### ISSUE TITLE
Should there be a WritableStream.close() method?

### ISSUE THREAD

**Issue by mkruisselbrink** [whatwg/streams#1007]
It appears that currently the only way to close (without aborting) a writable stream is by calling `getWriter`, and then calling `close()` on that writer. Would it make sense to also expose `close()` directly on `WritableStream` itself?

Presumably you'd only be able to call such a method if the stream isn't locked (just like abort on the stream can only be called if the stream isn't locked).

**Comment by ricea** [comment]
`close()` is certainly the odd-one-out here, as both `cancel()` and `abort()` have versions that operate on plain unlocked objects.

On the other hand, I don't find the `cancel()` and `abort()` variants all that useful anyway. Writing `writable.getWriter().close()` is not a terrible burden.

I assume this was a conscious choice when `WritableStream` was converted to be lockable. @domenic, do you happen to remember what the motivation was?

**Comment by domenic** [comment]
It looks like this was more of a historical accident than anything. We intended to add close in https://github.com/whatwg/streams/issues/319, but I guess the initial pull requests didn't do so. I'd like to add it.

**Comment by ricea** [comment]
Okay. I have no objection. I'm hoping some enthusiastic person will step up with a PR :smile:

**Comment by MattiasBuelens** [comment]
I'll pick this up. Should be simple enough. 🙂

**Comment by ricea** [comment]
Fixed in #1011.
