### ISSUE TITLE
[Question] how do you "unpipe"?

### ISSUE THREAD

**Issue by jimmywarting** [whatwg/streams#1012]
i want to have a transform stream that sits in the middle of one readable stream (source) and writable stream (dest) and i want to have that transformer stream in the middle to filter out the beginning of the stream until it encounter a certain value. After that i just want everything else to pass through. 

While this solution works i wonder if there is a better way to only close the transform stream.

```js
// (source)
a = new ReadableStream({
  start (ctrl) {
    ctrl.enqueue('a')
    ctrl.enqueue('b')
    ctrl.enqueue('c')
    ctrl.enqueue('d')
  }
})

goThrought = false

b = new TransformStream({
  transform (chunk, ctrl) {
    if (goThrought) {
      return ctrl.enqueue(chunk)
    }

    if (chunk === 'b') {
      // filter out first chunks
      // preferable unpipe this transform stream so it
      // goes directly from a -> c
      goThrought = true 
    }
  }
})

// (dest)
c = new WritableStream({
  write (chunk) {
    console.log(chunk)
  }
})

a.pipeThrough(b).pipeTo(c)
```

expected output: c, d

**Comment by MattiasBuelens** [comment]
You could create an `AbortController` and pass its `signal` to `a.pipeTo(b)` and `b.pipeTo(c)`, allowing you to abort both pipes. You should set `preventAbort = true` and `preventCancel = true` to prevent `a`/`c` from becoming canceled/aborted when you do this. See [this comment](https://github.com/whatwg/streams/issues/1004#issuecomment-508271679) for an example.

**Comment by jimmywarting** [comment]
> My suggestion: stick with your current solution. 😉

OK, Thanks. might just do that.

Will try other solution too (if i can't come up with any better solution), maybe try to discard the first bytes before passing the stream onwards and hopefully remove the transform stream altogether.
