### ISSUE TITLE
Stop using "transforming"

### ISSUE THREAD

**Issue by annevk** [whatwg/streams#1013]
As per @Ms2ger this is now part of "upon settling" and defined in IDL. (Context: https://github.com/w3ctag/promises-guide/pull/61.)

**Comment by annevk** [comment]
See https://github.com/heycam/webidl/issues/783 though.

**Comment by domenic** [comment]
This was fixed in https://github.com/whatwg/streams/commit/d26db0ea6ab72bee56b3d5c4512349fb028fa04d.
