### ISSUE TITLE
Make underlying sink writes abortable

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#1015]
We should pass an `AbortSignal` object to underling sink `write()` calls and signal abort if the stream is aborted. `write()` implementations could either ignore it (giving the existing behaviour), or reject the promise they returned, making the abort operation complete more quickly than it would otherwise.

This would also work with `pipeTo()` abort (as long as _preventAbort_ was not set).

**Comment by MattiasBuelens** [comment]
Yes, please! 😀

I've been trying to make a fully spec-compliant `TransformStream` polyfill that uses native `ReadableStream` and `WritableStream`, so only using their public API. However, I ran into problems with [TransformStreamDefaultSinkWriteAlgorithm](https://streams.spec.whatwg.org/#transform-stream-default-sink-write-algorithm), which needs to check whether the stream is `erroring` (i.e. `abort()` has been called) before it transforms the chunk. Currently, this is impossible to know using only the public API. Having an `AbortSignal` passed to each sink `write()` call would solve this.

**Comment by MattiasBuelens** [comment]
Random thought: what about transform streams? Should we also pass a signal to `transform()`, so the underlying transformer can stop early if it knows the transformed chunk will no longer be used? 🤔

Slightly related: an underlying transformer currently has no way to know that its writable side has become aborted, or that its readable side has become cancelled. There's only `flush()`, which is called when the writable side becomes closed. Do we need an `abort(reason)` and/or `cancel(reason)` method on a transformer?

**Comment by MattiasBuelens** [comment]
We could also add a `signal` property to `WritableStreamDefaultController`, since the abort signal doesn't really need to change between two `write()` calls.

**Comment by yutakahirano** [comment]
It's good to make `close()` potentially abortable too.

We are discussing whether we want an abort operation which takes effect immediately even when there is an in-flight write or close operation (w3c/webtransport#248), but this should be a solution for the problem.

cc: @jan-ivar
