### ISSUE TITLE
Links to "a new promise", "a promise resolved with", etc. are broken

### ISSUE THREAD

**Issue by jswalden** [whatwg/streams#1020]
Various terms of art like "a new promise" and "a promise resolved with" are links to a W3C document like https://www.w3.org/2001/tag/doc/promises-guide/#a-new-promise or so.  Since this text was written, however, that document has delegated its definitions to WebIDL.  Affected links need to be changed to https://heycam.github.io/webidl/#a-promise-resolved-with and similar (against whatever is the canonical version of that URL, not sure if the heycam-specific URL is that).

**Comment by jswalden** [comment]
Note that Web IDL is using the same anchor identifiers, but the phrases it uses for them are somewhat different -- so streams uses "a new promise" but Web IDL says "To create a new Promise<T> in a Realm realm".

It might be worth changing the streams language to the new Web IDL language -- including passing the current realm explicitly.

Or, streams could define its own internal operation -- presumably using the current language -- that invokes the new language, and passes along the current realm explicitly.

I haven't looked at all the affected operations, but it looks like this isn't as simple as I initially was thinking it was, of just changing some link URLs and that being that.

**Comment by ricea** [comment]
@domenic I assume for this standard, we always create promises in the current realm. Is that correct?

**Comment by MattiasBuelens** [comment]
There's [this note](https://streams.spec.whatwg.org/#readable-stream-pipe-to) in `ReadableStreamPipeTo`:
> Various abstract operations performed here include object creation (often of promises), which usually would require specifying a realm for the created object. However, because of the locking, none of these objects can be observed by author code. As such, the realm used to create them does not matter.

The way I understand this: the promise returned by `pipeTo` **must** be in the current realm, but the intermediate promises (e.g. the actions passed to "shutdown with an action", or the write promises from "wait until every chunk that has been read has been written") **could** be in a different realm.

**Comment by domenic** [comment]
In this standard, we currently create promises always in the current realm, since we follow ES spec conventions. So we should probably start there.

However, we may at some point want to align with [the general web platform guidance](https://html.spec.whatwg.org/multipage/webappapis.html#realms-settings-objects-global-objects):

> In general, web platform specifications should use the relevant concept, applied to the object being operated on (usually the this value of the current method). This mismatches the JavaScript specification, where current is generally used as the default (e.g. in determining the JavaScript realm whose Array constructor should be used to construct the result in Array.prototype.map). But this inconsistency is so embedded in the platform that we have to accept it going forward.

This is complicated by the fact that the reference implementation (or any pure-JS implementation) has no way of accomplishing this, so testing will have to be done against browsers.
