### ISSUE TITLE
What the difference between ReadableStream.cancel() and ReadableStreamDefaultReader.cancel()?

### ISSUE THREAD

**Issue by determin1st** [whatwg/streams#1033]
What the difference between ReadableStream.cancel() and ReadableStreamDefaultReader.cancel()?

**Comment by ricea** [comment]
They are the same. ReadableStream.cancel() is just a convenience method, roughly equivalent to
```javascript
const reader = readable.getReader();
reader.cancel();
reader.releaseLock();
```

**Comment by determin1st** [comment]
@ricea so, is it the same bound function or maybe the `readable.cancel` is a shortcut which calls `reader.cancel` (or reverse)?

Also, does the workflow order matter if I do:
```javascript
reader.releaseLock();
reader.cancel();
```

**Comment by MattiasBuelens** [comment]
> so, is it the same bound function or maybe the `readable.cancel` is a shortcut which calls `reader.cancel` (or reverse)?

They are different functions, see the spec [here](https://streams.spec.whatwg.org/#rs-cancel) and [here](https://streams.spec.whatwg.org/#default-reader-cancel). They have different preconditions, but they have the same effect (calling the abstract operation [ReadableStreamCancel](https://streams.spec.whatwg.org/#readable-stream-cancel)).



> Also, does the workflow order matter if I do:
> 
> ```js
> reader.releaseLock();
> reader.cancel();
> ```

Yes, the order matters. You cannot call any reader methods after you've released the lock. So `releaseLock()` must always be last.

**Comment by determin1st** [comment]
> They are different functions, see the spec [here](https://streams.spec.whatwg.org/#rs-cancel) and [here](https://streams.spec.whatwg.org/#default-reader-cancel). They have different preconditions, but they have the same effect (calling the abstract operation [ReadableStreamCancel](https://streams.spec.whatwg.org/#readable-stream-cancel)).


Does it mean, that the better/proper/primary/shorter cancellation route is:
```javascript
reader.releaseLock();
stream.cancel();
```

Also, does the "loss of interest" signaling means that i shall not do:
```javascript
reader = stream.getReader();
```
..anymore, and i should recreate a stream?

**Comment by MattiasBuelens** [comment]
> Does it mean, that the better/proper/primary/shorter cancellation route is:
> 
> ```js
> reader.releaseLock();
> stream.cancel();
> ```

It's more a question of whether you already have a reader locked to your stream or not.
* If you have a reader, you must use `reader.cancel()`, because `stream.cancel()` only works when your stream is unlocked.
* If you have a reader, but you don't need it anymore after cancelling, you can do either `reader.cancel(); reader.releaseLock()` or `reader.releaseLock(); stream.cancel()`. Both are equivalent, and take up pretty much the same amount of code.
* If you don't have a reader, you could cancel ["the long way"](https://github.com/whatwg/streams/issues/1033#issuecomment-600933751), or you can use `stream.cancel()` to get the same result.

> Also, does the "loss of interest" signaling means that i shall not do:
> 
> ```js
> reader = stream.getReader();
> ```
> 
> ..anymore, and i should recreate a stream?

Yes. Canceling a stream is a "terminal" action: the stream can never become readable again. You will no longer be able to read chunks from it, even if you acquire a new reader.

**Comment by determin1st** [comment]
oke, that clarifies.. so if the `reader.read()` is not settled yet, i can't do `reader.releaseLock()` (according to the spec), so i can't `stream.cancel()` and the only valid route is:

> If you have a reader, you must use reader.cancel(), because stream.cancel() only works when your stream is unlocked.

What should happen in the same condition of `reader.read()` promise (not settled) when i do:
```javascript
reader.cancel();
```
Will it be resolved or rejected? (i find hard to determine it from the spec)

**Comment by MattiasBuelens** [comment]
In the spec, [ReadableStreamCancel](https://streams.spec.whatwg.org/#readable-stream-cancel) calls [ReadableStreamClose](https://streams.spec.whatwg.org/#readable-stream-close), which will resolve all outstanding `read()` promises with `{ done: true, value: undefined }`.

**Comment by determin1st** [comment]
@MattiasBuelens alright, thanks for you help!

**Comment by lucgagan** [comment]
How to tell if the stream was cancelled?
