### ISSUE TITLE
simpler, less stateful basic streams?

### ISSUE THREAD

**Issue by othiym23** [whatwg/streams#104]
At the summit today, @evancz, @Gozala, and I sat down to try to hash out a version of the streams API that was the simplest possible interface that would satisfy the following requirements (but maybe not all at the same time, or without subclassing):

* honors the basic contract of an (event) stream, with the operations `put` and `take` that atomically write to a fixed-length queue / buffer / channel
* can *exert* backpressure
* can *respond* to backpressure
* supports either or both of transient failure (i.e. signaling failure in-band) or permanent invalidation (marking the whole stream as errored-out)
* cancellable
* supports the usual set of functional combinators (map, accumulate, filter, drop)

After a little back and forth, we came up with a pretty minimal set of operations:

* createStream(size): returns an object with the methods `{ put, take, getSize, getFilledCount }`, and allocates a backing queue of size `size`. The methods look like:
  * `put`: put a chunk / object / event on the stream. Returns a `Promise` that will be resolved to the value put when the stream is again writable, rejects the promise with an error on (any) failure
  * `take`: Returns a `Promise` that will be fulfilled with the next / current value from the stream, or rejected with an error if one comes down from upstream.
  * `getSize`: Returns the capacity of the queue.
  * `getFilledCount`: Returns the number of slots in the queue that are presently filled. Could also be expressed as its converse, `getFreeCount` -- whatever feels most natural with experience.

We worked through a few of the common use cases and compared this with @Gozala's [gist](https://gist.github.com/Gozala/7242467) and it seemed like this was able to handle a wide variety of use cases fairly straightforwardly:
* backpressure strategies can be added via composition (and perhaps access to the underlying promises) by passing these simple streams into high water mark / low & high water mark classes
* completely agnostic to the contents of the slots (obviously)

It also eliminates the started / waiting state machine that sits in the middle of `BaseReadableStream` (and seems like a natural evolution of @creationix's min-streams proposal). The cost of this approach is that either it tempts the wrath of Zalgo (although @Gozala's generators-based approach looks pretty clean in this regard) or it creates, to speak to @Benvie's point, a whole bunch more promises to deal with.

It also seems that as long as the interface is implemented in a standard way, it should be easy to drop in implementations that use writev internally, or use the "native piping" that Jonas Sicking was discussing. All while keeping a pretty simple core implementation that doesn't conflate too many concerns / complect unnecessarily.

@Gozala / @evancz, is this more or less what you were thinking?

**Comment by domenic** [comment]
So, thinking has evolved a lot since this original issue. One the one hand, the recently-merged PR introduced async read(), so that should make some people happy. On the other, we've learned a *lot* more about byte streams and the intricacies behind them. (I'm doing a [blog series](https://blog.domenic.me/byte-sources-introduction/) to explain the constraints.) I think it's time to close off this discussion, but thanks everyone for pushing it.
