### ISSUE TITLE
Removing non-existent constructors from MDN and BCD

### ISSUE THREAD

**Issue by sideshowbarker** [whatwg/streams#1043]
MDN contains articles for the following constructors:

* https://developer.mozilla.org/docs/Web/API/ReadableByteStreamController/ReadableByteStreamController
* https://developer.mozilla.org/docs/Web/API/ReadableStreamBYOBRequest/ReadableStreamBYOBRequest
* https://developer.mozilla.org/docs/Web/API/ReadableStreamDefaultController/ReadableStreamDefaultController
* https://developer.mozilla.org/docs/Web/API/WritableStreamDefaultController/WritableStreamDefaultController

…and BCD also contains corresponding data for those constructors.

However, none of those constructors are actually in the spec.

So, should we delete the MDN articles and the corresponding data in BCD?

**Comment by ricea** [comment]
I'm in favour of removing them from MDN.

**Comment by a2sheppy** [comment]
I've deleted the articles from MDN. @sideshowbarker is working on a PR to update the BCD records.

**Comment by sideshowbarker** [comment]
Raised https://github.com/mdn/browser-compat-data/pull/6314 for the removal from BCD

**Comment by ricea** [comment]
Thank you!

**Comment by sideshowbarker** [comment]
@ricea Thanks for the confirmation (@MattiasBuelens too :)
