### ISSUE TITLE
Remove https://streams.spec.whatwg.org/#ts-constructor step 12 

### ISSUE THREAD

**Issue by youennf** [whatwg/streams#1065]
Step 9 is: Let startPromise be a new promise.
Step 12 is: Let startPromise be a new promise.

Most probably step 12 should be removed.

**Comment by ricea** [comment]
Thanks. It was introduced accidentally in https://github.com/whatwg/streams/pull/1035. As you say, the second one should be removed. I will make a PR tomorrow.
