### ISSUE TITLE
Introduce ReadableStream<T> generics typing.

### ISSUE THREAD

**Issue by yoichio** [whatwg/streams#1075]
Currently we don't have a typing that what `Promise<T>` type returns if we call `readablestream.getReader().read()`.
This makes Web IDL readability bad.
For example, 
`new QuicTransport('example.com', 10001).receiveStreams()` returns so typed `ReadableStream<ReadableStream<Uint8Array>>` but we can not represent it:
https://wicg.github.io/web-transport/#dom-datagramtransport-receivedatagrams

**Comment by ricea** [comment]
We discussed this in #678 and concluded it wasn't needed. The only thing which has changed since is that we've converted the standard to use WebIDL. @domenic what do you think?

**Comment by domenic** [comment]
I maintain that comments are the right place to put this information, since it doesn't help code generators.

**Comment by ricea** [comment]
Okay, closing WontFix.
