### ISSUE TITLE
Returning after performing error steps in ReadableStreamBYOBReaderRead

### ISSUE THREAD

**Issue by nidhijaju** [whatwg/streams#1091]
While investigating a WPT failure, I found that if we don't return after this
> If stream.[[state]] is "errored", perform readIntoRequest’s error steps given stream.[[storedError]].

in [ReadableStreamBYOBReaderRead()](https://streams.spec.whatwg.org/commit-snapshots/41a968974c91e05b20738f77d0b2731ec7391e92/#readable-stream-byob-reader-read) we hit the second assert in [AddReadIntoRequest()](https://streams.spec.whatwg.org/commit-snapshots/41a968974c91e05b20738f77d0b2731ec7391e92/#readable-stream-add-read-into-request)

> Assert: stream.[[state]] is "readable" or "closed".

Just wondering should we be returning after performing the error steps then, or is there another behaviour that is expected here?

**Comment by domenic** [comment]
Great catch! I think we should hide the last step, i.e.

> Return ! ReadableByteStreamControllerPullInto(stream.[[controller]], view, readIntoRequest).

behind an "Otherwise", like is done in ReadableStreamDefaultReaderRead right below.

The reference implementation already contains the corresponding `else`, which is why it passes the WPTs:

```js
function ReadableStreamBYOBReaderRead(reader, view, readIntoRequest) {
  const stream = reader._stream;

  assert(stream !== undefined);

  stream._disturbed = true;

  if (stream._state === 'errored') {
    readIntoRequest.errorSteps(stream._storedError);
  } else {
    ReadableByteStreamControllerPullInto(stream._controller, view, readIntoRequest);
  }
}
```

**Comment by nidhijaju** [comment]
Okay, sounds good! I'll make a pull request adding that in.
