### ISSUE TITLE
Add reader-type asserts to ReadableStream abstract operations

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#1094]
Several ReadableStream abstract operations are only called with one particular type of reader. For clarity, it would be good to add assertions of what kind of reader they are called with.

A (hopefully complete) list of miscellaneous operations that assume the reader type:

ReadableStreamFulfillReadIntoRequest
ReadableStreamFulfillReadRequest
ReadableStreamGetNumReadIntoRequests
ReadableStreamGetNumReadRequests

Already have assertions:

ReadableStreamAddReadIntoRequest
ReadableStreamAddReadRequest

**Comment by ricea** [comment]
@nidhijaju Do you want to take this on?

**Comment by nidhijaju** [comment]
Yes, I can do this.
