### ISSUE TITLE
Test: "default ReadableStream getReader() should only accept mode:undefined"

### ISSUE THREAD

**Issue by evilpie** [whatwg/streams#1122]
The test mentioned in the title fails on https://wpt.fyi/results/streams/readable-streams/general.any.html?label=experimental&label=master&aligned. I am still getting used to reading the streams spec, but I can only find one definition of getReader: https://streams.spec.whatwg.org/#rs-get-reader.

I don't see any indication that this should not support "byob".

**Comment by ricea** [comment]
"byob" is only supported for byte streams. The test doesn't create a byte stream. See https://streams.spec.whatwg.org/#set-up-readable-stream-byob-reader step 2 for where this is enforced.

**Comment by evilpie** [comment]
Actually I think I understand the problem. The only supported values for `mode` are undefined and "byob". This is enforced via WebIDL. Seems like Firefox is incorrectly throwing a RangeError instead of a TypeError.

**Comment by MattiasBuelens** [comment]
The specification used to throw a `RangeError` (see [snapshot of 6 April 2020](https://streams.spec.whatwg.org/commit-snapshots/cfcd303a38158e4ec3837d1028158c88d505c35d/#rs-get-reader)), but this was changed to a `TypeError` as a result of the WebIDL rewrite. So it's not really "incorrect", just "no longer correct". 😉
