### ISSUE TITLE
Close should be idempotent

### ISSUE THREAD

**Issue by mitranim** [whatwg/streams#1136]
Currently, the spec requires some "close" operations to be non-idempotent:

> The `close()` method steps are:
>   If `! ReadableStreamDefaultControllerCanCloseOrEnqueue(this)` is false, throw a TypeError exception.
>   Perform `! ReadableStreamDefaultControllerClose(this)`.

The following code causes an exception in both Chrome and Deno:

```js
let ctrl
new ReadableStream({start(val) {ctrl = val}})

ctrl.close()
ctrl.close()
// error: Uncaught TypeError: The stream controller cannot close or enqueue.
```

Making "close" operations non-idempotent is a questionable choice (severity = minor). I'm under the impression that in modern high-level languages, there's a general trend of making all close operations idempotent. When dealing with callback-infested APIs, it's common to have multiple code paths / callbacks leading to the same cleanup call. Code will assume that it's okay to `.close()` many times, erring on the side of "closing for sure" rather than leaking.

When using Deno (which appears to implement streams faithfully to spec), this was causing minor practical issues for me; sometimes a stream would be closed by the underlying runtime due to client disconnect, and sometimes it wouldn't; my code was _always_ calling `.close()`, which sometimes resulted in unhandled exceptions.

Of course there's an easy workaround of `try/catch`, but it shouldn't be necessary here.

The same logic applies to `.cancel()` and other forms of deinit/abort/cleanup, but I haven't checked if those have the same issues.

**Comment by domenic** [comment]
We designed it this way intentionally, because in our experience code which closes the stream twice is buggy code.

**Comment by MattiasBuelens** [comment]
> sometimes a stream would be closed by the underlying runtime due to client disconnect, and sometimes it wouldn't

If you're the one implementing the source of a `ReadableStream`, you should have exclusive ownership over the `ReadableStreamDefaultController`, so only your code should be able to call `controller.close()`. The only way a consumer of your stream can cause it to become closed, is when the consumer cancels the stream. You should handle this case by implementing a `cancel()` method on the source.

On the other hand, if the underlying runtime is actually calling `controller.close()` without your knowledge... then that sounds like a bad runtime behavior. It should probably cancel the stream instead to clean it up.

> The same logic applies to `.cancel()` and other forms of deinit/abort/cleanup, but I haven't checked if those have the same issues.

Calling `cancel()` a second time does nothing (see step 2 of [ReadableStreamCancel](https://streams.spec.whatwg.org/#readable-stream-cancel)).

**Comment by mitranim** [comment]
I see, thanks for taking the time to explain.

I have a lot of working code where multi-deinit ensures reliable cleanup, and struggling to recall any code where multi-deinit could indicate a bug or an issue. But it sounds like you've seen some examples of that. Since it's intentional, I'll have to drop the argument. Thanks for consideration.
