### ISSUE TITLE
Internal promises need to be handled before they reject

### ISSUE THREAD

**Issue by jespertheend** [whatwg/streams#1139]
At the moment the spec takes care of rejected promises in the following way:

1. Create a rejected promise
2. Mark the promise as handled

or

1. Reject the promise
2. Mark the promise as handled

This happens in [WritableStreamDefaultWriterEnsureClosedPromiseRejected](https://streams.spec.whatwg.org/#writable-stream-default-writer-ensure-closed-promise-rejected) for instance.

However, according to the [Promises spec](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-host-promise-rejection-tracker) the UA needs to do checks the moment a Promise rejects. So if you mark a promise as handled after it rejects, it is already too late.

This can be seen from running the following in the console in Chromium:
```js
ws = new WritableStream();
writer = ws.getWriter();
writer.releaseLock();
```

If 'Pause on exceptions' is enabled, script excecution gets paused twice. Once for the `ready` promise and once for the `closed` promise.

The Chromium issue for this is tracked in https://crbug.com/1132506

**Comment by MattiasBuelens** [comment]
This seems very similar to MattiasBuelens/web-streams-polyfill#8. But that was reported as a Node-specific issue, I didn't think this could also affect browsers. 🤔 

The "fix" back then was to first create a pending promise, then mark it as handled, then reject it. Hopefully we can handle this in a cleaner way for the specification. Maybe add a "create a an already-handled rejected promise" helper to Web IDL?

**Comment by domenic** [comment]
This isn't a specification issue. This is related to specific implementations (particularly Chromium devtools) which do non-specified behavior around rejected promises. So I don't think we should change anything in the specification here.

**Comment by domenic** [comment]
In particular the only impact of HostPromiseRejectionTracker in spec-land is the `unhandledrejection` and `rejectionhandled` events, which are batched up on task boundaries so as long as you handle it within a task it's fine.

**Comment by jespertheend** [comment]
Thanks for the info. I've got a fix ready for Chromium that works similar to the fix described by @MattiasBuelens but I wanted to check in with the spec to see if this would need to be changed as well.
