### ISSUE TITLE
When to use streams?

### ISSUE THREAD

**Issue by jan-ivar** [whatwg/streams#1153]
It's my impression this WG wants streams to be the platform primitive for consuming and producing streams of data asynchronously with back pressure.

However, such adoption is [not obvious to everyone](https://docs.google.com/document/d/10S-p3Ob5snRMjBqpBf5oWn6eYij1vos7cujHoOCCCAw/edit), and discussions like https://github.com/w3c/mediacapture-transform/issues/4 could use clearer guidance A) about this ambition, and B) criteria for when to use streams, and when not to.

For _promises_ the promise guide's [§ 2. When to use promises](https://www.w3.org/2001/tag/doc/promises-guide#when-to-use) set these criteria, which I believe successfully settled many a debate.

Is there a streams guide in the works (with a _When to use streams_ section)?

**Comment by jan-ivar** [comment]
(This is the subjective part)

> For _promises_ the promise guide's [§ 2. When to use promises](https://www.w3.org/2001/tag/doc/promises-guide#when-to-use) set these criteria, which I believe successfully settled many a debate.

For example, among those criteria were NOT: Is using promises less to type than callbacks? Is it simpler(-looking)? Because sometimes, using promises meant _more_ to type and read than with callbacks (especially before `async`/`await` came along). Instead the criteria were distinctly intrinsic to the nature of the operation of the API. They were good.

This may seem obvious in hindsight, but adopting promises throughout the platform wholesale as the idiomatic pattern for (most, based on these criteria) async behavior in all new APIs, I think was critical to its success. IOW, the prevalence of the pattern was itself fundamental to its utility/benefit/success, as it enabled [composition](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#composition). Going half-in would have been painful to the point of jeopardizing its success (with failure probably blamed on the new pattern).

And if people didn't like it, they could work around it with `p.then(successCallback, failureCallback)`.

### What's the corollary to streams?

Streams like promises have a learning curve, and (like promises had) a lack of enough established APIs using them to make the synergistic benefits obvious (not enough sources & sinks for critical mass yet). This takes me back to when promises were hard to argue for, because they weren't prevalent.

We are seeing this resurface in decisions being contemplated based on what seems "simpler", or based on simple comparisons between code examples (that aren't or cannot use `pipeTo` for instance), instead of asking: is there something a streams API prevent you from doing?

This is basically the streams pattern being challenged over and over. I hope there's enough feedback for a guide here.

**Comment by domenic** [comment]
Does https://github.com/whatwg/streams/blob/main/FAQ.md help?
