### ISSUE TITLE
srcObject

### ISSUE THREAD

**Issue by o-t-w** [whatwg/streams#1160]
One of the examples of a use case for streams given in the spec is "Video effects: piping a readable video stream through a transform stream that applies effects in real time."

Does the following code work?
```
const video = document.createElement('video');
video.srcObject = stream;
```

I'm a bit hazy in general about how MediaStream and streams relate to each other.

**Comment by MattiasBuelens** [comment]
That's not a thing... yet. The [MediaStreamTrack Insertable Media Processing using Streams](https://w3c.github.io/mediacapture-transform/) proposal aims to make that work, so I suggest you follow their progress over at [w3c/mediacapture-transform](https://github.com/w3c/mediacapture-transform). 🙂
