### ISSUE TITLE
ReadableStream.prototype.pipeline(...)

### ISSUE THREAD

**Issue by jasnell** [whatwg/streams#1184]
While the current `pipeTo()` and `pipeThrough()` are nice and functional, given how often we need to set up multi-step pipelines, it would be nice to have a `pipeline()` that would take multiple `TransformStream`s in a single operation...

e.g.

```js
const source = getReadableSomehow();
const transform1 = getTransform1();
const transform2 = getTransform2();
const transform3 = getTransform3();
const options = getPipeThroughOptions();

const readable = source.pipeline(transform1, transform2, transform3, options)

// Equivalent to:

const readable = source.pipeThrough(transform1, options)
                       .pipeThrough(transform2, options)
                       .pipeThrough(transform3, options)
```

**Comment by MattiasBuelens** [comment]
This is fairly easy to do in user-land. You can use the fact that `pipeThrough()` accepts a `{ readable, writable }` pair, where the two streams don't necessarily have to come from the same `TransformStream`:
```javascript
function pipeline(...transforms) {
  if (transforms.length === 0) return new TransformStream();
  let { readable, writable } = transforms[0];
  for (let i = 1; i < transforms.length; i++) {
    readable = readable.pipeThrough(transforms[i]);
  }
  return { readable, writable };
}

const transformChain = pipeline(transform1, transform2, transform3);
const readable = source.pipeThrough(transformChain, options);
```
This composes perfectly: `pipeline(pipeline(t1, t2), pipeline(t3, t4))` is equivalent to `pipeline(t1, t2, t3, t4)`. 🙂

I think, for now, it's fine to keep this in user land. If it gets more wide-spread adoption, we may consider standardizing it.
