### ISSUE TITLE
WritableStreamDefaultController uses AbortSignal on Worklet where it isn't exposed

### ISSUE THREAD

**Issue by evilpie** [whatwg/streams#1199]
I am not sure where the right place to open this issue is. [`WritableStreamDefaultController`](https://streams.spec.whatwg.org/#writablestreamdefaultcontroller) is exposed on `(Window,Worker,Worklet)` and uses `AbortSignal signal`. [`AbortSignal`](https://dom.spec.whatwg.org/#abortsignal) itself however is only exposed on `Window,Worker`.

**Comment by MattiasBuelens** [comment]
Good catch. I suppose the *intention* is that `AbortSignal` would also be exposed to worklets.

This should be fixed in #1176 together with whatwg/dom#1024.

**Comment by saschanaz** [comment]
Seems this is fixed.
