### ISSUE TITLE
`SetUpTransformStreamDefaultControllerFromTransformer` doesn't ensure that `transformAlgorithm` and `flushAlgorithm` return `Promise`

### ISSUE THREAD

**Issue by tschneidereit** [whatwg/streams#1201]
Step 1 of [TransformStreamDefaultControllerPerformTransform](https://streams.spec.whatwg.org/#transform-stream-default-controller-perform-transform) and step 3 of [TransformStreamDefaultSinkCloseAlgorithm](https://streams.spec.whatwg.org/#transform-stream-default-sink-close-algorithm) assume that `transformAlgorithm` and `flushAlgorithm` always return a `Promise`.

While this is true if the algorithms were set via the [TransformStream Set Up](https://streams.spec.whatwg.org/#transformstream-set-up) operation, it's not guaranteed for if a `TransformStream` is created via `new TransformStream()`: if a `transformer` argument with `transform` and `flush` methods on it is passed to the constructor, the algorithms stored result in their completion result, which might or might not be a `Promise`.

I *think* this can be addressed by creating the creation of `{transform,flush}AlgorithmWrapper` from the `Set Up` operation into [SetUpTransformStreamDefaultController](https://streams.spec.whatwg.org/#set-up-transform-stream-default-controller), which is called from both ways to create/initialize a `TransformStream`.

**Comment by MattiasBuelens** [comment]
This is handled by step 2 of [the `TransformStream` constructor](https://streams.spec.whatwg.org/commit-snapshots/7f7d68befc29d9cfa0c3b204e0e8b9217e941fd2/#ts-constructor):
> 2. Let _transformerDict_ be _transformer_, converted to an IDL value of type `Transformer`.

Note that [the `Transformer` interface](https://streams.spec.whatwg.org/commit-snapshots/7f7d68befc29d9cfa0c3b204e0e8b9217e941fd2/#dictdef-transformer) declares `transform` and `flush` as promise-returning callbacks, so Web IDL handles converting a non-promise return value into a promise. See https://github.com/whatwg/streams/issues/1161#issuecomment-902032645 for more information.

**Comment by tschneidereit** [comment]
Aah, that's the bit I was missing. Thank you, @MattiasBuelens!
