### ISSUE TITLE
Why is `size` just a function?

### ISSUE THREAD

**Issue by j-f1** [whatwg/streams#1226]
Both [`ByteLengthQueuingStrategy`](https://streams.spec.whatwg.org/commit-snapshots/9538b77788be6ff7304fcf582823e3d56463ef2a/#bytelengthqueuingstrategy) and [`CountQueuingStrategy`](https://streams.spec.whatwg.org/commit-snapshots/9538b77788be6ff7304fcf582823e3d56463ef2a/#countqueuingstrategy) are defined as having a `readonly attribute Function size`. However, the definition for [`QueuingStrategy`](https://streams.spec.whatwg.org/commit-snapshots/9538b77788be6ff7304fcf582823e3d56463ef2a/#dictdef-queuingstrategy) has a specific type for this field: [`QueuingStrategySize`](https://streams.spec.whatwg.org/commit-snapshots/9538b77788be6ff7304fcf582823e3d56463ef2a/#callbackdef-queuingstrategysize). Is there a reason these two interfaces do not use the more specific type?

**Comment by domenic** [comment]
This is due to how Web IDL works. The type of attributes don't really matter, and it's easier to create a `Function` in spec text. Whereas the types of dictionary members have normative impacts on how inputs are processed and called.

Hope this helps!
