### ISSUE TITLE
gRPC support

### ISSUE THREAD

**Issue by 0xAlcibiades** [whatwg/streams#1249]
https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md

I'm wondering what, if anything, is still needed to support gRPC via whatwg streams?

**Comment by wenbozhu** [comment]
I wrote the above doc. grpc-web (github.com/grpc/grpc-web) supports fetch/streams for responses. There is no plan to support upload streams as the feature is enabled only with H2 (which is a runtime condition) and HTTPS as a result.
