### ISSUE TITLE
Should `ReadableStreamClose(stream)` also close pending read requests in case of ReadableStreamBYOBReader

### ISSUE THREAD

**Issue by debadree25** [whatwg/streams#1294]
On reading the spec for https://streams.spec.whatwg.org/#readable-stream-close we see it asks to perform close steps in case of [ReadableStreamDefaultReader](https://streams.spec.whatwg.org/#readablestreamdefaultreader) but what about the case when its a byob reader? this was first noted when trying to implement https://github.com/nodejs/node/issues/47993 a simple example: 

```mjs
async function test() {
  const toPull = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'];
  const st = new ReadableStream({
    type: 'bytes',
    start(controller) {},

    pull(controller) {
      const chunk = toPull.shift();
      if (chunk === undefined) {
        controller.close();
        return;
      }

      controller.enqueue(new TextEncoder().encode(chunk));
    },
  });

  const reader = st.getReader({ mode: 'byob' });
  const decoder = new TextDecoder();

  console.log('start');
  let result;
  do {
    result = await reader.read(new Uint8Array(100));
    if (result.value !== undefined) console.log(decoder.decode(result.value));
  } while (!result.done);
  console.log('end');
}

await test();
```

would expect both start and end to be printed to console but both node and chrome give the following output:

```console
start
a
b
c
d
e
f
g
h
i
j
```

this in contrast to `ReadableStreamError()` which branches for both byob and normal. Is this behaviour intended? i am unable to understand unfortunately 😅 any help in understanding would be greatly appreciated! 

Thank You!

**Comment by ricea** [comment]
Yes, this is hard to understand. For a while I thought it was a bug, and then I remembered we did it this way so that the buffer can be returned to the user. I think [example 10.5](https://streams.spec.whatwg.org/#example-rbs-pull) does it correctly. You need to call `controller.byobRequest.respond(0)` after `controller.close()`.

**Comment by debadree25** [comment]
ahah! understood thanks so much for explaining @ricea probably need to include such an example in the node docs too
