### ISSUE TITLE
Should delegate functions of underlying sink/source return promises or call given functions

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#130]
cc/ @yutakahirano

I investigated how continuous call to `close()` and `abort()` of WritableStream results in `[[onClose]]` and `[[onAbort]]` call.

If `close()` returns a non-promise value synchronously, i.e. it complete successfully and synchronously, the returned value will be resolved to a promise, and "upon fulfillment" code will be run asynchronously. This means the state doesn't change to `"closed"` immediately on `close()` call. It stays to be `"closing"`. If `abort()` is called right after `closed()` call in the same task, it invokes `[[onAbort]]` though `close()` has finished synchronously.

I wonder if we want to allow `[[onAbort]]` being called after successful and synchronous `[[onClose]]`. Maybe we want to hide this kind of cumbersome state checking inside streams not to bother underlying sink implementer. Like what we're doing for `write()`, we could pass some method like `signalDone` to have a stream get notified of completion of a delegate method synchronously and change the state synchronously.

This question can be generalized as to figure out "clear rule to choose notification method for delegate functions on underlying sink/source".

I briefly discussed this with @yutakahirano. We also came up with an alternative that we delay both `[[onClose]]` and `[[onAbort]]` execution by putting them into the micro task queue by having an internal promise for this purpose and append (then-ing) state changing code, `[[onClose]]` and `[[onAbort]]` to the promise.

```
this.current = this.current.then(
  => check_state(); call_delegate().then(
    => change_state(); ...) ...
```

**Comment by domenic** [comment]
I think this is largely close-able now. Especially with the changes from wait() to ready.
