### ISSUE TITLE
"read all bytes" algorithm support for stringifiers

### ISSUE THREAD

**Issue by jasnell** [whatwg/streams#1312]
### What problem are you trying to solve?

The `read all bytes` algorithm currently defined in the spec is currently limited to `Uint8Array` values:

![image](https://github.com/whatwg/streams/assets/439929/82af8935-6d46-4ad5-9252-9a60fd4cfb63)

It would be helpful if this algorithm allowed for values with `stringifiers` to be used as well. Specifically, if the value has a `stringifier` then the value would be converted to a string then UTF-8 encoded for the purpose of the `read all bytes` algorithm. This would allow, for instance, a stream of strings or various types of objects to be read:

```js
const rs = ReadableStream.from(['hello', ' ', {toString() { return 'world'; }}]);
const res = new Response(rs);
await res.text(); // 'hello world'
```

**Comment by domenic** [comment]
I'm pretty firmly against this. Byte streams should be limited to streams of Uint8Arrays. Use a transform stream if you're getting the data in the wrong format. Then you can clearly choose the correct encoding, for example, instead of assuming UTF-8.
