### ISSUE TITLE
Handeling backpressure on the Readable side of a transform stream

### ISSUE THREAD

**Issue by vstefanovic97** [whatwg/streams#1323]
### What is the issue with the Streams Standard?

This is actually more of a question than an issue, so sorry in advance.
I want to know how to handle backpressure for the ReadableSide of a transform stream.

For example I am trying to implement a replace text functionality, where I replace a string of text coming from a ReadableStream with text coming from a second Readable stream, so far I couldn't find any example for this using whatwg streams.

This is pseudo code, so for simplicity I'm pretending like the text to replace won't span chunk boundaries

```javascript
class Transformer {
  async transform(chunk, controller) {
    const foundTextIndex = chunk.indexOf('text to replace');
    
    if (foundTextIndex === -1) {
      controller.enqueue(chunk);
      return;
    }

    // Enqueue text before the part that needs to be replaced
    controller.enqueue(chunk.slice(0, foundTextIndex));
    
    // Enqueue the text from the second source
    // this is the part I'm not sure for which how to handle if we are adding
    // chunks to the readable sides internal queue even if it's full
    for await (const chunk of streamForReplacement) {
     controller.enqueue(chunk.slice(0, foundTextIndex));
     console.log(chunk);
   }
   
    // Enqueue text after replacement
    controller.enqueue(chunk.slice(foundTextIndex + 'text to replace'.length));
  }
}
```

One thing I saw thanks to good old `chatGTP` was to use `Promise.resolve()` to wait for the next event loop tick in case the `desiredSize` was negative.

For example
```javascript
class Transformer {
  async transform(chunk, controller) {
    const foundTextIndex = chunk.indexOf('text to replace');
    
    if (foundTextIndex === -1) {
      controller.enqueue(chunk);
      return;
    }

    // Enqueue text before the part that needs to be replaced
    controller.enqueue(chunk.slice(0, foundTextIndex));
    
    // Enqueue the text from the second source with backpressure support (maybe)
    for await (const chunk of streamForReplacement) {
     while (controller.desiredSize <= 0) {
       await Promise.resolve(); // wait for next tick to check if we can enqueue more chunks
     }
     controller.enqueue(chunk.slice(0, foundTextIndex));
   }
   
    // Enqueue text after replacement
    controller.enqueue(chunk.slice(foundTextIndex));
  }
}
```

I'm not sure if doing `Promise.resolve();` is valid, as I couldn't find any example dealing with this problem, and I want to know if there are better alternatives?

**Comment by ricea** [comment]
Probably something like StackOverflow is a more appropriate forum for this kind of question, but I will try to answer anyway.

The easiest "solution" is to ignore the whole problem and assume that `streamForReplacement` will always be a reasonably small size. Your `transform()` method won't get called again until all the data you enqueued is used up, so it will mostly work.

Depending on what your consumer is
```js
await Promise.resolve();
```
may not be sufficient to let backpressure be cleared. It doesn't give the browser the opportunity to handle any events from outside JavaScript. A portable approach that will let the browser get work done is
```js
await new Promise(resolve => setTimeout(resolve, 0));
```
Using a non-zero delay on setTimeout is even better if you can afford to wait a bit before you start to write again, because it will avoid consuming 100% CPU and running down your users' batteries.

In this case, abandoning TransformStream altogether may be the best option. `pipeThrough` can accept any pair of a ReadableStream and WritableStream, and writing the transform yourself will give you maximum control.

```js
function MyTransform() {
  let pullCalled;
  let pullCalledResolver;
  function clearPullCalled() {
    pullCalled = new Promise(resolve => { pullCalledResolver = resolve; });
  }
  clearPullCalled();
  let controller;
  let pipePromise;
  let identityTransform = new TransformStream();
  function startPiping() {
    const backpressureSniffingReadable = new ReadableStream({
      start(c) {
        controller = c;
      },
      pull() {
        pullCalledResolver();
      }
    }, { highWaterMark: 0 });
    controller = new AbortController();
    pipePromise = backpressureSniffingReadable.pipeTo(
        identityTransform.writable,
        {signal: controller.signal, preventAbort: true});
  }
  startPiping();
  const readable = identityTransform.readable;
  const writable = new WritableStream({
    async write(chunk, controller) {
      await pullCalled;
      clearPullCalled();

      const foundTextIndex = chunk.indexOf('text to replace');

      if (foundTextIndex === -1) {
        controller.enqueue(chunk);
        return;
      }

      // Enqueue text before the part that needs to be replaced
      controller.enqueue(chunk.slice(0, foundTextIndex));

      // Stop the current pipe.
      controller.signal();
      await pipePromise.catch({} => {});

      await streamForReplacement.pipeTo(identityTransform.writable,
                                        { preventClose: true });

      // Restart our pipe.
      startPiping();
    },

    close() {
      controller.close();
    },

    abort(err) {
      controller.error(err);
    }
  });
  return {readable, writable};
}
```
This is all untested but hopefully you get the idea.

I assume you know that if `'text to replace'` is split between two chunks this won't work. If you need to handle that, see https://streams.spec.whatwg.org/#example-ts-lipfuzz for an example.

**Comment by vstefanovic97** [comment]
@ricea I really appreciate you taking the time to answer my question.
Sorry again for posting the question here, but this is so specific I really doubted anyone on StackOverflow would answer it.

Your example really helped me to understand some things better after which I re-read the spec one more time.

Your example actually gave me some inspiration, and I think I have thought up a simpler way to do it, what do you think about:
```javascript
function MyTransform() {
  let identityTransform = new TransformStream();
  const readable = identityTransform.readable;
  const identityWritter = identityTransform.writable.getWriter();
  const writable = new WritableStream({
    async write(chunk) {
      await identityWritter.ready;

      const foundTextIndex = chunk.indexOf('text to replace');

      if (foundTextIndex === -1) {
        identityWritter.write(chunk);
        return;
      }

      await identityWritter.ready;

      // Enqueue text before the part that needs to be replaced
      identityWritter.write(chunk.slice(0, foundTextIndex));

      // Enqueue the text from the second source
      // this is the part I'm not sure for which how to handle if we are adding
      // chunks to the readable sides internal queue even if it's full
      for await (const chunk of streamForReplacement) {
        await identityWritter.ready;
        identityWritter.write(chunk);
      }

      await identityWritter.ready;

      // Enqueue text after replacement
      identityWritter.write(chunk.slice(foundTextIndex + 'text to replace'.length));
    },

    close() {
      identityWritter.close();
    },

    abort(err) {
      identityWritter.error(err);
    },
  });
  return { readable, writable };
}
```

This way I'm using the identity transforms writter in order to respect the backpressure, since we can await `identityWritter.ready;` to know if we can write again

**Comment by ricea** [comment]
That's nice and simple, great work!

**Comment by jedwards1211** [comment]
@MattiasBuelens I wonder if I'm missing something here...

In a `ReadableStream` we can handle backpressure by limiting the amount of data we enqueue in `pull()` according to `controller.desiredSize`.

But it seems like in a `TransformStream` we can't really put `controller.desiredSize` to good use.  Our `transform()` could limit the amount of data it enqueues, but any of the remaining data from the input chunk would just be lost.

So can we make any reasonable decisions with `TransformStreamDefaultController.desiredSize`?

Theoretically, there should be a clean way to implement a `TransformStream` where given an input chunk `{ n: 483 }`, it enqueues 483 output chunks, respecting backpressure.  But it seems impossible to do something like that within the API's current limitations.
