### ISSUE TITLE
https://www.facebook.com/pages/Ptsunan-Rubbre-Pabrik-Getah-Karet-Palembang-Kertapati/499702870401821?mibextid=rS40aB7S9Ucbxw6v

### ISSUE THREAD

**Issue by okta46** [whatwg/streams#1328]
### What is the issue with the Streams Standard?

https://www.facebook.com/pages/Ptsunan-Rubbre-Pabrik-Getah-Karet-Palembang-Kertapati/499702870401821?mibextid=rS40aB7S9Ucbxw6v

**Comment by nektro** [comment]
If this is an issue relating to the Streams Standard please complete one of the issue templates
