### ISSUE TITLE
Abort followed by write on WritableStream may invoke a null strategy algorithm

### ISSUE THREAD

**Issue by shannonbooth** [whatwg/streams#1331]
### What is the issue with the Streams Standard?

Consider the following test (simplification of https://github.com/web-platform-tests/wpt/blob/8686b7a6d288d3b2c22b5ddb5a21773619b22b85/streams/writable-streams/aborting.any.js#L57 to remove any infrastructure)

```html
<script>

function test() {
  const ws = new WritableStream();

  setTimeout(() => {
      const writer = ws.getWriter();
      const abortPromise = writer.abort("some error");
      writer.write(1);
  }, 0)
}

test();
</script>
```

The stack of calls from  [abort(reason)](https://streams.spec.whatwg.org/#default-writer-abort) are:

1.  [WritableStreamDefaultWriterAbort](https://streams.spec.whatwg.org/#writable-stream-default-writer-abort)
2.  [WritableStreamAbort](https://streams.spec.whatwg.org/#writable-stream-abort)
3. [WritableStreamStartErroring](https://streams.spec.whatwg.org/#writable-stream-start-erroring)
4. [WritableStreamFinishErroring](https://streams.spec.whatwg.org/#writable-stream-finish-erroring)

Step 12 of WritableStreamFinishErroring will then perform:

> 12. Let promise be ! stream.[[[controller]]](https://streams.spec.whatwg.org/#writablestream-controller).[[[AbortSteps]]](https://streams.spec.whatwg.org/#abstract-opdef-writablestreamcontroller-abortsteps)(abortRequest’s [reason](https://streams.spec.whatwg.org/#pending-abort-request-reason)).

Where [\[AbortSteps\](reason)](https://streams.spec.whatwg.org/#ws-default-controller-private-abort) will clear the write algorithms:

> 2. Perform ! [WritableStreamDefaultControllerClearAlgorithms](https://streams.spec.whatwg.org/#writable-stream-default-controller-clear-algorithms)([this](https://webidl.spec.whatwg.org/#this)).

Which includes the `strategySizeAlgorithm`:

> 4. Set controller.[[[strategySizeAlgorithm]]](https://streams.spec.whatwg.org/#writablestreamdefaultcontroller-strategysizealgorithm) to undefined.

Once abort has finished, [writer.write(chunk)](https://streams.spec.whatwg.org/#default-writer-write) is invoked.

In [WritableStreamDefaultWriterWrite](https://streams.spec.whatwg.org/#writable-stream-default-writer-write) step 4 is to:

> 4. Let chunkSize be ! [WritableStreamDefaultControllerGetChunkSize](https://streams.spec.whatwg.org/#writable-stream-default-controller-get-chunk-size)(controller, chunk).

Which will invoke the strategySizeAlgorithm:

> 1. Let returnValue be the result of performing controller.[[[strategySizeAlgorithm]]](https://streams.spec.whatwg.org/#writablestreamdefaultcontroller-strategysizealgorithm), passing in chunk, and interpreting the result as a [completion record](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-completion-record-specification-type).

However, this has been nulled out by the call to WritableStreamDefaultControllerClearAlgorithms earlier, as part of the `abort`.

The stream is in an errored state, and _should_ throw an exception, but this is only performed on step 9 of WritableStreamDefaultWriterWrite.

Speculatively, I think step 4. of `WritableStreamDefaultWriterWrite` could be moved to just after step 9 where the erroring status is checked, but I am not sure if that has unintended side effects / observable in some way we care about.

**Comment by shannonbooth** [comment]
Unfortunately reordering the step does cause unintended side effects - at least for my case it results in wpt.live/streams/writable-streams/bad-strategies.any.html assertion failure on WritableStreamAddWriteRequest for the stream state. https://streams.spec.whatwg.org/#writable-stream-add-write-request

Falling back to a size of 1 in the getter works for both cases.

**Comment by domenic** [comment]
I'll try to look into this in more detail later, but have you looked at what the reference implementation does in this case? It passes all the tests, including the one you're simplifying, so either the spec is correct already in some way, or there's a bug in the reference implementation which maybe could inspire us on how to fix the spec.

**Comment by domenic** [comment]
Ah, yep, overzealous catching of exceptions is precisely one of the ways the reference implementation can be buggy compared to the spec. (In the spec, "performing" a null algorithm is undefined behavior, whereas in JS it's just a catchable exception.)

Thanks for investigating; one of the editors (possibly myself) will work on trying to find a good solution here soon.
