### ISSUE TITLE
ReadableByteStreams: missing APIs

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#176]
- [x] `read()`: should be defined in terms of `this.readInto` (not in terms of `[[readInto]]`, note).
- [x] `pipeTo()`: if we have `read()`, can we just reuse that algorithm in the general case? How can we special-case for WritableByteStream to maximize efficiency? That part at least depends on knowing what WritableByteStream is.
- [ ] `pipeThrough()`: I think this should literally be `ReadableByteStream.prototype.pipeThrough = ReadableStream.prototype.pipeThrough`.
- [x] `cancel()`: doesn't seem that hard semantically.

**Comment by tyoshino** [comment]
Closing as the API is changing largely. See #300 instead.
