### ISSUE TITLE
Transform stream base class (or other helper) in toolbox

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#20]
Per @dominictarr at https://twitter.com/dominictarr/status/397223577931378689, this is important. I agree. Logging so I don't forget it.

**Comment by wanderview** [comment]
I mentioned this in IRC, but can we make a null transform function mean "make a dump buffered pipe"?  Or some other convenient way to do that.

**Comment by domenic** [comment]
This definitely exists now!
