### ISSUE TITLE
Should we "lock" readable streams while piping?

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#241]
Inspired by:
- https://github.com/slightlyoff/ServiceWorker/issues/452#issuecomment-60652562
- https://github.com/whatwg/streams/issues/97
- An offline email conversation with @acolwell

Right now, if you are piping a readable stream to a writable stream, you can also concurrently call `.read()`. Usually this will just cause a mess, but it fell out of the design naturally.

Both "off-main thread piping" (#97) and a similar situation with Fetch's Request class, which has a `.json()` method, deal with the hazards of "C++ readers" concurrent with potential "JS readers." Ideally once a stream is being read by C++, JS cannot touch it, both for performance and implementation-complexity reasons.

One solution for this might be to add some kind of "locking" mechanism so that only one consumer can read. But I don't know how to define that, without some kind of radical redesign that splits out the concept of readable stream into a stream and a stream reader or something like that.

Another possibility that would work quite well I think would be to lock the stream while it's being piped somewhere. That is, at the beginning of pipeTo, set a [[piping]] = true property; when pipeTo finishes, set [[piping]] = false. While [[piping]] is true, .read() instantly throws, saying that the stream is being piped elsewhere and cannot be read.

This would solve all of our problems that inspire this issue:
- It removes the potential author footgun of accidentally calling .read() and getting racy or unexpected results, and perturbing the pipe in progress, that @acolwell was worried about.
- Off-main-thread piping (of UA-created streams) would be able to react the same way, so that to author code it looks like any normal pipe.
- Via some sleight of hand, it solves `.json()`, by "explaining" `.json()` as piping to a concatenator stream. (See https://github.com/slightlyoff/ServiceWorker/issues/452#issuecomment-60843906) Under the hood the UA will probably not implement `.json()` that way, but what's important is that they _could_, with the same author-observable behavior---so that way, `.json()` isn't doing anything magic.

It has a few theoretical disadvantages, but I am not sure how big of a deal they are in practice:
- It means `ReadableStream.prototype.pipeTo` will no longer be implementable purely on top of the public readable interface; it will be using some private [[piping]] state, and some private version of the `.read()` method that doesn't throw while the stream is [[piping]]. This means e.g. it doesn't apply directly to ReadableByteStreams. (Note however that it still only uses public writable stream interfaces, unless we want to lock those too...)
- It removes the ability to pipe to multiple streams in order to have the one that is most free to accept writes pick them up. This sounds rare, but funnily enough just today I was asked about a npm package to do this. It could be built on top as a library though, similar to a tee stream but without any copies.

Note that this does _not_ disable the use case of e.g. .read()ing headers from a stream and then piping the rest of it, or piping with `{ preventCancel: false }` and .read()ing the leftover if the destination gets closed prematurely. It only disables concurrent pipes + reads, not sequential.

Would love thoughts from @tyoshino @yutakahirano @sicking and anyone else.

**Comment by tyoshino** [comment]
Took a look at `Locking Design Doc.md`. Almost all of the rationale looks good to me.

I agree that there's no compelling reason for exposing stream.isLocked, yet.

`lock.isActive` looks useful as Yutaka said (https://github.com/whatwg/streams/issues/241#issuecomment-65218999) but I also wonder if there's any concrete use case where this is required (not just useful).

`releaseLock()` maybe to make it more descriptive, you've included `Lock`. Right? Just `release()` would have any problem?

Even after release, reader's `closed`, `ready`, and `state` getters will simply delegate to the encapsulated stream as the note at https://streams.spec.whatwg.org/#reader-release-lock explains. I don't have strong opinion yet but wonder if this is useful or harmful.

**Comment by domenic** [comment]
Thanks for the review @tyoshino; sorry I didn't get a chance to pass it by you earlier. 

> lock.isActive looks useful as Yutaka said (#241 (comment)) but I also wonder if there's any concrete use case where this is required (not just useful).

Yeah, maybe we should remove it until someone asks for it?

I guess part of the reason I have it is that it's better to avoid forcing people to use try/catch. I can't think of a real world situation where you would, but it seems nicer to be able to do

```js
if (reader.isActive && reader.state === "readable") {
  console.log(reader.read());
} else {
  console.log("not locked!");
}
```

instead of

```js
if (reader.state === "readable") {
  try {
    console.log(reader.read());
  } catch (e) {
    console.log("not locked! or maybe another error?", e);
  }
}
```

> releaseLock() maybe to make it more descriptive, you've included Lock. Right? Just release() would have any problem?

I said releaseLock() since usually the variable will be `reader`, not `lock`. I.e., `reader.releaseLock()`. I also think this is a bit helpful to differentiate operations that pass through to the stream (like `read()` and `cancel()`) versus ones having do to with the reader and the lock it has acquired. Just `release()` sounds too similar to `cancel()` for me.

> Even after release, reader's closed, ready, and state getters will simply delegate to the encapsulated stream as the note at https://streams.spec.whatwg.org/#reader-release-lock explains. I don't have strong opinion yet but wonder if this is useful or harmful.

I at first had a design where they would fail but it turned out to be quite hard to write `pipeTo` correctly in that design, because `pipeTo` consults those properties a lot. For example in the design where closing a stream automatically releases any held locks, the check `source.state === "closed"` never works since by the time it's closed `state` becomes a throwing getter. If I recall even in designs without auto-release-on-close there were other problematic cases as well. So I think it is pretty useful in the end.

**Comment by tyoshino** [comment]
I was on vacation and didn't have time to do it, sorry. Thanks so much for great progress!

> I guess part of the reason I have it is that it's better to avoid forcing people to use try/catch.

Oh, I see. I'm now a little inclined to keep it.

> I said releaseLock() since ...

Got it!

> the check source.state === "closed" never works

Thanks for explanation. I understand and agree that it makes sense for transition-to-"closed" case.

When a reader is unlocked while the associated stream is readable/waiting, it's a bit weird to keep exposing the non-closed stream's status via the released reader. What do you think about making a reader look like a closed stream regardless for what kind of transition the unlock happened?

**Comment by tyoshino** [comment]
I.e. making
- `ready` return a resolved promise
- `state` return "closed"
- `closed` return a resolved promise

or keep it look waiting?

Ah, for errored case, we should make the reader look errored, sorry.

**Comment by domenic** [comment]
Hmm, that's interesting. I think it is better than what we have now, yes. I will open an issue to take care of it.
