### ISSUE TITLE
[Reader] Should resolve readyPromise on getReader() call?

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#258]
@yutakahirano pointed out that `readableStream.getReader()` must resolve the current promise stored in `[[readyPromise]]` and replace it with a new pending promise.

After `getReader()` call, the `ready` getter starts masking (starts returning `[[lockReleased]]`). But if `[[readyPromise]]` is already obtained like the following example, it stays to be working as `[[readyPromise]]` (i.e. receives and delivers resolution signal to `[[readyPromise]]`).

```
readableStream.ready.then( ... );
reader = readableStream.getReader();
```

It should be ok even if it gets resolved while the reader is active as we just see `readableStream.state` being `"waiting"` and get `[[lockReleased]]`.

If it doesn't get resolved while the reader is active, then, we cannot get notified of release of the lock. But I think in such a case, one who was watching the stream is not interested in release of lock but transition to readable/closed. So, this case is also not a problem?

Do you think this needs to be taken care of? @yutakahirano's suggestion was to resolve it on `getReader()` call.

**Comment by domenic** [comment]
Gah, I thought I had a test case for this. I guess I missed it though.

Right now the contract for `ready` is that it only fulfills if the state is no longer "waiting". I would prefer to keep that contract if possible. So I don't think resolving it on the `getReader()` call is very good.

I think this might be fixable via something like `return this._readyPromise.then(() => this._reader !== undefined ? this._reader.ready : undefined)` but last time I tried something like that I got stuck in an infinite ping-pong loop between the two `ready`s. I think it is still doable I just need to be careful.

> If it doesn't get resolved while the reader is active, then, we cannot get notified of release of the lock. But I think in such a case, one who was watching the stream is not interested in release of lock but transition to readable/closed. So, this case is also not a problem?

Yes, that is my feeling as well, since people asking for `ready` are really interested in transition to readable/closed/errored (i.e. anything but waiting).

**Comment by yutakahirano** [comment]
> Right now the contract for ready is that it only fulfills if the state is no longer "waiting". I would prefer to keep that contract if possible. So I don't think resolving it on the getReader() call is very good.

IIUC we already have waiting => waiting transition.

```
var stream = ...;
var reader = stream.getReader();
stream.ready.then(() => console.log('state becomes ' + stream.state));
reader.releaseLock();
```

The above code prints 'state becomes waiting', right?

**Comment by domenic** [comment]
Augh, good catch @yutakahirano, I should fix that one too!! `return this._reader._lockReleased.then(() => this._readyPromise)`, is my untested patch :).

Clearly need moar tests...

**Comment by tyoshino** [comment]
When reading the lock system, I came up with alternative that is to switch the target promise of each algorithm (e.g. `read()`). Discussed with @yutakahirano and summarized the ideas.

When lock is not in use, `[[readyPromise]]` is exposed via `ready` getter. In the current design, `read()`, etc. works on `[[readyPromise]]` even after a lock is created.

In the alternative approach,
- we stop accessing `[[readyPromise]]` once a lock is created. If the stream was `"waiting"` before locking, it stays to be `"waiting"`, and the promise obtained via `readableStream.ready` before locking stays to be pending.
- we create a new promise and expose it on the reader which represents current status of the stream
- once the stream is unlocked, `read()`, etc. again operate on `[[readyPromise]]`. If the stream was closed, errored, or became readable, that will be applied to `[[readyPromise]]` on unlocking.

To make this work, we need to introduce a new state in addition to current locked/unlocked states. Currently, the stream is unlocked by the reader on each operation. For the stream, it's indistinguishable whether it's unlocked temporarily for reader to run some operation, or it's unlocked as there's no reader associated with the stream. So, `readableStream.read()`, etc. cannot switch between the two target internal slot to hold a promise. We need to make it distinguishable.

There's no need to introduce state variables to represent the states. We should instead make `readableStream.getReader()` and `reader.releaseLock()` do something special.

This may conflict with some of the design philosophies listed in the Locking... md file. We'll investigate feasibility of this design tomorrow.

**Comment by domenic** [comment]
I am working on this + #260 in the reader-fixups branch. I was able to solve the waiting → waiting transition from https://github.com/whatwg/streams/issues/258#issuecomment-68828539 easily but the one from the OP is not as easy.

I'm interested in if you can make the alternative approach work somehow. Would appreciate hearing how you guys are doing on that. The design principle to keep in mind from the design doc is:

> Subclasses of ReadableStream should get locking support "for free." The same mechanisms for acquiring and using a lock should work flawlessly. More interestingly, if they wanted to support modifying the behavior of e.g. read() (or state or ready or closed), they should only have to override it in one location.

> Which location is more friendly? Probably in ReadableStream, so that ExclusiveStreamReader still works for ReadableStream subclasses. Less work.

(We have given up on "level 3" support, i.e. custom readable stream implementations. That seems fine. But subclassing is still important.)

**Comment by domenic** [comment]
OK. I thought about this for about an hour. I don't think there's a fix possible given the current design.

Our requirements are contradictory:

- `rs.ready` needs to fulfill when the stream transitions away from `"waiting"`,
- AND it must not fulfill when there is a reader present,
- EXCEPT if the promise was originally retrieved by the reader itself as part of [the reader's `ready` getter](https://github.com/whatwg/streams/blob/25a514128c35f362f0978576eeac006e90107af8/reference-implementation/lib/exclusive-stream-reader.js#L27-L32).

There's no real workaround here, without somehow telling the stream "I am the reader, give me a special `ready`."

One design that comes to mind is then to pass in a `getReady` function to the ExclusiveStreamReader constructor. (I think this was @yutakahirano's original design.) We might as well expand this to `getState` and `read` functions, which helps avoid the try/finally lock/unlock stuff for those.

Alternately, we are already coupling to the presence of the [[reader]] slot. We could just couple to the presence of the [[readyPromise]] and [[state]] slots. (And just abstract ReadFromReadableStream into an abstract op that we call directly.) Subclasses of ReadableStream inherit those too, so things will work. Except...

This latter design means that if you override `read()`/`state`/`ready` in your subclass, those will *not* be called by the reader. But, the more I think about this (that is why I took an hour), the more I am OK with that. Overriding those is very brittle. The only legitimate overrides I can imagine are "instrumentation"-like ones, that observe the data passing through. (E.g., overriding `read()` to fire a `"data"` event on the stream every time it is read, somewhat like in Node.js streams.) And for those, it's actually preferred that the exclusive reader not trigger the instrumentation hooks---non-observability is kind of the whole point!

So, I'm going to try ripping stuff out and more tightly coupling ExclusiveStreamReader to ReadableStream (and ReadableByteStream, and anything else that implements those specific slots).

**Comment by domenic** [comment]
One thing I forgot to mention is that if people want to override read()/state/ready and still have a reader that consults those, they can always override getReader() to return a custom reader.

---

The reader-fixups branch contains these changes. I also made separate readers for ReadableStream and ReadableByteStream. This allows them to be monomorphic, and it aligns with our story of how authors would create custom stream types---they wouldn't get to re-use ExclusiveStreamReader.
