### ISSUE TITLE
Uses of "upon fulfillment/rejection" contain unused returns and throws

### ISSUE THREAD

**Issue by jyasskin** [whatwg/streams#284]
Several algorithms in the Steams spec use the [Upon fulfillment](http://www.w3.org/2001/tag/doc/promises-guide#upon-fulfillment) and [Upon rejection](http://www.w3.org/2001/tag/doc/promises-guide#upon-rejection) algorithms.

Taking [WritableStreamAdvanceQueue()](https://streams.spec.whatwg.org/#writable-stream-advance-queue) as an example, the spec has:

1. ...
1. Let writeResult be ...
1. Upon fulfillment of writeResult,
  1. ...
  1. If ..., then call-with-rethrow Call(stream@[[error]], undefined, «‍syncResult.[[value]]»).
  1. Otherwise, return WritableStreamAdvanceQueue(stream).
1. Upon rejection of writeResult with reason r, call-with-rethrow Call(stream@[[error]], undefined, «‍r»).

"Upon fulfillment" is defined as calling p.then(_nested steps_), but not as doing anything with the return value of `.then()`. So any exceptions thrown or values returned by these nested steps are simply ignored, and the final "return" or "call-with-rethrow" could be removed.

**Comment by domenic** [comment]
> So any exceptions thrown or values returned by these nested steps are simply ignored, and the final "return" or "call-with-rethrow" could be removed.

They aren't necessarily ignored. Chrome for example logs any unhandled exceptions to the console.

**Comment by jyasskin** [comment]
Wow, this is all to get abrupt completions up to a JS context where Chrome can handle them, rather than to get exceptions and return values to places users can handle them?

**Comment by domenic** [comment]
Yes, in general ES-style specs do not drop completion records on the floor when they can avoid it. Exceptions and return values are signaled to users in other ways (e.g. calling `stream@[[error]]`).

**Comment by jyasskin** [comment]
Then I misunderstood the purpose here. Sorry for the noise.

**Comment by domenic** [comment]
No worries! ECMAspeak can be ... unenlightening at times :-/
