### ISSUE TITLE
Test ReadableStream does not call pull multiple times after previous pull finishes is incorrectly specified.

### ISSUE THREAD

**Issue by calvaris** [whatwg/streams#291]
You can find the test currently in readable-stream.js:304.

I think the test should not have the timeout in line 334 because according to the spec, after reading we pull asynchronously, but if we leave the timeout where it is and let it work, the pull from the second read could end up happening because it is waiting to be run.

Am I missing anything?

**Comment by domenic** [comment]
Hmm, I think you are right :-/. I wonder what went wrong in the reference implementation/spec/test; must be some subtle interaction.

However, given that #253 is pushing us toward async read anyway, I think the interaction between read and pull is going to change soon :-S. Hope to have the details for that up within a couple days...

**Comment by calvaris** [comment]
We changed the code and actually the timeout seems to be needed, so I'll close this issue.
