### ISSUE TITLE
Why is the reference implementation calling promise callbacks synchronously?

### ISSUE THREAD

**Issue by youennf** [whatwg/streams#293]
Should it not be the case that ReadableStream._resolveReadyPromise, _resolveClosedPromise and _rejectClosedPromise run the callbacks asynchronously?

This may have some impact on how/when code is actually executed.
This may be observed in some cancel tests, where ready/closed promises are vended before and after cancelling the stream.

**Comment by domenic** [comment]
The reference implementation isn't calling promise callbacks synchronously. Instead, it is resolving/rejecting the promise, which itself will schedule the callbacks asynchronously. Here is an example with just promises that may be helpful to understand:

```js
let resolve;
const promise = new Promise(r => { resolve = r; });

promise.then(v => console.log("fulfilled", v));

resolve(5);
console.log("after resolve call");
```

This will print `"after resolve call"\n"fulfilled 5"`. Even though `resolve(5)` is called "synchronously", the way promises are specified ensures that any callbacks are scheduled to run asynchronously.

Make sense?

**Comment by youennf** [comment]
Yep, that makes sense.
I should have had a second look at the test results obviously!
Thanks

2015-03-11 16:27 GMT+01:00 Domenic Denicola <notifications@github.com>:
