### ISSUE TITLE
Do writable streams need separate signals for write-success vs. write-accepted?

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#316]
Spawned from https://github.com/yutakahirano/fetch-with-streams/issues/30.

The premise of the current writable stream design is that it's important to signal two things to the producer:

1. Whether a given write succeeds or fails
2. Whether the stream's internal queue, as determined by its strategy, is getting full (backpressure).

This manifests in the current API in two corresponding ways:

1. The promise returned by a call to `write()`
2. The stream's `state` property (`"waiting"` vs. `"writable"`) and `ready` promise. (Although, this would likely be revised in light of #301.)

Many "functional" writable streams (known as "generator interfaces" in [GTOR](https://github.com/kriskowal/gtor/) or "observers" in Rx-land) only supply the latter, and do so via the promise returned from (their version of) the write method, which fulfills when the stream is ready to accept more data.

My position has always been that, as I/O streams, we need to supply both. However, in https://github.com/yutakahirano/fetch-with-streams/issues/30 it was argued that (1) is not useful for HTTP streams, since acceptance by the kernel is not actionable information. There was some subsequent discussion wondering whether this is generally true; a counterexample given was a writable stream representing a database where each write represents a commit to the database.

I'm not sure what to think yet, but want to log this issue.

**Comment by tyoshino** [comment]
Thanks for the summary. The sort of tasks for which the API with success/failure signal is useful would be one consists of a sequence of works where:
- each work is transaction-ish.
- it makes sense to buffer the works with back-pressure
    - this implies that the user want to issue multiple operations without waiting for completion of previous ones

I guess the domain of problems that satisfy both of these conditions is not so big.

Another use case for which the API is suitable is to represent RPC stub via which we issue mutually independent computation jobs to the cluster. In this case, write() calls may be fulfilled out of order, but backpressure makes sense to tell the developer if the cluster is overloaded (or load is exceeding CPU quota), and the user really want to see the result and we can return the result via the promise returned by write() call.

**Comment by domenic** [comment]
One issue I just thought of is about error signaling. The separate-signals model gives you more chances to communicate errors. E.g., if you require all data written to the stream to be validated in a certain way, and that validation is async, the separate-signals model lets you communicate that with (1). Whereas if we only gave backpressure signals via the promise, then the promise would fulfill immediately if the queue was empty, and you wouldn't be able to know that your data failed validation except by listening to `ws.closed` or similar.

**Comment by tyoshino** [comment]
Yeah. We could have the promise returned by `.write()` mean (not successful/failed of the whole operation, but) mean that half of the operation was successful/failed (e.g. it passed validation, IPC but unknown about validation, processing at the remote server). I don't think it's useless as far as it's clearly documented on the spec of that API not misleadingly.

**Comment by jkrems** [comment]
Anecdotal information in reference to the `writableStream.write(.., cb)` question on twitter: I used the callback argument before to make sure a specific write was flushed to disk before a hard-exit of the process. Example: downloading a file to disk. We had problems (IIRC) in testium where tar files were incomplete because the process doing the download quit before the write was flushed.

**Comment by domenic** [comment]
I think @kriskowal gave a decisive "yes" answer with [this tweet](https://twitter.com/kriskowal/status/587765438953590784). You need two separate signals for byte streams, at the very least:

- Backpressure
- This buffer has been consumed (e.g. "copied to the kernel buffer") so you can start reusing it.

For byte streams presumably `write()` would fulfill with (a new ArrayBuffer instance backed by) the original buffer.

More generally, it makes sense for the write() promise to be the one that signals "I am done reading from this object now, and you can modify it without fear of race conditions" even for object streams.

**Comment by meandmycode** [comment]
One query I have which is woefully uninformed so I apologize if this has been answered ad infinitum, are these write(..) promises going to cause performance issues? if I make 10k write calls with no care about a callback, will I have 10k of promises waiting to GC, and is that significant?

**Comment by tyoshino** [comment]
See also #323 where we discuss "reuse of buffers" regarding identity transform

**Comment by tyoshino** [comment]
We're doing some performance analysis for readable at #320. We should also discuss how much the impact is for writable case as meandmycode suggests.

**Comment by tyoshino** [comment]
Regarding memory pressure, we should be aware of https://github.com/domenic/streams-demo/issues/4

**Comment by domenic** [comment]
Closing per https://github.com/whatwg/streams/issues/316#issuecomment-92541923

Also per #318 the backpressure signal will become more precise (a size instead of just a boolean) so trying to fit all its info into a promise is not workable anyway.
