### ISSUE TITLE
Should ReadableStreamController be visible?

### ISSUE THREAD

**Issue by youennf** [whatwg/streams#322]
From my reading of the spec, it seems that ReadableStream, ReadableStreamReader and ReadableStreamController should all be visible from ECMAScript.
It makes sense for ReadableStream.
It makes somehow sense for ReadableStreamReader.
It does not seem necessary for ReadableStreamController.
Is there a need for that?

**Comment by domenic** [comment]
What do you mean, "visible"? What sections of the spec are you reading?

**Comment by youennf** [comment]
One can check the prototype of ReadableStream/ReadableStreamReader objects, test whether an object is an instance of ReadableStream/ReadableStreamReader.
All three RS classes in the spec are defined the same, so it seems they should be treated consistently.
But the controller could just be implemented as an object with three instance properties.

**Comment by domenic** [comment]
I still don't understand. Can you give some example code you would use?

> But the controller could just be implemented as an object with three instance properties.

No, then you would create three new function objects every time you create a controller, which is very wasteful.

**Comment by youennf** [comment]
In JS, one can do things like: if (rs instanceof ReadableStream), new
ReadableStreamReader(...), ReadableStream.prototype...
Do we also want that for ReadableStreamController?
For instance, what is the point of allowing to do "new
ReadableStreamController()" if it always throws a TypeError.


2015-04-08 21:55 GMT+02:00 Domenic Denicola <notifications@github.com>:

**Comment by tyoshino** [comment]
Maybe your concern can be addressed in Chrome by specifying [NoInterfaceObject] to the IDLs of `ReadableStreamReader` and `ReadableStreamController`. http://heycam.github.io/webidl/#NoInterfaceObject. Then, they are not exposed on window, though they're still obtainable via `controller.__proto__`.

**Comment by youennf** [comment]
After a quick look, that seems to help for the controller case.
I am not sure this is applicable to ReadableStreamReader, which has a
usable constructor.
I guess the spec could say a word about this or am I missing something?

2015-04-09 14:50 GMT+02:00 Takeshi Yoshino <notifications@github.com>:

**Comment by domenic** [comment]
Are you aware of https://streams.spec.whatwg.org/#globals ?

**Comment by youennf** [comment]
Ah I was missing that piece, thanks a lot!


2015-04-09 15:50 GMT+02:00 Domenic Denicola <notifications@github.com>:

**Comment by tyoshino** [comment]
Ah. Sorry, then Chrome is incorrect. @yutakahirano

**Comment by domenic** [comment]
@tyoshino I think we decided not to expose `ReadableStream` for now given the ReadableStream vs. ReadableByteStream issue and the fact that ReadableStream isn't constructible yet anyway. So I think Chrome is fine.

**Comment by tyoshino** [comment]
Discussed off-thread.

See https://code.google.com/p/chromium/issues/detail?id=474851
