### ISSUE TITLE
readBatch(), readAllAvailable() or getSyncReader()

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#327]
Sub issue for #320.

It's still under discussion whether we should take care of the promises overhead. It's discussed at #320. This sub issue makes sense only if the conclusion for the issue turns out to be that we need sync mode.

As @wanderview analyzed in https://github.com/whatwg/streams/issues/320#issuecomment-91692373, there should not any big performance difference between them.

But as I questioned in https://github.com/whatwg/streams/issues/320#issuecomment-91606599, `readBatch()` and `getSyncReader()` have different power for recognition of the consumer's signal. This comment by me elaborates the first bullet point in the comment by Ben.

Domenic +1-ed readAllAvailable() at https://github.com/whatwg/streams/issues/320#issuecomment-91608679 to avoid confusion.

So, currently I see 3 approaches:

1. provide `readAllAvailable()` on async reader
1. provide `readBatch(N)` on async reader
1. add `getSyncReader()`

**Comment by domenic** [comment]
Resolved in #320.
