### ISSUE TITLE
TransformStream: transform() is never invoked via pull()

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#330]
When `write()` of the underlying sink of `writable` is called, `maybeDoTransform()` always proceeds to run `transform`. It never stop with `writeChunk` pending but `transform` not started. Maybe what we want to do is not to start `transform` while there's back-pressure on `readable`.

**Comment by tyoshino** [comment]
As `TransformStream` doesn't know how `transform()` increase/decrease the "size" of the chunks, we may need to ask `transform()` to interpret back-pressure signal via `enqueueInReadable` and tell `TransformStream` whether `transform()` want to exert back-pressure or not, based on the signal and its own status.

Since underlying sink `write()` method takes only one signal, i.e. fulfillment of the promise returned, we cannot exert back-pressure and success/fail of the transform separately. If we want to exert back-pressure, we need to delay fulfillment of `p`, which also means delay on delivery of success/fail.

**Comment by domenic** [comment]
> TransformStream: transform() is never invoked via pull()

Unclear how to relate the issue title to the text...

> Maybe what we want to do is not to start transform while there's back-pressure on readable.

Yes, this seems like a clear win.

> Since underlying sink write() method takes only one signal, i.e. fulfillment of the promise returned, we cannot exert back-pressure and success/fail of the transform separately.

I don't quite follow the reasoning here. If we want to exert back-pressure we can change `transform.writable.state`. If we want to signal success/failure of the transform, we use the return value of `transform.writable.write()`. What am I missing? Code might help :)

**Comment by tyoshino** [comment]
> > TransformStream: transform() is never invoked via pull()

> Unclear how to relate the issue title to the text...

Sorry. I meant that the code path from `pull()` to `maybeDoTransform()` can be removed. If we do

>  Maybe what we want to do is not to start transform while there's back-pressure on readable.

Then, the code path can run `transform()`, but without such a change, there's no chance to invoke `transform()` from that path.

**Comment by tyoshino** [comment]
> I don't quite follow the reasoning here. If we want to exert back-pressure we can change transform.writable.state. If we want to signal success/failure of the transform, we use the return value of transform.writable.write(). What am I missing? Code might help :)

Ah, I was talking a subtle thing about the interface between the sink and the WritableStream. `underlyingSink.write()` is invoked by `WritableStreamAdvanceQueue`. Once `underlyinSink.write()` fulfills, it continues to advance more (step "g"). So, `underlyingSink.write()` alone cannot exert back-pressure without delaying fulfillment of ws.write().
