### ISSUE TITLE
TransformStream: There's no means available to fail transform() asynchronously

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#331]
An exception thrown by `transform()` is caught to error both `readable` and `writable`. But if `transform()` wants to do something asynchronous that may fail, we cannot tell the TransformStream the failure. `transformDone` just tells it to retrieve the next chunk.

**Comment by tyoshino** [comment]
Related: #185

**Comment by domenic** [comment]
Yeah I think fixing #185 is the right fix for this.
