### ISSUE TITLE
listen()

### ISSUE THREAD

**Issue by millermedeiros** [whatwg/streams#341]
calling `read()` multiple times gives more control but it's kinda hard to consume when you really don't need to handle backpressure (eg. I just want to `console.log` data as it comes)

```js
var reader = stream.getReader();
reader.listen(logData);
// also need a way to stop listening for data
reader.unlisten(logData);
```

I know it goes against the promise-based API but it's much simpler to use for simple cases. Right now you would need to do:

```js
function listen(readableStream, cb) {
  const reader = readableStream.getReader();

  return pump();

  function pump() {
    return reader.read().then(({ value, done })=> {
      if (done) {
        return;
      }

      cb(value);
      return pump();
    });
  }
}
```

Maybe the `listen()` method would only be available on a special kind of reader (`getEventReader()`?)

PS: this is exactly the same boilerplate as the [`getReader()` example](https://streams.spec.whatwg.org/#rs-get-reader), maybe it's really the time to abstract this logic.

PPS: `listen()` was inspired by [dart:async:Stream](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:async.Stream#id_listen)

**Comment by domenic** [comment]
If you don't care about backpressure, then streams are not great for your use case. You can adapt them into something more like observables/signals (what Dart calls "streams"), or you can create utility libraries that let you treat them that way like you've done, but that's not really a programming style we want to encourage.

**Comment by millermedeiros** [comment]
@domenic on my current use case (2-way communication between worker/window) I need the basic features of the Readable/Writable streams (`cancel`, `abort`, `write`, `close`, `closed`), but it's really closer to an *observable* since I expect the window to be able to handle all the data that is sent by the worker without needing to *pull* it (I expect the consumer to buffer/queue it by themselves if needed). I'm using the streams spec as a reference for my API/features but I ended up adding the `listen()` method to the *readable stream* itself just to keep things simple. We currently don't need the sink/pipe/buffering/pull logic.

I'm trying to avoid the need for *yet-another-helper-lib* (eg. `jQuery` for Streams), but I totally understand if that is not a *"programming style we want to encourage"*.

**Comment by domenic** [comment]
I guess I am confused why you are trying to use streams or a stream-like API if observables are a better fit for your use case.

**Comment by wanderview** [comment]
I think you can integrate with functions like `logData()` pretty easily with the current spec:

```
stream.getReader().pipeTo(new WritableStream({ write: logData }));
```

**Comment by wanderview** [comment]
Sorry, that should be even shorter:

```
stream.pipeTo(new WritableStream({ write: logData }));
```

**Comment by domenic** [comment]
Right, and importantly with that version you get backpressure.

**Comment by millermedeiros** [comment]
@domenic just because I need to `cancel` the action and the current streams spec was almost what we need. I didn't want to implement all the features tho, since we have constraints about file size and complexity; maybe when streams are available natively on modern browsers I can drop my *half-assed* implementation and just document how to use the `pipeTo`.

@wanderview you just convinced me that the `listen()` is not required. `pipeTo` is way more flexible and avoids all sorts of issues.

**Comment by domenic** [comment]
:) yay! Wish I'd thought of @wanderview's answer first.
