### ISSUE TITLE
Difference in the specification between notes, pseudocode and example code

### ISSUE THREAD

**Issue by edhager** [whatwg/streams#344]
Are you interested in comments related to inconsistencies in the specification?  I have a couple examples:

**3.2.4.2. getReader()**

The notes say that getReader locks the stream and addition readers cannot be acquired.  The pseudocode and the reference implementation do not enforce this.  Also the specification does not indicate how getReader should respond when the stream is locked.

**3.5.5. EnqueueInReadableStream ( stream, chunk )**

Line 7 in the pseudocode indicates that undefined should be returned and this is reflected in the reference implementation but the example in "9.2. A readable stream with an underlying push source and backpressure support" shows that enqueue needs to return an indication of backpressure.

**Comment by domenic** [comment]
> The pseudocode and the reference implementation do not enforce this.

Can you write a test showing otherwise? The pseudocode and reference implementation do enforce this from what I can see.

> but the example in "9.2. A readable stream with an underlying push source and backpressure support" shows that enqueue needs to return an indication of backpressure.

Excellent catch, thank you; this was left out when merging #317.

**Comment by edhager** [comment]
Ok, I was looking at the pseudo code for getReader() is:

1. If IsReadableStream(this) is false, throw a TypeError exception.
1. Return AcquireReadableStreamReader(this).

which does not do any locking tests.  I see the test now in the ReadableStreamReader constructor.

**Comment by edhager** [comment]
Thanks for the quick fix!

**Comment by domenic** [comment]
Thanks for finding it!
