### ISSUE TITLE
Canceling tee'ed streams does not cancel original stream

### ISSUE THREAD

**Issue by edhager** [whatwg/streams#347]
The reader that is acquired from the original stream in the tee() method is never released:  https://streams.spec.whatwg.org/#tee-readable-stream, step 3.

I don't think this code is running in your tests: https://github.com/whatwg/streams/blob/master/reference-implementation/test/readable-stream-tee.js#L147-L148.  I think the promise returned from canceling your tee'ed steams is being rejected because the call to cancel() on the original steam is rejecting due to the fact that the stream is still locked.

In the reference implementation, I think the code here https://github.com/whatwg/streams/blob/master/reference-implementation/lib/readable-stream.js#L693-L695 and here https://github.com/whatwg/streams/blob/master/reference-implementation/lib/readable-stream.js#L709-L711 needs to release the reader before calling CancelReadableStream.

**Comment by domenic** [comment]
Will look at this more later but note that CancelReadableStream can be called even on locked streams.

**Comment by edhager** [comment]
Ah yes.  I was equating cancel() with CancelReadableStream.

**Comment by edhager** [comment]
I guess i have a hard time leaving the stream with a reader attached after tee'ing and canceling.

**Comment by domenic** [comment]
Is there any observable difference?

**Comment by domenic** [comment]
Also FinishClosingReadableStream will release the reader.

**Comment by edhager** [comment]
Yes, you are correct.  I think that will work.  I wanted to combine close and CancelReadableStream but it looks like I need them to be separate for tee.  Thanks for your help.

**Comment by domenic** [comment]
Cool. For the future, a failing test is always appreciated :).
