### ISSUE TITLE
Add SNAPSHOT-LINK argument to the bikeshed command line in README.md

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#348]
The following example in README.md fails due to failure in processing SNAPSHOT-LINK on my environment:

> curl https://api.csswg.org/bikeshed/ -F file=@index.bs > index.tmp.html

Adding e.g. `-F md-Text-Macro="SNAPSHOT-LINK a"` makes it go. Can we include a fake SNAPSHOT-LINK argument like this in the instruction, or add a mode to run bikeshed without providing this?

**Comment by domenic** [comment]
Yeah, definitely. A dummy seems OK, unless @tabatkins knows a better way to do dummy text macros.

**Comment by domenic** [comment]
These days I'm pretty happy with `npm run local-watch` though, FWIW.

**Comment by tyoshino** [comment]
I see. Once one install bikeshed to their machine, local-watch should be the best.

**Comment by tabatkins** [comment]
This isn't a Bikeshed thing; Domenic just uses a custom text macro, and without the command for it, Bikeshed correctly throws an error about an unknown text macro.

Hmm. I guess I don't have a way to actually produce an empty text macro with that command.  I suppose you can just do something like `"SNAPSHOT-LINK &zwnj;"` to get a nearly-empty value. ^_^
