### ISSUE TITLE
ReadableByteStream underlying source/controller design: return a promise vs. c.something

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#354]
The current draft has underlying byte sources defined like

```js
new ReadableByteStream({
  pull(c) {
    c.resolve(aChunk);
  }
});
```

Assuming we don't add the ability to enqueue multiple chunks, it would be better to return a promise for a chunk, since then it would fit better with other promise-using APIs. However, in Tokyo in person @tyoshino and I discussed this and we found a case where that does not work well. We need to remember and write down what that case was.

Assuming we keep the `c.resolve(aChunk)` design, `resolve` is not the best name, as promises are more an implementation detail; the developer should be thinking about streams and reads and pulls instead. Looking through a thesaurus, here are some options: answer, conclude, fill, finish, satisfy, produce, complete, finalize, respond.

**Comment by tyoshino** [comment]
```
const underlyingByteSource = {
  pull() {
    c.close();  // When this should be issued???
    return Promise.resolve('foo');
  },
  cancel() {
  }
}
```

If `close()` is a separate method, we need to issue it after the last chunk is handled by the stream. We can wait for another `pull()` and `close()` in it, but it means we require one more microtask delay and bother the user by asking one-action-per-one-pull.

```
const underlyingByteSource = {
  pull() {
    return Promise.resolve({value: 'foo', done: true});
  },
  cancel(reason) {
  }
}
```

We can choose to fulfill the promise with a tuple containing a "done" signal.

Suppose there's a microtask (call this task-A) that runs `reader.cancel()` already queued in the task queue when the current task that is now calling `reader.read()` and resulted in `underlyingByteSource.pull()` call.

Even if the `pull()` returns a resolve promise immediately, the function to handle the fulfillment value of the promise (cast if necessary) returned by `pull()` is run after the task-A is run. Then, the underlying byte source receives `cancel()` call though it already told the stream that it's "done".

We kinda said it's okay for this issue and adopted promise based result returning for WritableStreamAdvanceQueue (here, the race with "abort" was the problem).

**Comment by domenic** [comment]
Thanks, that's exactly the kind of explanation that helps :). I am find with `c.respond` now that we have this documented. I'll close the issue but now it's searchable and linkable in case we forget again.
