### ISSUE TITLE
ReadableByteStream needs reference implementation/tests

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#355]
Can't really count on these APIs being ready until we've validated them :)

- [x] Add RBS and basic tests for it: #361
- [ ] Add RBS to the templated tests
- [ ] Sync spec and reference implementation

**Comment by tyoshino** [comment]
This is happening at https://github.com/whatwg/streams/tree/bytestream

**Comment by tyoshino** [comment]
Domenic created a PR https://github.com/whatwg/streams/pull/361

**Comment by tyoshino** [comment]
Added TODO list to OP

**Comment by tyoshino** [comment]
Now #361 is done. Updated the OP by adding it.

**Comment by tyoshino** [comment]
Merged the tasks into https://github.com/whatwg/streams/issues/300. Let's close this.
