### ISSUE TITLE
Never-released lock / getReader({unreleasable: true})

### ISSUE THREAD

**Issue by yutakahirano** [whatwg/streams#358]
Is it worth introducing lock that will never be released, even when closed or errored? As an implementer, I think it is useful.

Let `rs1` be a ReadableByteStream, `{ws2, rs2}` be an identity transform stream and `ws3` be a WritableStream.
When we call `rs1.pipeTo(ws2)` and `rs2.pipeTo(ws3)`, we effectively transfer data from (the source of) `rs1` to (the sink of) `ws3`. We would like to optimize the data transfer by transferring data directly from the source of `rs1` to the sink of `ws3`, but we need to report the end-of-transfer to `{ws2, rs2}`. If we can state that the lock gotten by `pipeTo` will never be released, we can omit the report and that simplifies the implementation (For example in a case where these streams live in different threads / processes each other).

**Comment by domenic** [comment]
Hmm. I would rather not have lock variants, where sometimes locks are auto-unlocking on closed/errored and sometimes they stay locked forever. I think it would be OK to have *all* locks stay locked after error/closed as discussed in yutakahirano/fetch-with-streams#37, but having a special for-implementer-convenience type of lock is not good.

I will explore a more detailed proposal in the other thread...

**Comment by yutakahirano** [comment]
> I would rather not have lock variants, where sometimes locks are auto-unlocking on closed/errored and sometimes they stay locked forever. I think it would be OK to have _all_ locks stay locked after error/closed

I see, but introducing _unreleasable lock_ has a problem that we easily lose the ability to access state / error by accident. I now think https://github.com/yutakahirano/fetch-with-streams/issues/37#issuecomment-108151055 is good for general stream even if it is not used to support `bodyUsed`.

**Comment by tyoshino** [comment]
We need to think of possible introduction of partial piping in the future. E.g.:

```
rs1.pipeBytesTo(ws2, 1024);
rs2.pipeTo(ws3);
```

rs1 contains multiple serialized request body data. Now we've read the header and got that the next 1024 bytes are the body to send, and the rest are the other bodies and their headers.

We want to pipe only 1024 bytes to ws2. ws3 represents the fetch() and data should be fully drained from rs2 into ws3.

**Comment by domenic** [comment]
> rs1.pipeBytesTo(ws2, 1024);

Interesting. This covers some of the use cases for https://github.com/whatwg/streams/issues/295#issuecomment-108980522 option (2). Pretty cool.

Since pipeBytesTo would of course need to release its lock, I think that means the implementation of that at least would need to report back even in a pipeline situation.

**Comment by tyoshino** [comment]
Yes!

**Comment by domenic** [comment]
Should we close this? Since it seems like the implementation will need to report back anyway...

**Comment by yutakahirano** [comment]
Sure, thanks.
