### ISSUE TITLE
Add ReadableByteStream observing API

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#362]
I and @yutakahirano discussed alternatives to the wrapper solution.

The wrapper solution requires composition/subclassing. We could instead introduce some interface to the ReadableByteStream.

##### API and algorithm

```
class ReadableByteStream {
...
  registerObserver(observer);
  unregisterObserver(id);
...
}
```

```
class ReadableByteStreamObserver {
  report();
}
```

- Both `registerObserver()` and `unregisterObserver()` can be called only when the `ReadableByteStream` is not locked.
- Every time when a `ReadableByteStream` is unlocked, the `ReadableByteStream` calls `observer.report()` with `{bytesRead: <the number of bytes read during the lock>}`.
    - `reader.read()` and `byobReader.read(view)` automatically accumulates the number of bytes read into the `ReadableByteStream` so that it can be reported to the observer on unlocking
    - The default `pipeTo()` and any optimized `pipeTo()` would also reports the number of bytes read before unlocking the `ReadableByteStream`.
- `unregisterObserver(id)` takes the object returned by `registerObserver()` to unregister the observer.

##### `Request` object implementation

NOTE: `unregisterObserver()` is not used for implementing the Fetch API. Just for APIs to be proposed in the future.

Algorithm:

- on construction,
    - create an object to receive `.report()` call
    - call `registerObserver()`passing the object to get the ID object
- when `.report()` is called,
    - remember (accumulate) the number of bytes read
- when `cache.put()` is called,
    - [Plan A] fail if the number of bytes read is positive
    - [Plan B] fail if at least one `.report()` call was made

##### API and algorithm

```
class ReadableByteStream {
...
  registerObserver();
  unregisterObserver(id);
...
}
```

- `stream.registerObserver()` returns an object which the stream updates on every unlock.

##### `Request` object implementation

- call `registerObserver()` to get the report object
- on `cache.put()` call, check the report object to see if any bytes have been read out

### Advantage to the wrapper solution

- In terms of knowing that at least one getReader() call happened, this observer solution doesn't have so much advantage to the wrapper solution.
- But this observer solution enables observing the number of bytes by requiring ReadableByteStream implementors to report some data specified in the spec e.g. the number of bytes. This is hard to realize by the wrapper solution. Especially regarding optimized one.

### Alternative: Using generic Event mechanism

Instead of introducing a dedicated mechanism, use `addEventListener`/`removeEventListener` given that if one doesn't know the function object, it cannot unregister the event listener

### Requirements analysis

Both approach A and B satisfie (1)-(4) of https://github.com/yutakahirano/fetch-with-streams/issues/37#issuecomment-107836439 but not (5) (7). I'd say (6) is also satisfied as there's such path-dependent data exists only when some observers are registered and is placed outside the stream object.

Re (4), custom `ReadableByteStream` is expected to implement these (`registerObserver` and `unregisterObserver()`) methods correctly. Whether (1) is satisfied or not depends on if they're implemented correctly or not.

**Comment by tyoshino** [comment]
One more question. What if a ReadableStream (not ReadableByteStream) is passed to the Request constructor?

Should we also introduce an observing API but without bytesRead item?

**Comment by domenic** [comment]
Sorry that I haven't had much time to look at streams today. But hopefully these few comments will be useful before I can spend tomorrow on them in more depth.

I don't quite understand the advantage of these types of solutions over e.g. adding `bytesRead` to the reader? (Or adding `bytesRead` to the stream and having it be `null` or not updating it while the stream is locked, maybe. There are variations.)

I realize that an observer-type solution would tell you when `bytesRead` updates. But that's not actually important for any of our use cases now, right?

> One more question. What if a ReadableStream (not ReadableByteStream) is passed to the Request constructor?

I think in this case we need to pipe the stream to some kind of identity transform stream that also validates that the chunks are Uint8Arrays (or maybe transfers other types into new Uint8Arrays?). It is not an easy case.

**Comment by tyoshino** [comment]
@domenic 

> I don't quite understand the advantage of these types of solutions over e.g. adding bytesRead to the reader?

The main motivation of this proposal is to satisfy (2) of https://github.com/yutakahirano/fetch-with-streams/issues/37#issuecomment-107836439 as well as the other important requirements and @wanderview's requirement (no one should be able to clear the "used signal") that he showed in his comment https://github.com/yutakahirano/fetch-with-streams/issues/37#issuecomment-110109499 of objection to @yutakahirano's solution.

**Comment by tyoshino** [comment]
> I realize that an observer-type solution would tell you when bytesRead updates. But that's not actually important for any of our use cases now, right?

The approach B in OP doesn't tell you the timing.

**Comment by tyoshino** [comment]
> I think in this case we need to pipe the stream to some kind of identity transform stream that also validates that the chunks are Uint8Arrays (or maybe transfers other types into new Uint8Arrays?). It is not an easy case.

Branched to https://github.com/yutakahirano/fetch-with-streams/issues/44

**Comment by domenic** [comment]
> The main motivation of this proposal is...

OK. I still don't understand the advantage over bytesRead on the reader.

**Comment by tyoshino** [comment]
My understanding is that `reader.bytesRead` tells us the number of bytes read from the stream for whole lifetime of the stream. So, it doesn't satisfy (2) of https://github.com/yutakahirano/fetch-with-streams/issues/37#issuecomment-107836439. I'm misunderstanding your proposal? If we make it able to reset the `bytesRead` data, then, we cannot satisfy wanderview's point.

**Comment by domenic** [comment]
I think you can still satisfy (2). Request/Response stores the bytesRead value at construction time, and later in fetch/cache.put/etc., if the value has changed, you throw.

**Comment by tyoshino** [comment]
Oh, sorry. Yeah, we just need to get diff.
