### ISSUE TITLE
Consider moving stuff into ReadableStreamController

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#364]
See https://github.com/whatwg/streams/pull/361#discussion_r32265033 where @tyoshino does this for ReadableByteStream and it seems to work out well.

**Comment by domenic** [comment]
I started working on this in the [refactor innards branch](https://github.com/whatwg/streams/tree/refactor-innards). However, I got stuck, as there were a few state variables that I wasn't sure where they should go (reader, controller, or stream):

- disturbed is a property of the stream but is modified by stream.cancel(), reader.cancel(), and reader.read()
- state is used for some checks inside the stream, and it seems good to enforce those checks no matter what the controller implementation is. But it is mostly modified and consulted by the controller, sometimes by the reader too.
- storedError is similar to state.

In the end these are not insurmountable problems. We would just need to define some kind of contract for all of the shared properties, e.g. "ReadableStreamController can be implemented in any way as long as it has state and storedError slots" or "ReadableStreamController can have a pointer back to its owner readable stream in order to modify its state and storedError slots." But it was not as straightforward as I'd hoped so I'm probably going to set this aside for a bit longer.

**Comment by tyoshino** [comment]
I was taking some of the abstract operations as representation of the contracts. For example, [[state]] is altered only via ErrorReadableStream and FinishClosingReadableStream. These operations would form an internal interface.

[[disturbed]] should stay in ReadableStream, I agree.

Ah, I didn't mean moving such a lot from Stream to Controller. I thought queuing details would fit int Controller and moved them. state, etc. should fit in Stream, I think.

**Comment by tyoshino** [comment]
I'll take over https://github.com/whatwg/streams/tree/refactor-innards to do what we know we can for now.

**Comment by tyoshino** [comment]
Created: https://github.com/whatwg/streams/pull/418

**Comment by tyoshino** [comment]
https://github.com/whatwg/streams/issues/379 is updated to point #418. Closing this issue as it has taken over this.
