### ISSUE TITLE
Add .bytesRead to ReadableByteStream.*Reader

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#367]
Putting together @domenic's `reader.bytesRead` idea to address https://github.com/yutakahirano/fetch-with-streams/issues/37:
- Fail `cache.put()` when the stream has been partially/fully drained https://github.com/yutakahirano/fetch-with-streams/issues/37#issuecomment-110109499
- Content-Length https://github.com/yutakahirano/fetch-with-streams/issues/37#issuecomment-110945488

Request/Response constructor saves the current value of `.bytesRead` https://github.com/whatwg/streams/issues/362#issuecomment-112984341

```
const rbs = ...;  // BodyInit as-is, or created from ArrayBuffer, etc.
this._bodySize = ...;  // undefined for RBS. The length of BodyInit for the others
const reader = rbs.getReader();
this._bytesReadAtConstruction = reader.bytesRead;
reader.releaseLock();
```

`cache.put()`, etc. checks if `req._bytesReadAtConstruction` has been changed or not.

```
const reader = req.body.getReader();
if (reader.bytesRead !== this._bytesReadAtConstruction) {
  throw new TypeError();
}
// Proceed with consuming body
```

`fetch()` computes the number of bytes remaining to generate the up-to-date value to be used for the Content-Length header.

```
const reader = req.body.getReader();
if (req._bodySize !== undefined) {
  const currentSize = req._bodySize - reader.bytesRead;
  // Generate Content-Length header
}
```

**Comment by tyoshino** [comment]
This proposal satisfies (1) (detecting partial consumption), (2), (3) (visible only to one who has lock), (4) (as long as the user-authored RBS conforms to the spec) of https://github.com/yutakahirano/fetch-with-streams/issues/37#issuecomment-107836439.

Domenic said ok to give up on (6) at https://github.com/yutakahirano/fetch-with-streams/issues/37#issuecomment-110945488.

(5) and (7) are not satisfied. They can be satisfied only when a wrapper is used.

**Comment by domenic** [comment]
I'd ideally like to generalize this to ReadableStream as well, using the size() measuring functionality from the queuing strategy. In which case it needs a better name. consumedSize? consumed? readCount? readSize? offset? (I think I like offset the most.)

Also, I would really appreciate if anyone else has scenarios where this property is useful, besides HTTP streams and Content-Length. I guess in general it can be useful for progress meter type things. What else?

**Comment by tyoshino** [comment]
I'm fine with `offset`.

- The good point of `offset` and `fooCount` is that it sounds like holding an accumulated historical data.
- The bad point of `count` is that it sounds like counting objects, not the result of `size()`
- `offset` may sound like it's settable to perform seeking, but it doesn't matter much.

**Comment by annevk** [comment]
I don't see how this addresses `Content-Length` as I tried to explain in https://github.com/yutakahirano/fetch-with-streams/issues/37#issuecomment-114889440.

**Comment by tyoshino** [comment]
Like this?

Switch on BodyInit's type:
- Blob, BufferSource, FormData...: Save the original length as `originalLength`. When passed to `fetch()`, calculate `currentLength` by `originalLength - rbs.offset` and generate `Content-Length` header using `currentLength`.
- RBS obtained from onfetch event w/ original length info: Same as above
- RBS obtained from onfetch event w/o original length info: The final length is unknown. Just use the chunked transfer encoding or send the `Content-Length` header using a user provided value (though it's still under discussion https://lists.w3.org/Archives/Public/public-webapps/2014OctDec/0422.html)
- User authored RBS: Same as above

**Comment by tyoshino** [comment]
Oh, wait... We're likely to just prohibit `fetch(req2)` in https://github.com/yutakahirano/fetch-with-streams/issues/37#issuecomment-110592585?

**Comment by annevk** [comment]
So yeah, it depends on whether we prohibit a partially read `Response`/`Request` from being transmitted. It does not make much sense to me to transmit them in part. A `Response`/`Request` is a body + metadata. It's not a partial body + metadata. Is there any precedent for this? (Other than HTTP range, but that does not seem to be what this is about.)

**Comment by domenic** [comment]
I think it is a matter of convenience. E.g. it could be convenient, if we allow it, to request a body from one URL, read off the first 200 bytes (the "header" portion), then upload the rest elsewhere. If we disallow such things, then it becomes more manual work for authors, and possibly more memcpys. (Especially since we backed away from writable streams for uploads.)

**Comment by annevk** [comment]
That can cause attacks too though. E.g. tricking the server into cutting off some set of bytes that contain an important script. Per https://github.com/whatwg/fetch/issues/61#issuecomment-115376269 I think we want `offset`, but I'm not sure we should do this, at least not initially. Note also https://github.com/whatwg/fetch/issues/67 which this would make even worse.

**Comment by domenic** [comment]
Can you explain the attack model more? As I said, it's literally just convenience; you could replicate the same thing with more manual work.

**Comment by annevk** [comment]
Say the document's CSP allows resources from "https://example.com/test". Now the service worker modifies the resource by reading the part from it that comments out a script or some such, but we don't make it clear it's now a synthetic response (or is that the plan?). Hole.

**Comment by domenic** [comment]
Ah I see, yeah, we'd want to mark anything with a nonzero offset as a synthetic response I think.

**Comment by annevk** [comment]
That might be okay then, but it makes the synthetic response check a bit more complicated since you'll have to check the combination of the response and the stream rather than just a bit on the response. And remember to do that. Rejecting seems easier for now...

**Comment by domenic** [comment]
Let's close this as it's no longer necessary given the plan to expose IsReadableStreamDisturbed (#378).
