### ISSUE TITLE
.closed should be fulfilled/rejected after fulfillment/rejection of read()?

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#374]
My gut feeling is that pending read()s should be fulfilled/rejected first (to be precise; microtasks for fulfillment/rejection should scheduled first) in the same order in which they were called, and then .closed should be fulfilled/rejected.

Thoughts?

**Comment by domenic** [comment]
Hmm, this is a pretty minor detail, but it is something we need to decide and write tests for, I agree. I agree with you about the order.

**Comment by tyoshino** [comment]
Thanks. I'll go with that plan. This is FTR and to be used for discussion if anything new about this is found.
