### ISSUE TITLE
Add IsDisturbed predicate

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#378]
Should return true if stream is ever .cancel()ed or .read() from. See more details in https://etherpad.mozilla.org/streams-f2f-july

**Comment by tyoshino** [comment]
Thanks for getting this discussed and summarizing it. FTR, could you please list the participants of the f2f (or put a link to some page with such a list) if no problem?

**Comment by wanderview** [comment]
I added the attendees to the etherpad.  Basically, me, @Domenic, and @annevk since we were all in town for other meetings that week.

**Comment by tyoshino** [comment]
Thanks, Ben.

Reading the note. @domenic , you objected to the always-chunked approach at https://lists.w3.org/Archives/Public/public-webapps/2014OctDec/0420.html Has it been resolved?

**Comment by domenic** [comment]
Yes. We can do chunked for now. In the future I would like to explore allowing setting content-length (and thus not auto-setting chunked) but we can leave that for another time.

**Comment by tyoshino** [comment]
Created. Sorry for OT comments.

**Comment by tyoshino** [comment]
Implemented as IsReadableStreamDisturbed() in #385.
