### ISSUE TITLE
Investigate merging RS and RBS

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#379]
The work in #361 moves a lot of the interesting work into the controller class, making the outer RBS class fairly simple. RBS becomes a shell that delegates to RBSC.

One possibility this opens up is that we could remove RBS, making RS just a shell which delegates to _either_ one of RSC or RBSC. This could have good ecosystem benefits by not splitting the ecosystem into two different types of streams.

To do this I think we need to:

- [x] Finish up #361.
- [x] Port RS to a similar infrastructure.
  - [x] #373
  - [x] #418 (taken over #364)
- [x] See if merging is possible and desirable.
- [x] Naming concern: https://github.com/whatwg/streams/issues/405

Related: #312.

**Comment by tyoshino** [comment]
Added #373. More work can be made after it.

**Comment by tyoshino** [comment]
Added #364, too. #361 is now done.

**Comment by martinthomson** [comment]
Discussed at TPAC2015, the group there felt that there would need to be very good reasons if these were to remain separate.  The extension to support writing into an `ArrayBuffer` (or more generally, an `ArrayBufferView`) seems like a pure extension.

**Comment by tyoshino** [comment]
We need to decide this:

ReadableByteStream has a new pull controlling mechanism. Should we port this to ReadableStream?:
- source.pull doesn't return a promise
- repeats calling pull (see where `_pullAgain` is set to `true`) using a for-loop while necessary
- when pull is requested while running enqueue, schedule run of pull by using process.nextTick

**Comment by tyoshino** [comment]
Currently the merging work is happening at PR https://github.com/whatwg/streams/pull/418.

**Comment by domenic** [comment]
> ReadableByteStream has a new pull controlling mechanism. Should we port this to ReadableStream?:

I don't quite understand the proposal. Can you give a bit more detail? Would it be additive, or replace the existing mechanism? How does some example code differ?

**Comment by tyoshino** [comment]
Sorry for lack of words. Branched into https://github.com/whatwg/streams/issues/423 :)

**Comment by tyoshino** [comment]
There's one more thing to decide regarding return type of the controllers. See https://github.com/whatwg/streams/issues/424.

**Comment by tyoshino** [comment]
Done https://github.com/whatwg/streams/commit/e601d69f3ba40e6f4b5506e4bb1fbe3f3eabf393

**Comment by annevk** [comment]
Very exciting, congratulations on finishing this @tyoshino!
