### ISSUE TITLE
Typo in ErrorReadableStream algorithm

### ISSUE THREAD

**Issue by youennf** [whatwg/streams#387]
In the HTML draft currently available at https://streams.spec.whatwg.org/#error-readable-stream, step 6 is probably wrong. It should probably say something like: if reader is undefined, return undefined.
Step 6a could also be renumbered as step 7.

**Comment by domenic** [comment]
Thanks! I think I see the fix. But I'll let @tyoshino do it to confirm. This was introduced in the most recent commit https://github.com/whatwg/streams/commit/7b034bbf9c3a87c01349a4b806b99ff3aab8dc53

**Comment by tyoshino** [comment]
Thanks for review and catching this! Right, it's a bug. I've fixed the code as you suggested.
