### ISSUE TITLE
Consistency of return value of ReadableStreamController method call on closed/errored streams

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#388]
It's minor thing, but there's some inconsistency in the reference impl.

Currently:
- close() on a close()-ed stream: throw a TypeError saying it's already closed
- close() on an errored-before-close() stream: throw a TypeError saying it's errored
- enqueue() on an errored stream: throw a TypeError saying it's errored
- enqueue() on a close()-ed but not errored stream: throw a TypeError saying it's already closed

**Comment by domenic** [comment]
I don't actually understand the inconsistency. Is it about the presence or absence of the word "already"?

If it is just changing error message text, feel free to make the change (no PR needed).

**Comment by tyoshino** [comment]
Right, it's only about the ref impl. When one refers to it to know whether the difference of the order matters, they would notice that they have different messages and the two functions have different priorities and may have some question about that.

**Comment by tyoshino** [comment]
This has been fixed by https://github.com/whatwg/streams/commit/e601d69f3ba40e6f4b5506e4bb1fbe3f3eabf393

Now, for both ReadableStreamDefaultReader and ReadableStreamBYOBReader, close() and enqueue() has [[closeRequested]] check and [[state]] check in the same order.
