### ISSUE TITLE
Some tests behaving differently

### ISSUE THREAD

**Issue by calvaris** [whatwg/streams#390]
I have a replica of the spec tests ported to WebKit to run them against the reference implementation. I realized that after your changes, there were some issues with the moment closed is fulfilled in reference to the last read. And in some cases it seems to be inconsistent.

For example, in the RS tee tests, at "ReadableStream teeing: should be able to read one branch to the end without affecting the other" we were getting closed before the last read, which is no longer true with the reference implementation.

For the templated tests, in the case of Errored, "ReadableStream (errored via call in start)" behaves different from "ReadableStream (errored via returning a rejected promise in start)" regarding "getReader() should return a reader that acts errored".

**Comment by domenic** [comment]
Hmm. A bit more concrete would be helpful. But for example,

> For the templated tests, in the case of Errored, "ReadableStream (errored via call in start)" behaves different from "ReadableStream (errored via returning a rejected promise in start)" regarding "getReader() should return a reader that acts errored".

This seems expected. For returning a rejected promise, you need to schedule a promise fulfillment callback to error the stream. Whereas calling error() will immediately error the stream. Once the stream becomes errored, you then reject the closed promise, which includes scheduling another microtask to call any registered handlers. So you can definitely observe differences here; the rejected-promise path is "more async" than the error() path.

I wonder if it could be an issue with WebKit's promise implementation's timing? But it's kind of hard to tell without more detail... Happy to help if you can give me more to work with.

**Comment by youennf** [comment]
Isn't it just that in previous versions of the spec, read promises were fulfilled after fulfilling the close promise. The order is now thankfully reversed.
At some point, we might just need to update WebKit implementation and related tests accordingly.

**Comment by calvaris** [comment]
Yes, I'll check it today with more detail. I just wanted to be sure that this was not an unexpected side effect of the change.

**Comment by calvaris** [comment]
Everything seems to be ok, the changes in the spec motivate our problems, so I'll update our tests and implementation accordingly.
