### ISSUE TITLE
Add an example of piping to a writable stream for consuming a readable stream

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#393]
As an alternative to the read loop, you can do e.g.

```js
readableStream.pipeTo(new WritableStream({
    write(chunk) {
      console.log(value);
    },
    close() {
      console.log("--- all done");
    }
    abort(e) {
      console.log("--- error in the readable stream", e);
    }
  });
```

**Comment by wenbozhu** [comment]
Why not just make this the only way to consume a readable stream?

**Comment by domenic** [comment]
@wenbozhu in general with new web APIs we try to follow the [extensible web manifesto](https://extensiblewebmanifesto.org/). Instead of only exposing high-level features, we also expose the low-level building blocks that allow you to make higher-level features. That way if someone wants to e.g. implement their own piping algorithm, with different tradeoffs or features, they can do so on top of the primitives, instead of simply being stuck until they convince spec writers/implementers to support their use case.
