### ISSUE TITLE
Rename ReadableByteStream

### ISSUE THREAD

**Issue by annevk** [whatwg/streams#405]
As I understand it the primitive is not bytes, but the various views one can have upon an ArrayBuffer. The feedback from TPAC (by @othermaciej from Apple, if I remember correctly) was to then give it a more appropriate name. ArrayBufferStream might not be quite right either, but TypedArrayStream also seems wrong. Any ideas?

(That is, if we keep this as a distinct type. When will we decide on that?)

**Comment by wanderview** [comment]
I'd greatly prefer to see this type go away in favor of the constructor specialization.

**Comment by tyoshino** [comment]
It's likely that RS/RBS merge happens: https://github.com/whatwg/streams/issues/379

The concern may be applied if we leave some classes/methods that works only for "byte"/"ArrayBuffer" use cases.

**Comment by tyoshino** [comment]
ReadableByteStream has been merged into ReadableStream. See https://github.com/whatwg/streams/commit/e601d69f3ba40e6f4b5506e4bb1fbe3f3eabf393

Closing
