### ISSUE TITLE
Is the reference implementation usable yet ?

### ISSUE THREAD

**Issue by rom1504** [whatwg/streams#406]
Is this ready to be used https://github.com/whatwg/streams/tree/master/reference-implementation ?
If so could it be published to npm ?

**Comment by domenic** [comment]
The reference implementation is just that: a reference implementation. It's meant for use by actual real implementations which want to refer to it, and as something to develop the spec and test suite against. It's not really meant to be used in actual programs. As such I don't have any intention of publishing it to npm, and I would advise against using it for purposes other than those it was designed for.

**Comment by rom1504** [comment]
Are there any implementations yet ?

**Comment by domenic** [comment]
Chrome has a partial implementation, as does WebKit nightly. Firefox has announced an intent to implement but work hasn't quite started.

**Comment by rom1504** [comment]
I see. Nothing usable in node.js then ? (I found https://github.com/h13i32maru/eo.whatwg-streams but it seems to be just an (old) copy/paste of https://github.com/whatwg/streams/tree/master/reference-implementation )

**Comment by domenic** [comment]
I'm not aware of any, but GitHub and npm are big places.
