### ISSUE TITLE
type of Chunk.value?

### ISSUE THREAD

**Issue by bblfish** [whatwg/streams#409]
Hi,

  how is one meant to know what the value of a chunk is going to be? Does that depend on the function that returns chunks? If a chunk can return any type of object then would this not require each piece of code to write long statements of the form

```scala
if ( chunk.value.isInstanceOf[UInt8Array]) { ... }
else if ( chunk.value.isInstanceOf[js.Array]) { ... }
...
```

Thanks for your help.

**Comment by domenic** [comment]
The example code is not in JavaScript, so I can't really help you. JavaScript is not a typed language, so this question doesn't really apply. If you are trying to implement this API in some language other than JavaScript, you will need to make up your own answer to problems you have invented by using a language other than the one it was designed for.
