### ISSUE TITLE
type of Chunk.value 

### ISSUE THREAD

**Issue by bblfish** [whatwg/streams#410]
Hi,

how is one meant to know what the value of a chunk is going to be? Does that depend on the function that returns chunks? The specification says in [¶2. Model](https://streams.spec.whatwg.org/#model):

> A chunk is a single piece of data that is written to or read from a stream. It can be of any type; streams can even contain chunks of different types. A chunk will often not be the most atomic unit of data for a given stream; for example a byte stream might contain chunks consisting of 16 KiB `Uint8Arrays`, instead of single bytes.

By printing out the value I seem to have at one point found that it was an Array of bytes ( but I am no longer sure), at another time a [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array) which is a form of [TypedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/prototype). 

If one can always treat the `chunk.value` as a `Uint8Array` would it not be best to state that this is what it returns?

**Comment by domenic** [comment]
It is whatever type the creator of the stream wants it to be.

**Comment by domenic** [comment]
It can be multiple types in the same stream too. Each chunk can be different, if that is what the creator wants.

**Comment by bblfish** [comment]
Ok so that means that functions returning a Chunk should specify what the exact type of the Chunk is I suppose. I am using the Fetch API's [fetch method](https://fetch.spec.whatwg.org/#fetch-method) which [returns a Promise of a Response](https://fetch.spec.whatwg.org/#response), which contains a `body` which is a `ReadableStream`.

Presumably they should state in their documentation what the type of the chunks returned by the ReadableStream is right?

**Comment by domenic** [comment]
https://fetch.spec.whatwg.org/#dfnReturnLink-1 may help clarify.

**Comment by tyoshino** [comment]
> Hmm it looks like the Response.body method says:

https://fetch.spec.whatwg.org/#concept-body you've pointed in this sentence is not Response.body. It's a concept body associated with a concept request or a concept response.

You should look at https://fetch.spec.whatwg.org/#dom-response-body which actually specifies what Response.body is. It leads to the text @domenic just mentioned above.

(/cc @yutakahirano)

**Comment by bblfish** [comment]
Ah I see there is [a note](https://fetch.spec.whatwg.org/#concept-response-readable-stream):

> This might become a ReadableByteStream object. While the type might change, the behavior specified will be equivalent since the hypothetical ReadableByteStream object will have the same members as the ReadableStream object has today.

So I suppose that's what I was missing, as I imagine that would state that a ReadableByteStream is a streams whose chunks contain ` Uint8Array`s.

That's close to my suggestion. You'd avoid having to create new types of objects by developing a generics style notation for the documentation.

**Comment by tyoshino** [comment]
> Though you'd avoid having to create new types of objects by developing a generics style notation for the documentation.

ReadableByteStream is not just a ReadableStream with Uint8Array chunks in it. ReadableByteStream has more functionality that is not specified in ReadableStream to allow efficient handling of bytes (though we're discussing if we can merge them at https://github.com/whatwg/streams/issues/379).

**Comment by domenic** [comment]
IDL Is not for documentation (nor are specs in general, really). MDN is probably a better place for that.

**Comment by tyoshino** [comment]
Ya

**Comment by bblfish** [comment]
@tyoshino  in that case you have 

`ReadableByteStream<T> extends ByteStream<T> `

@domenic as a user I have no idea how up-to-date the MDN documentation is. I'd rather go to the specs themselves.

**Comment by domenic** [comment]
@bblfish in that case you'd better learn how to read specs, despite them not being written as documentation for users.

**Comment by bblfish** [comment]
@domenic I am doing my best, and I am sure you are too. 
Note that the people reading these specs is what allows us to find bugs in them, such as https://github.com/whatwg/fetch/issues/164 . So the easier you make it to be read by good developers, then better those specs will be.
