### ISSUE TITLE
.ready still active after drain?

### ISSUE THREAD

**Issue by bmeck** [whatwg/streams#415]
minor thought. if someone uses `.ready` and the stream drains, the old `.ready` will stay resolved. this seems a bit weird, but maybe this has been thought of before.

**Comment by domenic** [comment]
You are talking about writable streams?

They are undergoing a redesign in that regard; the current plan is in https://github.com/whatwg/streams/issues/318. Basically `stream.ready` will be replaced with `writer.waitForDesiredSize(n)`.

**Comment by bmeck** [comment]
closing, will review after redesign
