### ISSUE TITLE
Description of "pull" is misleading

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/streams#425]
> pull(controller) is called when the stream’s internal queue of chunks is depleted, and the consumer has signaled that they wish to consume more data.

Based on this, I didn't expect `pull` to be called until `reader.read()` was called.

Maybe something like:

"pull(controller) is called when the stream’s internal queue of chunks is not full, and will be called until the internal queue is full."

**Comment by tyoshino** [comment]
lgtm

**Comment by jakearchibald** [comment]
Yep, this is great
