### ISSUE TITLE
ReadableStreamCancel() should assert IsReadableStream(stream)

### ISSUE THREAD

**Issue by wanderview** [whatwg/streams#452]
Currently the `ReadableStreamCancel()` algorithm simply does:

> Assert: stream is not undefined.

Since this function accesses slots on stream I think it would be much better to do a full `IsReadableStream(stream)` assertion.

**Comment by tyoshino** [comment]
First, I'd like to move the assertion comparing stream with undefined to the caller. Basically, all the abstract methods are assuming that the arguments are not undefined (unless it's optional). I'd like to align this with the others.

https://github.com/whatwg/streams/pull/459

**Comment by domenic** [comment]
Let's fold this into https://github.com/whatwg/streams/issues/453 as a general "add lots of asserts" issue.
