### ISSUE TITLE
Consider adding type assertions for all abstract operations

### ISSUE THREAD

**Issue by wanderview** [whatwg/streams#453]
ReadableStreamClose() does not assert anything about its argument at all!  We should assert IsReadableStream() here I think.  Anything that accesses slots should assure its operating on the right object type.

**Comment by wanderview** [comment]
This applies to `ReadableStreamAddReadIntoRequest()` and `ReadableStreamReadRequest()` as well.

**Comment by wanderview** [comment]
And ReadableStreamFulfillReadIntoRequest() and ReadableStreamFulfillReadRequest() as well.  These should also assert their reader types.

**Comment by domenic** [comment]
In general I have reserved assertions for things that are complex and not obvious, but I'm sure they're used more widely as of recent patches, and I'm happy to add general type checking assertions to most or all abstract ops if you think it would help readers such as yourself.

**Comment by wanderview** [comment]
I think the issue for me is spider monkey does not treat slots safely.  They are basically just numeric constants indexing into the object internals.  So anything using slots better make sure it has the right type.

I can keep this as an impl detail, but I thought I would mention it here in case it was spec worthy.

**Comment by domenic** [comment]
Nah, it's all good. But just to be sure we're on the same page: the intent of the asserts is as documentation, with no normative behavior impact. They state invariants which are guaranteed by other normative text. In an implementation that follows the spec without bugs, they will never fire, no matter how convolutedly the web developer uses the APIs.

(I think "Assert:" should autolink the appropriate paragraph near the bottom of https://tc39.github.io/ecma262/#sec-algorithm-conventions which explains this. I will work on that.)

**Comment by wanderview** [comment]
Yea, I realize asserts don't do anything in production.  I think they are super helpful for documenting assumptions and catching inadvertent changes in debug builds, though.  I'd rather err on too many assertions instead of not enough.  That's perhaps just a style thing though.

**Comment by domenic** [comment]
So I started looking into this and it basically amounts to the following:

- Every time an abstract operation (in section 3) has an argument named "stream", add "Assert: ! IsReadableStream(_stream_) is **true**."
- Every time an abstract operation in section 3.9 has an argument named "controller", add "Assert: ! IsReadableStreamDefaultController(_controller_) is **true**."
- Every time an abstract operation in section 3.12 has an argument named "controller", add "Assert: ! IsReadableStreamBYOBController(_controller_) is **true**."
- Every time an abstract operation in section 3.7 has an argument named "reader", add one of the two asserts depending on the reader type, or assert that either type is allowed.

I'm not really convinced this is valuable. Currently I have assertions in most of the algorithms that are intended to be called from other specs, to make sure other specs are clear on the requirements they need to set up before calling into this one. But within this spec, I don't think they add any more useful documentation beyond that already present by virtue of the parameter name or abstract operation name.

What do you guys think?

**Comment by domenic** [comment]
Closing per my above comment, but happy to continue discussing and change my opinion.
