### ISSUE TITLE
should ReadableStreamClose() resolve BYOB reader readIntoRequests?

### ISSUE THREAD

**Issue by wanderview** [whatwg/streams#455]
In ReadableStreamClose() we iterate over default reader's readRequests to resolve all of their promises.  We don't, however, do this for BYOB reader readIntoRequests.  Is this intentional?

Note that we do iterate and reject BYOB reader readIntoRequests in ReadableStreamError().

**Comment by tyoshino** [comment]
This is for allowing the underlying byte source to return the buffers it borrowed even after being canceled. We're still discussing whether this is really useful or not. Your opinion is really welcome.

We had this logic also for errored state, but we've removed it.

**Comment by domenic** [comment]
@wanderview did you have an opinion on this?

**Comment by wanderview** [comment]
I'm willing to defer here.  It was just something I noticed at a local level, but not sure I fully understand the total system implication yet.
