### ISSUE TITLE
Synchronous (or asynchronous) state probing on WritableStream

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#463]
I attempted to redesign WritableStream to follow this basic design: https://github.com/whatwg/streams/issues/319#issuecomment-133150569.

WritableStream is designed to allow the underlying sink to react to the `write()` method invocation synchronously by using `error()` function (which is now converted into `WritableStreamDefaultController.error()`). So, when a producer facing the WritableStream attemps to `write()` to it repeatedly and synchronously, it cannot know synchronously what happened to the stream (by reaction by the underlying sink) between two consequent `write()` calls. Backpressure signal is synchronously available once we introduce `desiredSize` getter to WritableStreamDefaultWriter interface. But error signal is available only via write()'s result promise, closed promise and ready promise, i.e. asynchronously.

Shall we keep state()?

For ReadableStreamDefaultController interface, this was not a problem. While an underlying source is operating on the stream using the ReadableStreamDefaultController, the consumer who's facing the ReadableStream never reacts to the operation synchronously. Any accident in e.g. size() are synchronously notified of as exception thrown for enqueue(), close(), etc. That's all which may happen to the stream synchronously.

**Comment by domenic** [comment]
Interesting. What if we made `desiredSize` return `null` for errored streams? That seems more semantically correct to me, even if we do introduce `state`. (Maybe we should change that for readable stream controllers too?) I'm not sure about whether it should return `null` for closed streams, or just `0`. But I guess you can't become closed unless you called `writer.close()`, so it is less of a concern.

I'm OK with synchronously exposing `state` too. I just can't tell if if it's too much complexity, or the right amount of complexity. How do we envision people using it? Would the pipe algorithm use it? (Even though we are planning to make pipe not use the public API, it is a good indicator of what types of things are important for people operating on streams at a low level.)

**Comment by yutakahirano** [comment]
Sorry, I don't understand why you need synchronous error notification. Can you tell me?

**Comment by tyoshino** [comment]
When writing multiple chunks at once to a writable stream, we could check backpressure signal and error/close synchronously between those write() calls to avoid write()s on backpressured / errored /  closed stream. If we throw away `.state`, we cannot do that. We need to schedule a new microtask to do the next write() by then()-ing on `.ready`, `.closed` or the promise returned by the previous `.write()`.

I'm asking if this inconvenience is ok or not.

**Comment by domenic** [comment]
Right. I think both @yutakahirano and I are asking for some more concrete use cases. I phrased it as:

> How do we envision people using it? Would the pipe algorithm use it? (Even though we are planning to make pipe not use the public API, it is a good indicator of what types of things are important for people operating on streams at a low level.)

In other words, it makes sense that the current setup is an inconvenience. But is it just a theoretical inconvenience, or a practical one?

**Comment by tyoshino** [comment]
Code to put multiple elements respecting back pressure would be like:

```
const values = [ ... ];
function writeData() {
  const value = values.shift();
  writer.write(v);
  Promise.race(writer.closed, writer.ready).then(() => {
    writeData();
  }).catch(r => {
    // Failed
  });
}
```

Hmm, ok. Let's proceed with the plan to just remove state. If I see any new issue in writing pipeTo, transform stream, I'll report here.

**Comment by domenic** [comment]
@tyoshino did you see any problems with pipeTo or transform streams while working on #488?

**Comment by tyoshino** [comment]
pipeTo() never performs batch write()-ing to the destination. So, it wasn't the case where I could evaluate the benefit of synchronous probing. Sorry.

**Comment by domenic** [comment]
I guess `.desiredSize` is also a pretty good synchronous probe.
