### ISSUE TITLE
Internal promises that can be rejected need to be handled

### ISSUE THREAD

**Issue by jplaisted** [whatwg/streams#468]
Title is a general rule of thumb but there's only one violation that I've found so far, and its in the reference implementation of pipeTo. The promises returned from dest.write are not catch'd and are never exposed to any consumers for them to catch either. So if there's an error with dest and there are pending writes from a pipe there will be uncaught Javascript exceptions and nothing the consumer can reasonably do to handle them. Possible solution is to pass a blank function to a catch of write, or rethrowAssertionErrorRejection.

There's also an issue with consumers/producers having to handle the exceptions from read()/write() and also the closed promise. They must handle both even though they'll be the same error. pipeTo is an example of this where any [non-assertion] errors from read() are just swallowed because they're handled in close. I'm not sure if this can be cleaned up, I can see some consumers wanting the closed promise and others wanting the promises from read/write, but I figured I'd point out the forced redundancy anyways.

**Comment by domenic** [comment]
Yes, there's a reason the spec currently says

> The pipeTo method is still in some flux.

We would lock down all of this before actually codifying it.

**Comment by jplaisted** [comment]
Ok, that's fine and I acknowledge it. I'll refrain from opening issues about anything in flux then.

But what about the latter issue of consumers/producers needing to handle closed and read/write promises, which can be redundant since they'll all be rejected with he same error, in the event of an error? pipeTo, although in flux, is an example of this redundancy. This is an issue with ReadableStreams, which you "are happy with".

**Comment by domenic** [comment]
You should only need to handle a given error once. For example, you don't need to handle .read() or .write() errors if you handle .closed. This is a nice convenience feature. There's no forced redundancy; you just have both options.

**Comment by jplaisted** [comment]
There is forced redundancy if you don't want uncaught exceptions in your production code. I get the idea was to provide options but for clients that don't want uncaught exceptions in production code they'll have to handle both. I'd assume most people wouldn't want uncaught exceptions being logged, especially when you technically handled it, just via another code path.

There's no relation between the closed promise and the ones returned from read. Catching one does not catch the other.

**Comment by domenic** [comment]
> There is forced redundancy if you don't want uncaught exceptions in your production code.

I'm not sure exactly what you're talking about here. Promises don't cause uncaught exceptions.

Perhaps if you could give an example (testable in Chrome Canary or WebKit nightly, perhaps) of what you're referring to, it would be clearer.

> There's no relation between the closed promise and the ones returned from read.

That's incorrect; they're both rejected with the same error under the same conditions.

> Catching one does not catch the other.

That's correct.

**Comment by jplaisted** [comment]
By relation I meant the next sentence (catching one doesn't prevent the other from throwing), perhaps a semicolon would've worked better. And yes I realize they're rejected with the same error, that's why its redundant.

Reading through the ES spec I guess I realize I'm just too use to how Promises are implemented in Chrome / in Closure. It doesn't look like its part of the ES spec that unhanded errors should be logged.

You can copy the code below in Chrome and get an error on the first example. However you won't in FireFox.

`Promise.reject(lol error') // causes the error: Uncaught (in promise) lol error in Chrome`
`Promise.reject('lol error').catch(() => {}) // no error in Chrome`

Guess this can be closed since it isn't part of the ES Promise spec. If it was (which I assumed) then I would've had an argument.

**Comment by chrisdickinson** [comment]
I second that the ReadableStream spec should avoid relying on handling previously unhandled rejections, if possible. I am happy to spend some time investigating this if it's helpful!
