### ISSUE TITLE
ReadableByteStreamControllerClose accesses first element of pendingPullIntos without checking array length

### ISSUE THREAD

**Issue by wanderview** [whatwg/streams#470]
In ReadableByteStreamControllerClose step 5 and 6 are:

```
5. Let firstPendingPullInto be the first element of controller.[[pendingPullIntos]].
6. If ! ReadableStreamHasBYOBReader(stream) is true, controller.[[pendingPullIntos]]
    is not empty, and firstPendingPullInto.[[bytesFilled]] > 0.
```

It seems like step 5 could trigger a range error if pendingPullIntos is empty and has no first element.  Should we be checking the length of the List before trying to access the first element?

**Comment by tyoshino** [comment]
Thanks. You're right. It's a bug I introduced when I modified reference impl so that the corresponding spec text becomes simple.
