### ISSUE TITLE
IsFiniteNonNegativeNumber() could be used in more places

### ISSUE THREAD

**Issue by wanderview** [whatwg/streams#475]
The spec uses `IsFiniteNonNegativeNumber()` but only uses it in `ReadableByteStreamControllerRespond()`.  I think it could also be used in `EnqueueValueWithSize`, step 2.

**Comment by wanderview** [comment]
We should probably also use it in ValidateAndNormalizeHighWaterMark() as well.  That function dubiously throws TypeError for NaN and ignores the possibility of infinity.

**Comment by domenic** [comment]
So Infinity is explicitly allowed as a high water mark, so I don't think it quite works there. But standardizing on RangeErrors for NaN seems probably OK...
