### ISSUE TITLE
Stack details are omitted in output of tap-spec

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#478]
I think it's because the body of the stack item is not appended to lastAsserRawErrorString in Parser.prototype._handleError in tap-out. I don't want to lose it as it's very useful for debugging. I've been running run-tests.js directly when I want to see the info.

Should I just upstream the issue to tap-spec repo?

**Comment by domenic** [comment]
Yeah, that is probably the best thing to do.

Maybe we should just get rid of tap-spec? It makes things a bit prettier but this cost is not a good one to pay. Especially since we are moving away from tape tests over time.

**Comment by tyoshino** [comment]
https://github.com/scottcorgan/tap-out/issues/25

> Maybe we should just get rid of tap-spec? It makes things a bit prettier but this cost is not a good one to pay. Especially since we are moving away from tape tests over time.

Hmm, i'm fine with having it. Let's just start working on switching to wpt soon :)

**Comment by ricea** [comment]
Obsolete.
