### ISSUE TITLE
Use e => t.error(e) than t.error for catching exceptions in a then-callback

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#479]
In unittests, we have `.catch()` call like this to report unexpected exceptions up to the test fixture:

```
  writer.close().then(() => {
  })
  .catch(t.error);
```

This doesn't tell us whether this happened but instead shows a message like this:

```
not ok 1 aaa
  ---
    operator: fail
    at: process._tickCallback (internal/process/next_tick.js:103:7)
  ...
```

The same for `t.error.bind(t)`.

If we use `e => t.error(e)`, we see stack info:

```
not ok 1 aaa
  ---
    operator: fail
    at: writer.close.then.catch.e (/usr/local/google/home/tyoshino/whatwgstreams/reference-implementation/test/writable-stream.js:59:17)
  ...
```

**Comment by domenic** [comment]
I mean, ideally we should convert everything to web platform tests... but yeah, this is clearly better while we're still on tap.

**Comment by tyoshino** [comment]
OK. Thanks for checking.
