### ISSUE TITLE
Broadcast ReadableStream

### ISSUE THREAD

**Issue by amatiasq** [whatwg/streams#481]
I see no documentation about a kind of broadcast-focused ReadableStream. I'm thinking for example on a stream for DOM events:

    function streamFromEvent(element, eventName) {
      return new ReadableStream(new class {
        constructor() {
          this._listener = this.listener.bind(this);
        }
        listener(event) {
          this._controller.queue(event);
        }
        start(controller) {
          this._controller = controller;
          element.addEventListener(eventName, this._listener, true);
        }
        cancel() {
          element.removeEventListener(eventName, this._listener, true);
        }
      });
    }
    
    let keyDown = streamFromEvent(document, 'keydown');
    let click = streamFromEvent(document, 'click');
    merge(keyDown, click).pipeTo(userActionsLogger());

This kind of stream can be read by multiple consumers at the same time (since in this case it's infinite) and should drop the chunk immediately after execution (maybe `enqueue` is not a proper name for this operation?).

**Comment by domenic** [comment]
Hi @amatiasq,

This is not what readable streams are intended for. https://github.com/whatwg/streams/blob/master/FAQ.md gives some of the background here.

**Comment by amatiasq** [comment]
I see, thanks @domenic :)
