### ISSUE TITLE
"socket.setTCPWindowSize"

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#483]
https://streams.spec.whatwg.org/#example-rbs-push

> socket\.setTCPWindowSize

The POSIX socket API size does not let you set the window size directly. You can only control it indirectly, by not reading data you are not ready for. When the kernel read buffer fills up, it responds by reducing the window size.

**Comment by tyoshino** [comment]
Right. It's just a hypothetical API we need to really coordinate the Streams with TCP.

**Comment by tyoshino** [comment]
It's there as an example how it could be connected with window based flow-control. Coordination with HTTP/2 is also in the scope.
