### ISSUE TITLE
"Web sockets do not provide any way to tell when..."

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#485]
https://streams.spec.whatwg.org/#ref-for-writable-stream-7

> Web sockets do not provide any way to tell when a given chunk of data has been successfully sent

Not strictly true. The "bufferedAmount" field lets you know when you are accumulating data in the browser, and you can use it as a signal to apply backpressure.

Maybe just remove this comment , since the example is useful?

**Comment by tyoshino** [comment]
Oh, good point. Needs some rewriting.
