### ISSUE TITLE
Repo/package confusion

### ISSUE THREAD

**Issue by ariutta** [whatwg/streams#487]
I was looking for a way to try out WHATWG streams, so I first tried npm package  `whatwg-streams`, but that appears to be an [outdated, dead](https://github.com/Raynos/whatwg-streams/issues/1) implementation. Next, I checked out the [`package.json`](https://github.com/whatwg/streams/blob/master/reference-implementation/package.json) for this implementation, and it lists the name as `whatwg-streams`, but it's not actually  `whatwg-streams` on npm. There's also no `main` entry in `package.json`.

What I was actually looking for was the npm package `web-streams-polyfill`. It would be helpful if the FAQ could reference an npm package. Ideally, @Raynos would point `whatwg-streams` to `web-streams-polyfill`.

**Comment by domenic** [comment]
We can remove the package name from the reference implementation. It's not going to be published anywhere. That's also why it has no main.

I don't think we should endorse specific polyfills in the spec repo.
