### ISSUE TITLE
Use some logging framework

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#499]
https://github.com/whatwg/streams/pull/488#issuecomment-236500833

Such as https://www.npmjs.com/package/debug

**Comment by ricea** [comment]
Is the "debug" package the best choice or does anyone have any other recommendations?

**Comment by domenic** [comment]
I think debug is the right choice. Note https://www.npmjs.com/package/debug#wildcards which could be useful if we create a number of different namespaces under `streams:` or something
