### ISSUE TITLE
piping issue

### ISSUE THREAD

**Issue by jimmywarting** [whatwg/streams#509]
I have included the [web streams polyfill](https://github.com/creatorrr/web-streams-polyfill) into my [project](https://github.com/jimmywarting/StreamSaver.js) and I'm trying to pipe a readableStream to a writableStream 

This is very simplified but it seems to work fine (it dose what i want it to do).
The writable stream gets all chunks it closes when the readableStream closes...
```javascript
var rs = new ReadableStream({
	start(c) {
		c.enqueue(5);
		c.close();
	}
})

var ws = new WritableStream({})

rs.pipeTo(ws)
```
But as soon as i `.close()` the ReadableStream it logs 3 TypeError

```
Uncaught (in promise) TypeError: Reader was released and can no longer be used to monitor the stream's closedness(…)
Uncaught (in promise) TypeError: Writer was released and can no longer be used to monitor the stream's closedness(…)
Uncaught (in promise) TypeError: Writer was released and can no longer be used to monitor the stream's closedness(…)
```
I'm doing something wrong?

**Comment by domenic** [comment]
It's possible this is a bug in our implementation of pipeTo. We still are working to get that specced and implemented better. I'll try to fix that as we work on it.

**Comment by jimmywarting** [comment]
Cool, thanks for letting me know. Hopefully I didn't do anything wrong and i just helped you find a bug :)

I know it's undergoing some changes ATM. But i like to prepare for what is coming :wink:

**Comment by isonmad** [comment]
I don't think this is pipeTo-specific. It's what always happens when the `.closed` promise is rejected, which happens when you do `reader.releaseLock()`. It happens twice for writer because it sets both `.closed` and `.ready` to rejected.

    new ReadableStream().getReader().releaseLock();
    new WritableStream().getWriter().releaseLock();

The promises would have to be lazily rejected in `get closed()` to avoid the warnings, wouldn't they?

**Comment by domenic** [comment]
Let's roll this into #547.
