### ISSUE TITLE
Question: what is the difference of pipeThrough and pipeTo?

### ISSUE THREAD

**Issue by jimmywarting** [whatwg/streams#515]
I have tried to read the documentation but haven't fully understand the difference why you should use the one or the other...

**Comment by domenic** [comment]
Hmm. Could you give more detail on what you find confusing? If I tried to explain it to you I'd just end up repeating what's at https://streams.spec.whatwg.org/#rs-pipe-through and https://streams.spec.whatwg.org/#rs-pipe-to (especially their respective first paragraphs). What is unclear about the difference between those two paragraphs?

**Comment by jimmywarting** [comment]
What would you choose to do this:
```javascript
httpResponseBody
  .pipeThrough(decompressorTransform)
  .pipeThrough(ignoreNonImageFilesTransform)
  .pipeTo(mediaGallery);
```

instead of just doing this:
```javascript
httpResponseBody
  .pipeTo(decompressorTransform)
  .pipeTo(ignoreNonImageFilesTransform)
  .pipeTo(mediaGallery);
```

**Comment by domenic** [comment]
Well, as stated in those paragraphs, `httpResponseBody.pipeTo(decompressorTransform)` will return a promise, which does not have a pipeTo method. And (as stated) `pipeTo` accepts a writable stream, but `decompressorTransform` is not a writable stream. So the latter just won't work.

**Comment by jimmywarting** [comment]
So the chain should only have one pipeTo in the end? and the previous must use pipeThrough?

Would love it if you could show me a simple (jsfiddle?) example with `new TextEncoder` using pipeThrough.

**Comment by domenic** [comment]
In general that's the case, yes.

I can't unfortunately show you an example, since TextEncoder is not a transform stream yet. People are working on that, but right now transform streams are still very much a work in progress, and not ready to ship in a browser. Even writable streams are not in a browser yet, although they've recently gotten much closer to finalized.

**Comment by jimmywarting** [comment]
Ok, think that it is for now. Haven't yet found a use case for it yet.
But if you would want to implement the TextEncoder your self would it be done something like this then?

```javascript
function transform(){
	let enqueueInReadable;
	let closeReadable;
	let encoder = new TextEncoder
	
	return {
		writable: new WritableStream({
			write(chunk) {
				enqueueInReadable(encoder.encode(chunk));
			}
		})
		
		readable: new ReadableStream({
			start(c) {
				enqueueInReadable = c.enqueue.bind(c);
				closeReadable = c.close.bind(c);
			}
		})
	};
}


someStream
	.pipeThrough(transform())
	.pipeTo(log)
```

**Comment by domenic** [comment]
That does seem roughly the right idea, modulo various edge cases :). We have plans to make this easier, with a `new TransformStream` constructor; @ricea has even prototyped using the current version in the repo (which needs to be updated in various ways). Watch this space!

Hope this was helpful!

**Comment by jimmywarting** [comment]
Cool! Thanks for your help!
