### ISSUE TITLE
getReader behaviour with empty mode

### ISSUE THREAD

**Issue by rombel** [whatwg/streams#517]
I have recently updated getReader implementation in WebKit. Based on spec and tests, getReader({ mode: '' }) does not return a ReadableStreamDefaultReader but throws a RangeError. The patch has been reviewed and committed, but I was asked to check this is not a spec error [1]. Could you confirm this is the intended behaviour?

[1] https://bugs.webkit.org/show_bug.cgi?id=160508#c14

**Comment by domenic** [comment]
Right, this is correct. { mode: undefined }, or omitting the parameter entirely, will return a default reader.

**Comment by rombel** [comment]
Thanks for the confirmation.
