### ISSUE TITLE
Pass controller to transformer methods in TransformStream

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#518]
Currently methods of the transformer object are passed individual parameters for each action they can take. For example, the transform method is called like this:

```javascript
transform(chunk, done, enqueue, closeReadable, error)
```

where `done`, `enqueue`, `closeReadable` and `error` are all functions that `transform()` can call in processing `chunk`.

For consistency with ReadableStream and WritableStream, it would be better if the methods were passed a controller object. The definition would be something like

```javascript
class TransformStreamDefaultController {
  constructor(stream)

  done()
  enqueue(chunk)
  closeReadable()
  error()
}
```

In a Promise-based implementation `done()` and `error()` would go away.

Then the signature of `transform()` would change to

```javascript
transform(chunk, controller)
```

**Comment by isonmad** [comment]
Since WritableStream only passes the controller to `start()`, and since the transformer can similarly store the controller for later use, does `transform()` need a second parameter at all?

**Comment by ricea** [comment]
My view is that someone has to store the controller. If the TransformStream does it, then that code only exists in one place. If the transformer does it, then every transformer implementation has to include code to store the controller, including implementing a start() method even if they didn't need one.
