### ISSUE TITLE
Link promise-manipulating phrases to the promises guide

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#532]
https://streams.spec.whatwg.org/#rs-default-controller-constructor

> Resolve startResult as a promise:​

Where is the term "Resolve * as a promise" defined? I can't find the definition.

**Comment by domenic** [comment]
I guess I did not use the same exact words as https://www.w3.org/2001/tag/doc/promises-guide#resolved-as-a-promise, but that's the intent.

**Comment by ricea** [comment]
So it is explicitly async then.

The reason I'm asking is that there are a bunch of tests using setTimeout(restOfTheTest, 0) to ensure that the sink's start() promise has resolved (even when it has no start() method). This is ugly and I was wondering what to do about it.

I think in most cases the setTimeout() can be replaced with writer.ready.then(), unless the test is intended to check the ordering of some other promise(s) with respect to the initial value of writer.ready, in which case we'll have to use delay(0).then().

Is it okay for the spec to use w3.org/.../promises-guide as the definition for that terminology?

**Comment by domenic** [comment]
> This is ugly and I was wondering what to do about it.

I think the best pattern for that is this one: https://github.com/whatwg/streams/blob/ba1e784ec2761fa7e992c80e1c3ef0f10b991ce1/reference-implementation/to-upstream-wpts/writable-streams/bad-underlying-sinks.js#L51-L64

> Is it okay for the spec to use w3.org/.../promises-guide as the definition for that terminology?

Yeah; that's stated in https://streams.spec.whatwg.org/#conventions. We should probably work to make them link to their definitions.

**Comment by ricea** [comment]
> Yeah; that's stated in https://streams.spec.whatwg.org/#conventions. We should probably work to make them link to their definitions.

I must have missed the significance of that when I read it the first time. I will leave this issue open until someone has time to add the links.
