### ISSUE TITLE
"If stream.[[readableStreamController]] is not u..."

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#543]
https://streams.spec.whatwg.org/#rs-default-controller-constructor

> If stream\.\[\[readableStreamController\]\] is not undefined, throw a TypeError exception\.

I believe this should be an assert, ie. Assert: _stream_\.\[\[readableStreamController\]\] is **undefined**\.

My reasons are

1. ReadableStreamDefaultController is not exported, so it can only be constructed from within the spec.
2. The algorithm in the ReadableStream constructor which constructs it does not permit \[\[readableStreamController\]\] to be defined at this point.

The same applies to ReadableByteStreamController and WritableStreamDefaultController.

**Comment by tyoshino** [comment]
I think you're right. Maybe this is a remnant from bunch of refactoring.

**Comment by domenic** [comment]
> ReadableStreamDefaultController is not exported, so it can only be constructed from within the spec.

You can get it though:

```js
let ReadableStreamDefaultController;
new ReadableStream({
  start(c) {
    ReadableStreamDefaultController = c.constructor;
  }
});

new ReadableStreamDefaultController({});
```

**Comment by ricea** [comment]
Wow. Okay, I wasn't thinking deviously enough. I have proposed some tests to verify this behaviour for WritableStream in #544.

It looks like brand-checks.js effectively covers this stuff for ReadableStream.

**Comment by tyoshino** [comment]
Oh, sorry. Yeah, we can get the constructor..
