### ISSUE TITLE
"Set chunkSize to Call(stream.[[strategySize]], ..."

### ISSUE THREAD

**Issue by fd** [whatwg/streams#546]
https://streams.spec.whatwg.org/#readable-stream-default-controller-enqueue

> *5.b.i.* Set chunkSize to Call\(stream\.\[\[strategySize\]\], undefined, « ‍chunk »\)\.

should be 

> *5.b.i.* Set chunkSize to Call\(controller\.\[\[strategySize\]\], undefined, « ‍chunk »\)\.

**Comment by tyoshino** [comment]
Fixed by aba1515561b7c0155c5044274e5c4158e82b3607. Sorry I forgot to quote this issue in the commit message. But I'd like to add you to the acknowledgement section. Can we add you as `Simon Menke`?

**Comment by fd** [comment]
@tyoshino: Sure! `Simon Menke` is the correct spelling for my name 😉

**Comment by tyoshino** [comment]
Added. Thanks!
