### ISSUE TITLE
Marking promise rejections as handled

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#547]
See https://bugs.chromium.org/p/chromium/issues/detail?id=654701 for background /cc @yutakahirano @jakearchibald. Also https://github.com/whatwg/streams/issues/468 is kind of related, but that issue was about pipeTo which was confusing since pipeTo was under flux at the time.

A simple repro ([run in Chrome](http://jsbin.com/sopogoyoyi/edit?html,output)) is

``` js
window.onunhandledrejection = e => {
  console.log(e.reason);
};

const rs = new ReadableStream({
  start(controller) {
    controller.close();
  }
});
const reader = rs.getReader();
reader.releaseLock();
```

This will log an unhandled rejection (and also show up in the console in Chrome, but that's a browser-specific devtools thing).

I think the correct solution is that all "state promises" like `.closed` should be marked as having their rejection handled (i.e. their [[PromiseIsHandled]] slot should be set to true).

**Comment by tyoshino** [comment]
Is your idea to run the suppression (either `thenPromise` or `[[PromiseIsHandled]]`) on `releaseLock()` call (maybe right before rejecting them), or to mark promises considered to be "state promises" from the beginning?

I think if the needs for marking promise rejections (or fulfillment) handled are considered to be common, we should address this as you said in the OP here than use of ad-hoc suppression (no-op) as you introduced in the Chromium bug tracker.

Can we come up with clear and reasonable criteria (guideline) for deciding whether or not to use this? The phrase "state promises" looks to be capturing the scope well, but still sounds a bit vague.

If we focus only on this issue specifically, it looks we should just mark promises that became (on releaseLock()) to be not expected to be handled as far as the code is "correct" (after releaseLock(), we shouldn't need to touch the promises basically).

**Comment by domenic** [comment]
> Can we come up with clear and reasonable criteria (guideline) for deciding whether or not to use this? The phrase "state promises" looks to be capturing the scope well, but still sounds a bit vague.

My intent was indeed to come up with such a criteria. By "state promises" I mean something like "properties that are promises that reflect some state change". In general for such promises, I would expect that every time you reject them (including creating them in a rejected state), you mark them as handled.

**Comment by tyoshino** [comment]
As we recently changed WritableStreamDefaultWriter's ready to be rejected. So, those who're not interested in backpressure signal i.e. watching only .closed would see the warning on error. This would lead to adoption of the "state promises" criteria.

**Comment by tyoshino** [comment]
Hmm, okay. I just understood that the ECMA spec has the HostPromiseRejectionTracker concept defined that is independent from implementation specific behavior. IIUC, for what this is intended is not explained in the spec (maybe intentionally). We could explain that in the promises-guide (or its successor? it's frozen?) with some example of its application (debug info) explain how to mark promises as handled than trying to build a guideline without mentioning possible applications?

**Comment by tyoshino** [comment]
For Streams case, I agree that we should mark `.ready` and `.closed` as handled given the analysis above.

**Comment by domenic** [comment]
Yeah it might be good to add some stuff to promises guide about this. The application is for https://html.spec.whatwg.org/multipage/webappapis.html#unhandled-promise-rejections

**Comment by tyoshino** [comment]
Thanks for the pointer!

**Comment by ricea** [comment]
I think the same concern applies to the Promises returned by write() and close(), based on  my reading of the tests. They are frequently not handled, even though I wouldn't call them "state promises" as such. "event promises" maybe?

My analysis is that there are multiple ways of observing an error on a stream, only one of which needs to be handled for a program to be correct.

Possible solutions that come to mind:

1. Radically change the standard so that there is only one way of observing error.
2. Unconditionally mark all promises as handled.
3. Come up with some magic that marks all the promises as handled if at least one was handled.

**Comment by ricea** [comment]
Offtopic: I've confirmed that Chrome does suppress the console message if you return false from the event handler, as implied by the standard: http://jsbin.com/narucopufi/1/edit?html,console,output

**Comment by yutakahirano** [comment]
I thought the uncaught-rejection warning was Chrome specific. Is the concept shared by other implementers?

**Comment by ricea** [comment]
I just realised that we can resolve this for getters by creating the Promise lazily when the getter is used. So, for example, the [[closedPromise]] slot of WritableStreamDefaultWriter would be undefined until `.closed` was accessed. User code which actually uses the getter is required to handle rejections.

**Comment by domenic** [comment]
> I think the same concern applies to the Promises returned by write() and close(), based on my reading of the tests.

Yes, this is true; I agree with your analysis. However, I think I disagree on the solution. IMO if you do something like calling close() or write() and an error occurs, it's OK to get an unhandled rejection. You'll get notified about the error, which is good. What's not good is for the getters, which are just updated to keep things in sync, to start telling you about errors. You did not call them.

So I would be OK with only fixing the getters, and not marking the promises returned by write() or close() as handled.

> I just realised that we can resolve this for getters by creating the Promise lazily when the getter is used.

That's really interesting. I guess the difference for authors would be that, given

```js
writer.closed.then(() => console.log("good!"));
```

if the stream is errored, then with lazy getters they will still get an unhandled rejection here, whereas with the proposed mark-as-handled, they will not.

This will be fairly invasive spec-wise :-/. But I guess it's probably the better solution, so we should do it.

**Comment by isonmad** [comment]
> I just realised that we can resolve this for getters by creating the Promise lazily when the getter is used.
> That's really interesting.

That's what I said in https://github.com/whatwg/streams/issues/509#issuecomment-247786396 last month. I never got a response though.

**Comment by domenic** [comment]
Sorry about that. As I said in the OP, I found that issue confusing, so it was hard to make sense of much of anything in that thread.

**Comment by isonmad** [comment]
Wait what, you referenced #468 in the OP, I replied to #509.

**Comment by ricea** [comment]
Sorry @isonmad, I missed your comment on #509.

**Comment by tyoshino** [comment]
I also see some good point in Adam's analysis and isonmad's proposal, but am leaning toward the plan to mark the "status" promises as handled.

Regarding the lazy promise creation idea, I'd like to confirm if this related to the principle about semantics of getters we discussed during the Fetch API's `Response.body` design. That is IIRC that if evaluating the member has any side-effect observable in JS should be implemented as a method. As showing the warnings is not observable in JS but only inspector, it's ok?

**Comment by ricea** [comment]
If I understand correctly, there is a visibility difference to JS:

with lazy initialisation, doing

```javascript
reader.ready.then(() => something());
```

would result in an `unhandledrejection` event, but never touching `reader.ready` at all would not.

If we mark the promise as handled, then neither would result in an `unhandledrejection` event.

**Comment by tyoshino** [comment]
Oh, I see. Thanks, Adam. I'd like to also hear @domenic 's opinion on this.

**Comment by domenic** [comment]
> That is IIRC that if evaluating the member has any side-effect observable in JS should be implemented as a method.

Hmm this does make me rethink things. It is very subtle but it does seem like this is having an observable side effect. It is more clear if you state it as the fact that with a lazy-promise-creation approach, adding the code

```js
reader.ready;
```

to your program will cause an `unhandledrejection` event. That is not great.

I guess this pushes me back to thinking that status promises should simply never trigger unhandledrejection. So we should just go with the simple mark-as-handled approach. Do others agree?

**Comment by ricea** [comment]
I think the principle that accessing members should have no side-effects is good. Whether we want to be completely strict about this principle is a larger question that impacts the whole platform. I certainly wouldn't want this to be the only exception to the rule in all browser APIs.

**Comment by domenic** [comment]
I don't think it's uniformly followed, but the cases where it is not are widely seen as regrettable mistakes that we should not continue. I've also never heard of touching a property causing an event to fire; that might be unprecedented.

See also https://w3ctag.github.io/design-principles/#attributes-like-data

**Comment by ricea** [comment]
That's clear then. Let's mark all state promises as handled by default.

**Comment by tyoshino** [comment]
I'm for it, too.
