### ISSUE TITLE
"Let controller be this."

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#552]
https://streams.spec.whatwg.org/#ws-default-controller-constructor

> Let controller be this\.

I don't understand the purpose of this statement. Why can't we keep using **this** for **this**?

**Comment by tyoshino** [comment]
I introduced this step to use the controller instance in the fulfillment callback when implementing this in the reference implementation without thinking deeply. And then, ported it to the spec text.

Let me think about it again more seriously. For the reference implementation, if the arrow function is used inside the WritableStreamDefaultController method, we can bind `this` to be used in the fulfillment/rejection handler to the controller. Or, we could use .bind() to do the same thing.

For the spec text, I think the current form is good in terms of clarification than assuming that even in the created callbacks `this` is referring to the same this.

**Comment by tyoshino** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#No_binding_of_this

**Comment by ricea** [comment]
Ah, I see. So I had forgotten about the problems with `this` In Javascript. I think it's okay to keep that line in the spec. If you are happy with it, you can close this issue.

I think I will keep it in the Chrome implementation too, at least for now.

**Comment by tyoshino** [comment]
sounds good. thanks
