### ISSUE TITLE
pipeTo(): Rationale for not making shutdown() no-op when shuttingDown is set

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#557]
Forked from https://github.com/whatwg/streams/pull/512#issuecomment-255938194

This https://github.com/whatwg/streams/pull/512#issuecomment-255754552 approach sounds not so good to me.

I understand that it sometimes works well for simplifying code to omit logic to suppress harmless processing and just let it happen as no-op. But I think such approaches should be taken only when:
- it's very clear that the operations would result in no-op
- or, there's a clear win of performance compared to introduced complexity of the carefully implemented optimization

To ensure that the redundant finalize() is harmless, we need to ensure that it happens only after everything it affects is settled down. There are, a promise (waitForCurrentWrite()) involved, three possible actions happen in action(), 3 abstract operation (promise resolution) invocation in finalize(). It's too much.

Actually, I just found a real bug in the current code. An error of the WritableStream caused by `.abort()` invocation by the `pipeTo()` logic (during `shutdownWithAction()` assuming the `preventAbort` was set to falsy) in response to the ReadableStream's error would also invoke `shutdown()` (assuming `preventCancel` was set to truthy) for the abortion of the WritableStream. When the underlying sink's `abort()` takes time e.g. please try changing the underlying sink's `abort()` to be `delay(10).then(() => { throw error2; })`, `finalize()` call for the `shutdown()` would win. In this example, the `pipePromise` gets rejected with `new TypeError('Aborted')` while it's expected that `pipePromise` gets rejected by `error2`.

Even after fixing this bug, despite of the cost of reasoning, there should not be much performance/readability gain with this omission, I guess. We already have the `shuttingDown` defined for the async case. Additional if-clause wouldn't be a big pain for us and readers in terms of either readability or performance. With the if-clause, we can omit a microtask containing invocation of 3 meaningless function calls and make the solidness of the logic easier to reason about.

Additionally, the name `shuttingDown` sounds like a book keeping variable for controlling duplicated invocation of shutdown.*(). It strikes at least to me that it's confusing that only `shutdownWithAction()` has an if-clause to be no-op when `shuttingDown` is set.

**Comment by domenic** [comment]
So my main concern is that with pipeTo, we are trying to do something different from normal and spec the observable semantics only. If we start getting too algorithmic we may get in the way of that. The existing algorithmic bookkeeping is meant to capture aspects of the shutdown sequence that are hard to specify otherwise.

So if we have bugs, we need to fix them. But for any other such changes, if they are not observable, then I think we should lean toward simplicity. I'm having a bit of a hard time figuring out which this is and would appreciate your help there.

**Comment by domenic** [comment]
Looking at this again it seems likely that making it a no-op is correct. It is pretty simple to spec now that I've separated shuttingDown and finally. I'd like to get a test written up that ensures that code path is exercised (maybe the one about the bug you mention). If you want to help write that up in a bit more detail that would be really helpful.

**Comment by tyoshino** [comment]
I think I've been aware of what you've been trying to accomplish and its value correctly.

What I suggested can be summarized as "the shutdown sequence should happen only once triggered by the first error / close observation". There're 2 observation points (writable.closed, readable.closed) and two types of events (fulfillment and rejection) for each. These 4 events are observed separately by 4 different callbacks. Actions required to happen as reaction to them can happen in parallel. But, on the other hand, there's only one receiver of the completion which is the reject(), resolve() function for the pipePromise and depends on the result of the action taken. So, it's natural that we need some logic to do mutex-ing (bookkeeping) to run only one of the 4 callbacks.

Sorry, I didn't have time today for help writing tests. I'll do it tomorrow.
