### ISSUE TITLE
pipeTo(): Rationale for propagating an error happened during error propagation to pipePromise

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#558]
Forked from https://github.com/whatwg/streams/pull/512#issuecomment-255345690

I'd like to record how we concluded to adopt this semantics.

`.pipeTo()` propagates error in both forward and backward direction by calling `.abort()` and `.cancel()` respectively. Before #512, I implemented it to throw away any error during the error propagation and reject the `pipePromise` with the original reason.

Domenic proposed that we change it to propagate an error happened during error propagation to `pipePromise` with explanation of the rationale at https://github.com/whatwg/streams/pull/512#discussion_r83466000. I understand Domenic's point that "both errors are seen by someone" is important.

So, when the destination WritableStream is errored during pipeTo() with `preventCancel` set to falsy:
- if the propagation (`reader.cancel()`) is successful, the `pipePromise` gets rejected with the original error
- otherwise, the `pipePromise` gets rejected with the error in `reader.cancel()`. In this way, the error in `reader.cancel` is seen via `pipePromise` while the original error can be obtained by looking at the destination WritableStream even when the propagated original error hasn't successfully remembered by the source ReadableStream.

I personally think it's a bit inconvenient that we need to check the destination writer to see the original reason and prefer e.g. making the resolution of `pipePromise` be a structure (even an Array is fine) to be able to hold both the original error and optionally an error during propagation if any. This would make the interface complicated, and is not based on real experience in application development.

So, we're going to adopt Domenic's idea, but we appreciate if you could comment to this issue when you have any other rationale or encounter any real situation which would support either of the approaches.

**Comment by domenic** [comment]
Hmm. Let's concentrate on only one scenario so I don't have to keep saying cancel/abort. So consider

```js
const rs = new ReadableStream({
  start(c) {
    c.enqueue(1);
    c.error(error1);
  }
});

const ws = new WritableStream({
  abort(err) {
    throw error2;
  }
});
```

To me the `abort(err)` handler is kind of like a `catch`-and-rethrow clause. By default it will "rethrow" the error passed in. But since `error2` is encountered while handling `error1`, the outer caller (i.e. the caller of `pipeTo`) instead sees `error2`.

Does that help?

**Comment by tyoshino** [comment]
> To me the abort(err) handler is kind of like a catch-and-rethrow clause. By default it will "rethrow" the error passed in. But since error2 is encountered while handling error1, the outer caller (i.e. the caller of pipeTo) instead sees error2.

This is an interesting view point and would help get convinced on the design though it's limited to the cases where `ReadableStreamCancel()`, `WritableStreamAbort()` successfully invoke `underlyingSource.cancel()`, `underlyingSink.abort()`.

Thanks Domenic. I'll close this issue for now.

Anyone who finds this behavior inconvenient, unclear, etc., please comment on this issue with your opinion so that we can revisit it.
