### ISSUE TITLE
Default transform() method should be the identity transform

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#565]
Currently `transformer.transform()` is compulsory. The TransformStream constructor will throw a TypeError if you do not set it.

I think instead if `transformer.transform` is undefined it should be equivalent to

```javascript
transform(chunk, controller) {
   controller.enqueue(chunk);
}
```

This enables two useful things:
* A transformer which just adds a fixed header and footer can be implemented with just `start()` and `flush()`.
* A transformer which just buffers can by implemented by specifying an empty _transformer_ and a strategy.

Both these things can be done by specifying the `transform()` method explicitly, but skipping it

1. Is shorter,
2. Enables optimisations by making the transformation unobservable from Javascript.

**Comment by domenic** [comment]
A long time ago when this last came up I was against this, prefering that we provide an explicit `TransformStream.identity()` and treat omitting the transform() transformer method as a bug. I guess those discussions were way back in https://github.com/whatwg/streams/issues/20#issuecomment-47719057.

However, your argument about the two useful things it enables are pretty compelling and overturn my previous ideas. So let's indeed make it optional. We should try to remember to include such examples in the spec, when we get around to writing it.

**Comment by jakearchibald** [comment]
Whoa @ricea, I was talking to @domenic about this yesterday. Coincidence?

**Comment by domenic** [comment]
I just saw code that did this in https://github.com/whatwg/streams/pull/773 and I was pretty confused. I wonder if we should add a `TransformStream.identity()` "alias"?

**Comment by jakearchibald** [comment]
Does that mean `TransformStream` would throw without a transform function?

**Comment by domenic** [comment]
No. I think the reasoning still holds. We event want it to be OK to pass no transformer at all and just pass novel strategies.

It'd be basically an alias for readability of code. I'm not sure it's worth it, but I wanted to mention the idea.

**Comment by jakearchibald** [comment]
I don't think we need it, but we can easily add it later.
