### ISSUE TITLE
Cancelling a pipe

### ISSUE THREAD

**Issue by neovov** [whatwg/streams#576]
I was wondering, how can I cancel a pipe?

For instance, I have something like this:
```js
let readable = new ReadableStream({…}); // Fetch a 10Mb file
let transform = new ReadableStream({…});
let writable = new WritableStream({…});

readable
  .pipeThrough(transform)
  .pipeTo(writable);
```

I'm trying to cancel this pipe in order to re-start it by fetching at another offset (seeking in the file).
Calling `readable.cancel()` will reject the promise since the reader is locked ("Cannot cancel a stream that already has a reader").
Calling `controller.close()` will also throw errors ("Reader was released and can no longer be used to monitor the stream's closedness" and "Writer was released and can no longer be used to monitor the stream's closedness" multiple times).

Is there something I'm doing wrong?

**Comment by domenic** [comment]
The plan is, once [cancelable promises](https://github.com/tc39/proposal-cancelable-promises) are ready, pipeTo will return a cancelable promise you can use. Until then, setting up a pipe is irreversable until the source/dest close/error.

As such, I'm going to close this as a dupe of https://github.com/whatwg/streams/issues/446, but I'm happy to discuss in the closed thread or over there.

> Calling controller.close() will also throw errors ("Reader was released and can no longer be used to monitor the stream's closedness" and "Writer was released and can no longer be used to monitor the stream's closedness" multiple times).

These errors should not occur, but are probably an artifact of using a not-yet-specced pipeTo implementation.

**Comment by neovov** [comment]
Sounds great, thanks for your time.
