### ISSUE TITLE
"non-negative" or "nonnegative" ?

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#585]
https://streams.spec.whatwg.org/#ref-for-queuing-strategy-1

> non\-negative

Standard text uses both "nonnegative" (twice) and "non-negative" (twice). We should pick one.

The capitalisation of abstract operations like IsFiniteNonNegativeNumber implies that "non" and "negative" are considered as separate words, so I prefer "non-negative".

**Comment by bterlson** [comment]
FWIW, ECMA262 uses nonnegative.

**Comment by bterlson** [comment]
Although according to https://en.wiktionary.org/wiki/non- I should probably update this to non-negative which is proper for the Queen's (and ECMA's) English.

**Comment by domenic** [comment]
HTML also uses non-negative, so I went with that.
