### ISSUE TITLE
Editorial: "return undefined." vs. "return"

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#587]
https://streams.spec.whatwg.org/#default-writer-release-lock

> return undefined

There seems to be inconsistent usage between "return undefined." and "return.". I think if a method or operation has no explicit return in its main path, then other paths should use "return." rather than "return undefined.".

There also appear to be some operations that have an unnecessary explicit "return undefined." at the end, but maybe I am just missing the reason for it.

**Comment by domenic** [comment]
I think ES uses "Return undefined" everywhere (even at the end of algorithms), and I rebelled against that because it seems pretty unnecessary, but did so inconsistently. Probably going for minimalism ("Return." and not including one at the end explicitly) is good.
