### ISSUE TITLE
Why are [[writeRequests]] and [[queue]] separate?

### ISSUE THREAD

**Issue by isonmad** [whatwg/streams#589]
Unlike [[readRequests]], they're both on the WritableStreamDefaultController object, and also unlike [[readRequests]], chunks and write requests both come from the same direction and arrive at the same time, so there's always a 1:1 correspondence. Is there any reason to have two parallel queues besides symmetry with ReadableStream? Will it be useful for writable byte streams somehow?

I didn't see an explanation in https://github.com/whatwg/streams/pull/488#r72936794

**Comment by ricea** [comment]
Nitpick: [[writeRequests]] is actually on the WritableStream object. My guess is the same as yours: it will make it easier to add byte streams in future. But I will wait to hear from @tyoshino.

**Comment by tyoshino** [comment]
I tried to have the ReadableStream (and readers) and WritableStream (and writers) contain only the logic to represent the constraints of the interfaces and have the controllers hold the remaining part i.e. helper functionality for source/sink implementors.

It's up to the sink implementor how to maintain the written chunks. The byte-stream variant to be introduced may detach the passed values, and in such case, it doesn't make much sense to hold them inside the WritableStream. On the other hand, it's one of the constraints of WritableStream interface that:
- each write() and close() returns a promise,
- they'll be fulfilled/rejected in the same order,
- they'll get rejected on error

So, I represented these in the WritableStream class using `[[writeRequests]]` in it, the abstract operations as members of the WritableStream, and assertions in them. We can, of course, ask the sink implementor (including the controller) to follow these constraints in the form of more assertions or spec texts, but the point is that it's better that we represent them as code inside the WritableStream class as much as possible.

**Comment by ricea** [comment]
With #619 `writer.close()` promises and the promise from the current `writer.write()` no longer appear in [[writeRequests]], removing the 1:1 relationship with [[queue]]. An implementation could still choose to combine them, but they'd make life difficult for themselves when they came to implement WritableStreamByteController.

Can I close this?
