### ISSUE TITLE
Closing the controller with a pipe

### ISSUE THREAD

**Issue by neovov** [whatwg/streams#606]
I was wondering, why does closing a controller raise a TypeError? (https://streams.spec.whatwg.org/#rs-default-controller-close)

For example, I have something like that:
```
new ReadableStream({
  start(controller) {
    controller.enqueue(whatever);
    controller.close();
  }
}).pipeThrough(transform).pipeTo(writable)
```

I get a bunch of `Uncaught (in promise) TypeError: Writer was released and can no longer be used to monitor the stream's closedness` (4 Writer was released, 2 Reader was released)

**Comment by neovov** [comment]
To test quickly:
```
new ReadableStream({
  start(controller) {
    controller.close();
  }
}).pipeThrough(new TransformStream()).pipeTo(new WritableStream())
```

**Comment by domenic** [comment]
This is a symptom of https://github.com/whatwg/streams/issues/547 and will be fixed when we fix that.

**Comment by neovov** [comment]
Alright, thanks.
Sorry if I'm spamming you ; I am using the reference implementation on a project and wonder if I am using it correctly. I will be glad to help, in an authoring point of view.

**Comment by domenic** [comment]
No problem! It's a little scary to see someone using the reference implementation in a project, as it's not really meant for production code, but we'll certainly take the feedback anyway :)

**Comment by neovov** [comment]
I know it's not really meant for production, but I like to live dangerously :).
More seriously though, I'd rather use a standard than shipping soon-to-be obsolete code. Besides, streams are perfect for what I need to do — an audio player with proprietary decryption (unfortunately I can't use EME) — and Chromium already have a partial implementation of ReadableStream. Cheers 🍻
