### ISSUE TITLE
Change directory listing order

### ISSUE THREAD

**Issue by annevk** [whatwg/streams#614]
For commit snapshots it would be nice to sort them by last modified in descending order. https://github.com/whatwg/misc-server/blob/master/shared/partof.whatwg.org..htaccess shows how that can be done. https://dom.spec.whatwg.org/commit-snapshots/ demonstrates it working well.

**Comment by domenic** [comment]
Done, thanks! And as a bonus streams and console got the other goodies in that file, like HSTS and CORS.
