### ISSUE TITLE
Reference defining "transforming [promise] by a fulfillment handler" ?

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#622]
https://streams.spec.whatwg.org/commit-snapshots/872188a984722861020ae773a5ee558892797c33#readable-stream-tee

> by a fulfillment handler

Although it's quite obvious what this means, it would be nice if there was a reference defining it explicitly.

**Comment by domenic** [comment]
https://www.w3.org/2001/tag/doc/promises-guide#transforming-by should do the trick

**Comment by ricea** [comment]
Does Bikeshed have markup for linking "transforming _p_ with a fulfillment handler" where _p_ is an arbitrary string containing markup and/or links?

**Comment by domenic** [comment]
We should be able to just do `<a>Transforming</a> _arbitrary string_ with a fulfillment handler`?

**Comment by ricea** [comment]
Yes, that works. PR to follow.
