### ISSUE TITLE
Do not allow abort() to interrupt a closing writable stream?

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#632]
I thought this would have been taken care of by https://github.com/whatwg/streams/commit/591a6eda9ea0b84881a370519d6aca53fab9e256, but it seems like there is a subtle difference between "closing" (a close request has been queued) and [[inClose]] === true (underlying sink close() is executing).

I am wondering if we can remove the wart currently noted as

> Due to the way writable streams asynchronously close, it is possible for both close and abort to be called, in cases where the producer aborts the stream while it is in the "closing" state. Notably, since a stream always spends at least one turn in the "closing" state, code like ws.close(); ws.abort(...); will cause both to be called, even if the close method itself has no asynchronous behavior. A well-designed underlying sink object should be able to deal with this. 

I started some work on this in https://github.com/whatwg/streams/tree/close-then-abort but my method of doing so broke the requirement that close() not happen before start() finishes. I think there might be another better method, but it's not clear to me what it is quite yet...

**Comment by tyoshino** [comment]
IIRC, the note was about possible invocation of both `sink.close()` and `sink.abort()` on the same sink due to that completion of `sink.close()` is processed and reflected to the state of the stream asynchronously and until that happens `sink.abort()` is not rejected. So, this is no longer the case. Once `sink.close()` is called, `[[inClose]]` is set to **true** to delay `writer.abort()` execution and then it never invokes `sink.abort()`.

**Comment by tyoshino** [comment]
Ah, not so sure if I remember correctly. But let me explain more.

The concern I raised before was that even after the promise returned by `sink.close()` is fulfilled, until the fulfillment is propagated to the logic to update the state of the stream to set it to `"errored"`, `writer.abort()` is not prevented, and therefore, the sink may receive `sink.abort()` even after finishing `sink.close()` successfully. I thought that the note was originally about this concern about the very edge case. IIRC, ... domenic wrote this note and talked about not only the edge case but generally about the possiblility of `sink.abort()` invocation during `sink.close()`.

**Comment by tyoshino** [comment]
Now, both the edge case and non-edge cases are already taken care of by the `writer.abort()` delaying logic recently introduced.

The only remaining case where we don't delay `writer.abort()` that is made after `writer.close()` is, as you said in the OP, a close request not yet picked by `WritableStreamDefaultControllerProcessClose()`. I think this is aligned with that write requests can be aborted immediately unless it's been picked by `WritableStreamDefaultControllerProcessWrite()`.

**Comment by tyoshino** [comment]
Ohhhhh, sorry. I was misunderstanding. `WritableStreamAbort()` is not delayed during `"closing"`.

**Comment by tyoshino** [comment]
Removed the comment in a25f410cbccfbaf56479ca3224fe57bab8b2b6fa. As I stated in the comments here, it's been already fixed before a25f410cbccfbaf56479ca3224fe57bab8b2b6fa.

As I said in https://github.com/whatwg/streams/pull/672#issuecomment-285698434, we should merge some of tests in domenic's https://github.com/whatwg/streams/tree/close-then-abort branch. See #694.
