### ISSUE TITLE
Consolidate "closing" state and [[pendingClosePromise]]?

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#633]
I think they are redundant, that is, everywhere we check "writing", we can check if [[pendingClosePromise]] is not undefined and state is "writable".

It's nicer to not have the redundancy since right now the spec has to make sure they stay in sync manually.

**Comment by ricea** [comment]
I think you are correct.

I felt that including these things in [[state]] was useful as explanation of the lifecycle of the stream, but I'm really not sure now.

**Comment by tyoshino** [comment]
This is done by a25f410cbccfbaf56479ca3224fe57bab8b2b6fa!
