### ISSUE TITLE
pipeTo() algorithm shuts down too early on readable close()?

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#644]
I think there's an issue with the pipeTo() algorithm that prevents writing all the data. When the underlying source calls `close()` the state of the ReadableStream changes immediately to "CLOSED". If there is a `read()` on the readable ongoing at that point then pipeTo shutdown starts immediately, prohibiting the data that was read from being written to the WritableStream.

I'm not 100% certain that this is a spec issue yet but I am making a note of it to look at it again later. I will close this bug if I conclude there is no actual issue.

**Comment by ricea** [comment]
A related problem is that if the source queues several items and calls `close()`, then the sink errors while writing one of those items, the standard implies that since the readable became CLOSED first, pipeTo should fulfill without error. I think it should reject with the error from the sink. I need to check whether there is a test for this case and add one if there isn't.

**Comment by ricea** [comment]
I've concluded that there is an issue here.

**Comment by ricea** [comment]
> It sounds like the problem is in "Shutdown must stop all activity". We want any reads to always be followed by writes... as long as the dest is "writable", I guess. Shutdown says "Wait until any ongoing write finishes" already, but if the write isn't ongoing yet that doesn't work.

I will try to come up with some wording for this.

For the Chromium implementation, I'm thinking of removing the 'Wait until any ongoing write finishes (i.e. the corresponding promises settle).' step from 'shutdown with action' because now that we treat underlying sink write() as uninterruptible it doesn't make any difference any more, and that step is troublesome to implement. Maybe we should also remove it from the standard?

> I think this works with the current spec:
> 
> close() ends up in "Closing must be propagated forward"
> We go to "shutdown with an action" of WritableStreamDefaultWriterCloseWithErrorPropagation(writer).
> We wait for any ongoing writes to finish. One errors, causing dest.[[storedError]] to be set.
> We let p be the result of performing WritableStreamDefaultWriterCloseWithErrorPropagation(writer).
> p is rejected with dest.[[storedError]].
> We finalize with dest.[[storedError]].

I see. I will write a test for this, after checking that it isn't already covered.

**Comment by domenic** [comment]
> For the Chromium implementation, I'm thinking of removing the 'Wait until any ongoing write finishes (i.e. the corresponding promises settle).' step from 'shutdown with action' because now that we treat underlying sink write() as uninterruptible it doesn't make any difference any more, and that step is troublesome to implement. Maybe we should also remove it from the standard?

Yeah, that sounds good to me, as long as the sanity test of removing its implementation from the reference implementation doesn't cause any test failures.

I guess it would be observably different in that the readable stream might become canceled sooner. Which is probably a good thing.

**Comment by ricea** [comment]
> I guess it would be observably different in that the readable stream might become canceled sooner. Which is probably a good thing.

So, specifically, we get different behaviour when the underlying sink on the end of a pipe calls `controller.error()` without immediately rejecting the promise returned from `write()`. Back propagation starts sooner, meaning that earlier pipeTos can be rejected before that write completes. I think this doesn't matter, because

1. The call to `controller.error()` implies that the write is never going to do anything useful, however long it takes.
2. Using the normal `readable.pipeThrough(transform).pipeTo(writable)` syntax no-one is observing the result of any `pipeTo()` but the last one anyway.

**Comment by domenic** [comment]
That reasoning seems sound to me.

**Comment by tyoshino** [comment]
I'm not sure how much the point (2) helps get convinced with the behavior, but I agree with your plan.

**Comment by domenic** [comment]
I wrote at least one test for this here: https://github.com/w3c/web-platform-tests/pull/5270

However I am having trouble making the reference implementation pass (while still passing all other tests). I'll keep banging on it, but if anyone wants to jump in that'd be cool too.

I think the spec wording is pretty straightforward too: basically we want to talk about read/write pairs, and less about reads and writes.

It's possible that, given the connection here to "Wait for any ongoing writes to finish", we should wait until #715 is resolved.
