### ISSUE TITLE
Constructing a readable byte stream can reach code that assumes a default reader

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#646]
Found by @tschneidereit:

- [new ReadableStreamDefaultController](https://streams.spec.whatwg.org/#rs-default-controller-constructor) step 11.a.iv. ->
- [ReadableStreamDefaultControllerCallPullIfNeeded](https://streams.spec.whatwg.org/#readable-stream-default-controller-call-pull-if-needed) step 1 ->
- [ReadableStreamDefaultControllerShouldCallPull](https://streams.spec.whatwg.org/#readable-stream-default-controller-should-call-pull) step 5 ->
- [ReadableStreamGetNumReadRequests](https://streams.spec.whatwg.org/#readable-stream-get-num-read-requests) which assumes _stream_.[[reader]].[[readRequests]] exists, which is not true for byte readers.

Untested, but I think the repro code is then something like:

```js
const rs = new ReadableStream({ type: "bytes" });
const reader = rs.getReader();
```

@tschneidereit mentions that his Gecko implementation is failing the test "ReadableStream with byte source: autoAllocateChunkSize", whereas the reference implementation for some reason is not.

---

I think the correct fix here is to bail in ReadableStreamDefaultControllerCallPullIfNeeded immediately if the reader is not a default reader. @tyoshino, does that sound right? We should also track down the missing test coverage though.

**Comment by ricea** [comment]
I found when trying to reproduce #645 that exceptions were silently getting dropped when happening in async code, even though I'd expect an "unhandled promise rejection". I have no idea why.

It's good to have coverage for these things anyway, although writing the tests can be mind-bendingly difficult. If an exception happens at the end of an async function it can be unobservable.

**Comment by domenic** [comment]
Maybe it is a problem with the tape framework in particular; I think the web platform tests are generally good at catching these sorts of things.

**Comment by isonmad** [comment]
> new ReadableStreamDefaultController

Wait, how would that happen in the first place if you're constructing a byte stream?

**Comment by domenic** [comment]
Argh, thanks @isonmad, I guess I did not understand the problem correctly... @tschneidereit thoughts?

**Comment by tschneidereit** [comment]
I'm afraid I don't understand what was going on either, anymore. I can't reproduce it and didn't save what I had that triggered this. #649 is good regardless, so I vote for closing this as invalid.

**Comment by domenic** [comment]
Sounds good; let us know if you can reproduce!

**Comment by tyoshino** [comment]
Thanks. Though it turned out it look that the repro in the OP is wrong, I checked the similar path for byte stream. https://streams.spec.whatwg.org/#readable-byte-stream-controller-should-call-pull looks ok. It's checking both reader presence and reader type.
