### ISSUE TITLE
Should pipeThrough() mark the promise from pipeTo() as handled?

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#652]
It seems really annoying that if one link in the chain fails every single pipeThrough() in the chain will complain about it.

If a transform in the middle of the pipe fails, are the separate complaints useful? I can think of two scenarios where they might be:
1. Something after the failed step in the chain has a bug which causes it to fail on abort/cancel. Then that error will be propagated, masking the real problem.
2. preventAbort is set, stopping propagation.

**Comment by domenic** [comment]
So the main concern, I think, is allowing people to catch all the errors. If they have proper error handling logic all over their program, no unhandled rejections should appear in their error telemetry. I guess that is not the case right now with pipeThrough, which is sad.

I agree that the cases you mention mean that causing the promise to be handled would potentially "lose" the error. However, I think it is OK:

1. Surfacing the developer bug seems more important. And after they fix the bug, they will be able to see the original error.
2. preventAbort is a specific signal that you do not care about this error in the usual sense; you do not want it to propagate, and thus you probably don't want it to count as unhandled. It's kind of like `catch (e) {}`.

Also note that, if people really need to inspect at runtime, they can always check `stream.getReader().closed`.

So, in general I am in favor of marking the promise as handled. Do you agree?

**Comment by ricea** [comment]
Yes. Now you put it like that, marking the promise as handled will allow preventAbort to work as intended.
