### ISSUE TITLE
Meta: Need an awesome favicon

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#654]
[streams.spec.whatwg.org](https://streams.spec.whatwg.org) has no favicon. As a result, I have it open in 6 tabs.

I would make one myself but my icon design skills are strictly less than awesome.

**Comment by domenic** [comment]
It actually does. Chrome just doesn't support svg favicons. It works great in Firefox :).

This is a general issue with all WHATWG specs, so I guess we could open something on whatwg/meta to discuss.

**Comment by ricea** [comment]
Closed in favour of https://github.com/whatwg/meta/issues/10
