### ISSUE TITLE
Is there an abstract operation for pipeTo?

### ISSUE THREAD

**Issue by yutakahirano** [whatwg/streams#658]
Do you have a plan to have an abstract operation? I want to use it from the fetch spec.

**Comment by ricea** [comment]
I like the idea. Can anyone think of a reason not to do it?

**Comment by domenic** [comment]
We should do this. It was part of my original plan but we didn't have a user at the time, so I didn't.

**Comment by domenic** [comment]
It seems like the resolution per https://github.com/whatwg/fetch/pull/458 is not to do this quite yet until we have a spec for transform streams at least. Let's close and reopen if someone else comes up with a need for it.
