### ISSUE TITLE
write.https.html test is slow with full memory checking

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#660]
Chromium has a bug related to this test, http://crbug.com/671165 due it timing out on MSAN bots. I am currently testing a change which reduces the number of iterations in the test 'a large queue of writes should be processed completely' (https://codereview.chromium.org/2644473002). In future Chromium will import the tests from the web-platform-tests so I would like to upstream this change. I don't think it makes the test less useful.

**Comment by tschneidereit** [comment]
I was about to propose a change to this, too. In optimized builds it's all fine, but in debug builds this one test takes about 15s on my machine. Reducing `numberOfWrites` to 1k or 2k would be an adequate fix, I think.

**Comment by domenic** [comment]
SGTM
