### ISSUE TITLE
Remove "Wait until any ongoing write finishes (i.e. the corresponding promises settle)." from pipeTo standard text

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#668]
Now that WritableStreamAbort will wait for any ongoing write to complete this step in the algorithm isn't necessary.

**Comment by domenic** [comment]
I don't think this is true until #715 is resolved.

**Comment by domenic** [comment]
Well, OK, re-reading #644, I guess it's not necessary. However the semantics of removing it will change after #715. So let's avoid changing this just yet because doing so with the current will generate extra tests that then just need to be rolled back after #715.

**Comment by domenic** [comment]
I think this is invalid after #726. In particular if we need to wait for chunks where we have read them but not yet started writing, we need some text to say that, like #726 introduces. I will close, but feel free to reopen if you disagree.
