### ISSUE TITLE
Assign names to the Records used in the standard

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#670]
As an implementer it is useful to be able to quickly find all the places a data structure is used in order to make decisions about how it should be structured. I had this issue even when implementing in a dynamically-typed language.

I think it would help to have names for the Records used in the standard.

For example, the record added to [[readRequests]] could be called "Read Request Record".

This doesn't completely solve the problem as Records are used in places where the fact that they are Records is not mentioned. But maybe we could rephrase things like

2. Let _readRequest_ be the first element of _reader_.[[readRequests]].

like this

2. Let _readRequest_ be the first Request Request Record from _reader_.[[readRequests]].

**Comment by domenic** [comment]
> This doesn't completely solve the problem as Records are used in places where the fact that they are Records is not mentioned. But maybe we could rephrase things like

This is still unsolved. But I guess #1048 would tackle that.
