### ISSUE TITLE
Set "Inline Github Issues bikeshed" option to appropriate value

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#674]
Already committed to master (originally in 83dbf131a5c801b1d1e6a7fad1079fe37b362ac9 squashed into c6c0a6e68a427be34f0bd1166c991f811379c32a). Please review. If it's looks good, please just close this issue. If not, please post comments there or just fix the issues.

We could use this issue for tracking the work to update the spec to utilize the new bikeshed feature.

**Comment by tyoshino** [comment]
Follow up for #655.

**Comment by domenic** [comment]
LGTM. I think maybe we should turn it off at some point since we're not using it, and in the past the feature has been problematic (e.g. since the spec does not rebuild every time you close an issue or edit its title/contents).
