### ISSUE TITLE
strategy.size() can reenter WritableStream logic before its caller finishes all the work

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#675]
Looks ReadableStream has the same issue.

The other user provided functions e.g. ones on underlyingSource/Sink which are invoked after their caller finishes all the work that touches the state variables of the streams. But in the callers of strategy.size(), there're lines that touch the state variables (both reading and writing) after strategy.size() is invoked. strategy.size() can implemented to call writer function or controller functions, and therefore reentry may happen. Should we have some guard against such a reentry?

**Comment by domenic** [comment]
In general I would say that if you do this your code is broken and we don't care to protect against it. But what we need to check is that doing so doesn't cause invariant violations that we are assuming elsewhere.

**Comment by tyoshino** [comment]
Yes, the same stance. I'm worried about possible assert hit, etc.

**Comment by isonmad** [comment]
It looks like there's no assertion failures, although the chunks get enqueued in the reverse of the order in which `enqueue()`/`write()` was called, when there are recursive calls.

```js
var c;
var strategy = {
  size(chunk) {
    if (chunk >= 1)
      c.enqueue(chunk-1);
    return chunk;
  }
};

var rs = new ReadableStream({start(controller){c = controller;}}, strategy);

c.enqueue(5);
rs.getReader().read(); // earliest enqueued chunk is 0 instead of 5
```

```js
var writer;
var strategy = {
  size(chunk) {
    if (chunk >= 1)
      writer.write(chunk-1);
    return chunk;
  }
};

var ws = new WritableStream({write(chunk) {console.log(chunk);}}, strategy);
writer = ws.getWriter();
writer.write(5);
```

**Comment by ricea** [comment]
Whatever the behaviour is, we have to write tests for it. As such, I'd prefer it if the behaviour was sane. Can we hoist the call to strategySize up to the beginning of the write() call?

**Comment by isonmad** [comment]
The only thing done before the strategySize call is `WritableStreamAddWriteRequest()` right now. Which is part of the generic writable stream logic, while the strategySize call is at the start of the `WritableStreamDefaultControllerWrite()` controller logic. It seems harmless enough?

**Comment by domenic** [comment]
"Reverse order" makes sense to me. It's in reverse order of the calls happening, but in normal order of the calls finishing. Writing tests seems like a good next step.

**Comment by ricea** [comment]
I found an assertion failure:

```javascript
promise_test(() => {
  let writer;
  const strategy = {
    size() {
      writer.close('C');
      return 1;
    }
  };

  const ws = recordingWritableStream({}, strategy);
  writer = ws.getWriter();
  return writer.write('W')
      .then(() => {
        assert_array_equals(ws.events, ['write', 'W', 'close', 'C'], 'close should happen after write');
      });
}, 'close() should be work when called from within strategy.size()');
```

I get this output with the reference implementation:

```
whatwg/streams/reference-implementation/lib/utils.js:10
      throw e;
      ^
AssertionError: queue must be empty once the final write record is dequeued
    at WritableStreamDefaultControllerProcessClose (whatwg/streams/reference-implementation/lib/writable-stream.js:854:3)
    at WritableStreamDefaultControllerAdvanceQueueIfNeeded (whatwg/streams/reference-implementation/lib/writable-stream.js:835:5)
    at WritableStreamDefaultController.Promise.resolve.then (whatwg/streams/reference-implementation/lib/writable-stream.js:712:9)
```

I expected this test to pass. I did not spot the issue when I manually inspected the standard. There are so many code paths that it is difficult to have certainty that there are no issues.

I suggest we hoist the call to strategySize to be the very first thing in WritableStreamDefaultWriterWrite, before the state checks.The state checks that are currently in `write()` should be moved into WritableStreamDefaultWriterWrite so that they can happen after the call to strategySize. This would leave no way for strategySize to put us in a bad state.

You can see the rest of my work-in-progress tests at https://github.com/ricea/web-platform-tests/blob/9380b44bf34132e145be508d7a0847781e3b7a62/streams/writable-streams/reentrant-strategy.js.

**Comment by ricea** [comment]
My proposed fix is at https://github.com/whatwg/streams/pull/680. PTAL.

If it looks okay, I will write the standard text changes.

**Comment by ricea** [comment]
This is done, just not yet landed.

Waiting for https://github.com/w3c/web-platform-tests/pull/4830 to land before updating the web-platform-tests submodule and landing #680.
