### ISSUE TITLE
WebIDL syntax for parameterized streams?

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#678]
For the encoding spec, I'd like to be able to write `ReadableStream<USVString>` to indicate a readable that vends string chunks, and `WritableStream<BufferSource>` to indicate a writable that accepts chunks consisting of [buffers of data](https://www.w3.org/TR/WebIDL-1/#es-buffer-source-types).

But this doesn't work. Should it?

**Comment by domenic** [comment]
In general right now even just plain `ReadableStream` is not valid IDL, since it is not an IDL type.

Why do you want to do this? Just documentation, or would you envision it helping bindings generators or generating spec code in some way?

**Comment by ricea** [comment]
I was thinking in terms of documentation. I hadn't thought about whether bindings generators would consume it. Blink is using type "any" in Response.idl.

**Comment by ricea** [comment]
Parameterized WritableStream is a bit weird, since my understanding is that IDL always throws on type conversion errors, but writer.write() never throws. Maybe it's a bad idea.

When using some kind of type-checked Javascript, it's obviously beneficial if the types are as specific as possible, and the easiest way to encourage that is to call out the types specifically in the standard. But maybe IDL is not the best way to do that.

**Comment by annevk** [comment]
We should only use types in IDL if it helps codegen (including JIT codegen, which is why we annotate guaranteed return types).

**Comment by ricea** [comment]
I think we have agreement this is not needed.
