### ISSUE TITLE
Export the "error the stream" concept?

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#679]
For the Encoding Standard, it would be useful to be able to talk about erroring the stream. However, while the Streams Standard uses the term in the few places, it doesn't explicitly define it.

**Comment by domenic** [comment]
This seems like part of #372. Right now Fetch does all the work for this: https://fetch.spec.whatwg.org/#readablestream

**Comment by ricea** [comment]
It would be nice to have a description of the concept from the developer's perspective, too.

**Comment by domenic** [comment]
This exists now.
