### ISSUE TITLE
Are abstract operations supposed to be in alphabetical order?

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#684]
It seems like most of the abstract operations are in alphabetical order within a section, but some are not. Is there a rule here, or is it a case-by-case thing?

https://streams.spec.whatwg.org/commit-snapshots/c9d7b9de530506d42034b74f5f875a1b49b45507#contents

> 3\.9\.4 ReadableStreamDefaultControllerClose \( controller \)

**Comment by domenic** [comment]
They are indeed supposed to be, but without machine-enforcement, it hasn't always been maintained.
