### ISSUE TITLE
Add identifier highlighting similar to the ES spec

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#687]
E.g. in https://tc39.github.io/ecma262/#sec-number-constructor-number-value, if you click _value_, _n_, or _o_, it highlights all other instances of the same value.

We can prototype this here in streams and then possibly consider expanding it to other WHATWG specs.

**Comment by ricea** [comment]
This is a great feature. Both for following the logic through the spec and doing implementations it is very helpful to be able to see at a glance where a variable is used.

I have a slight nitpick with the way it's implemented in the ES spec: highlighting is additive. I would rather it replaced the highlight when you clicked on a new identifier, or at least used a different colour.

Something that worries me is that Bikeshed and the emu-alg sections have separate notions of the set of identifiers. This currently only manifests itself by Bikeshed whining about unused identifiers during compilation, but it becomes more critical when the relationship between identifiers is exposed in the text.
