### ISSUE TITLE
How much latitude should implementations have in looking up transformer.transform()?

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#691]
Pull request #689 verifies that transformer.transform is looked up in exactly the same way as the reference implementation. But this puts pretty severe restrictions on possible optimisations. For example, `new TransformStream()` can be optimised to skip Javascript altogether, but `new TransformStream({})` cannot. Here are some use cases for a TransformStream with no transform() method:

1. A TransformStream which adds extra buffering to a pipe.
2. A TransformStream which adds a header and/or footer to the stream but does nothing else.

I see two ways we could permit optimisation here:
1. Make the standard ambiguous about when (and how?) the "transform" attribute of transformer is looked up.
2. Change the reference implementation (and hence the standard) to look up the "transform" attribute in the constructor only.

I think for developers 2. is better than 1. because it will at least be consistent between implementations even if it's different from the way sources and sinks work.

The semantics we provide for sources and sinks are that we treat them exactly like an object, including expected Javascript behaviours like dynamically changing prototypes.

My feeling is that complying with this expectation is important, even though only a tiny proportion of developers may take advantage of the flexibility. On the other hand, falling off a performance cliff because you wrote `new TransformStream({})` instead of `new TransformStream()` is suboptimal. Making identity transforms always be slower just to avoid surprising performance behaviour would also be bad.

Thoughts?

**Comment by tschneidereit** [comment]
I agree that we shouldn't require implementations to do a double lookup for
`transformer.transform`. Retaining the ability to easily perform stream
transforms without JS involvement is important.

I also agree that your proposed change 2) is better. Yes, it'd be different
from the source and sink handling, but it'd be in a very obvious way. That
is, as soon as you tried changing the transformer's `transform` method (be
it through a straight property set or a prototype change), you'd realize
that it doesn't have an effect.

Additionally, there isn't really a loss of flexibility: you can always e.g.
have the `transform` method forward to another function that's under your
control, or check a flag on the receiver.

**Comment by domenic** [comment]
I'm loathe to make the constructor design inconsistent between the three classes. On the other hand, it seems like a low-risk change to cache all the methods on all the constructors, so if this is important, I think we should do that.

It's a bit weird from a JS perspective IMO. If we're treating these things as methods, the usual syntax for method calling is `foo.bar()`, not `previouslySavedBar.call(foo)`. But few people will notice.

We don't want to go back to just treating them as functions, as that breaks cases like https://streams.spec.whatwg.org/#example-both.

It would bloat the size of each object a decent bit, e.g. ReadableStreamDefaultController would end up with three more internal slots to store start, pull, and cancel.

BTW I think the way you've stated this as a performance cliff between `new TransformStream()` and `new TransformStream({})` is not emphasizing the right thing. That's a very theoretical performance cliff. But the cliff is a real problem for the more realistic use cases you cite. Just a phrasing thing :).

**Comment by tschneidereit** [comment]
>
> I'm loathe to make the constructor design inconsistent between the three
> classes. On the other hand, it seems like a low-risk change to cache all
> the methods on all the constructors, so if this is important, I think we
> should do that.
>
That seems fine to me, too.

> It's a bit weird from a JS perspective IMO. If we're treating these things
> as methods, the usual syntax for method calling is foo.bar(), not
> previouslySavedBar.call(foo). But few people will notice.
>
It should be clear in the spec, perhaps including in examples, for sure.
Other than that, I think the few people who'd even notice would just apply
one of the trivial workarounds and move on. There really isn't a realistic
way for them to be affected without noticing, I think.

> We don't want to go back to just treating them as functions, as that
> breaks cases like https://streams.spec.whatwg.org/#example-both.
>
Fully agreed, calling them with the original object as the receiver makes
sense.

> It would bloat the size of each object a decent bit, e.g.
> ReadableStreamDefaultController would end up with three more internal
> slots to store start, pull, and cancel.
>
We'd only need to store `pull` and `cancel`, right? `start` is invoked in
the constructor and not needed after that, IINM. I agree that this is
unfortunate, but think it's worth it for the added optimization potential.

**Comment by domenic** [comment]
Good point about not needing to store `start()`; you're right.

**Comment by ricea** [comment]
I feel conflicted about this. An important feature of Streams is being able to plug together standard-shaped pieces and have them work together in a predictable way. If the objects passed to Stream constructors behave differently from Javascript objects in other contexts then we're going against our own design philosophy.

Strawman scenario: some future framework uses bytecode for everything on first load to avoid JS compilation overhead. After first load it lazily loads the real Javascript and dynamically swaps all the bytecode functions for the optimizable Javascript versions. Eventually some users of this framework notice that Stream performance is bad and the fact that byte-coding needs to be disabled for sink/source/transformer methods is independently rediscovered several times before finally making it into the documentation.

My intuition tells me that optimising for undefined transform() is important, but my intuition about optimisation has been wrong before.

**Comment by ricea** [comment]
Alternative proposal: scrap the transform() fallback and add an explicit `identity: true` attribute. Transformers can either define a transform() method or set `identity: true`, but cannot do both (or neither). Like the `type` attribute on a source, `identity` is only checked in the constructor and changing it afterwards does nothing.

**Comment by domenic** [comment]
> If the objects passed to Stream constructors behave differently from Javascript objects in other contexts then we're going against our own design philosophy.

I guess I'm not as conflicted because even though they behave differently, it's really not a big deal in practice. I've never really seen JavaScript code that dynamically changes the methods of an object passed elsewhere and expects that to be respected---even though it's probably the case that doing so would work, since most object-accepting code will use `foo.bar()` instead of `previouslySavedBar.call(foo)`.

Oh, and also, we use the same pattern for custom elements. Here was the thread with arguments for it at that time: https://github.com/w3c/webcomponents/issues/417

**Comment by tschneidereit** [comment]
> Oh, and also, we use the same pattern for custom elements. Here was the thread with arguments for it at that time: w3c/webcomponents#417

That's a good discussion of the up- and downsides to this, thanks. I don't know if the same is true for custom elements, though I'd assume so, but as I said above the important part for me is that having this check be required would necessitate entering the JS engine in *some* fashion, even if it doesn't necessarily entail running JS code itself. (Though recommending developers freeze the object or make the `transform` property non-configurable would also work.)

**Comment by ricea** [comment]
> Oh, and also, we use the same pattern for custom elements. Here was the thread with arguments for it at that time: w3c/webcomponents#417

I didn't know that custom elements was doing this. That negates my concerns. Thank you.

Mark me in favour of "cache method pointers at construction time for ReadableStream, TransformStream and WritableStream". Because this makes no difference in the vast majority of cases, I have no interoperability concerns about changing existing behaviour.

**Comment by ricea** [comment]
I think we should go directly to #813 (algorithm steps in slots) without doing the method-copying thing as an intermediate step.

**Comment by domenic** [comment]
Oh, wow, I didn't realize they solved the same problem. Good point. I'll set aside my half-done branch that does method copying and switch to working on algorithms in slots.

**Comment by ricea** [comment]
Yes, I plan to do this soon, probably tomorrow. Aside from providing optimisation opportunities I expect it will be a good simplification for TransformStream.

**Comment by ricea** [comment]
WIP at https://github.com/whatwg/streams/pull/860. The test changes https://github.com/w3c/web-platform-tests/pull/8519 are unexpectedly nice. There are less edge cases. Even though the new semantics are more unusual than the old ones, subjectively they seem less weird.

Sadly no TransformStream tests failed due to the change. I have a separate work in progress to fix that :-)
