### ISSUE TITLE
Decide whether or not to merge inFlightCloseRequest and closeRequest

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#692]
From https://github.com/whatwg/streams/pull/672#discussion_r104858805

**Comment by domenic** [comment]
Personally I think it is good as-is with the note in the spec. Feel free to close if you agree.

**Comment by tyoshino** [comment]
Thanks. Maybe @ricea's point in the comment has been addressed by the note added in response to domenic's suggestion at https://github.com/whatwg/streams/pull/672#discussion_r105001386.

Closing
