### ISSUE TITLE
Merge WritableStream tests from close-then-abort branch

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#694]
Merge useful tests from domenic's close-then-abort branch https://github.com/whatwg/streams/commit/33773df16229cdc99147b4d5ad29a0493fe6c41a#diff-4c7e8a1ce50d6c68c3d24df6461fcfd6

See also https://github.com/whatwg/streams/pull/672#issuecomment-285693724

**Comment by tyoshino** [comment]
https://github.com/whatwg/streams/pull/672#issuecomment-285693724

> We don't follow the expectation in the `Closing but then immediately aborting a WritableStream results in a successful close and a fulfilled abort()` test.

@domenic, do you want to choose this behavior? Or are you fine with keeping not yet in-flight close() abort()-able?

**Comment by domenic** [comment]
I am fine with keeping not yet in-flight close() abort()-able, as long as we have tests for it :). Maybe we already do.

**Comment by tyoshino** [comment]
OK. Thanks for confirming!
