### ISSUE TITLE
Editorial: make close() return this.[[closedPromise]]

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#724]
When re-reading the writable streams section I noticed the statement in one of the examples:

> In the previous example we only paid attention to the success or failure of the entire stream, by looking at the promise returned by its close() method. That promise **(which can also be accessed using the closed getter)**

I wanted to make sure the bolded part was still true. This was not obviously the case from the spec (although it is true if you trace things through). I think it could be made more obvious by making the close() method return stream.[[closedPromise]], and thus making WritableStreamDefaultWriterClose return nothing.

**Comment by domenic** [comment]
Actually, they are not the same promise, and haven't been for a while. Fixing the non-normative text in #725.

**Comment by tyoshino** [comment]
See the history at these comment
https://github.com/whatwg/streams/pull/721#issuecomment-291809255

https://github.com/whatwg/streams/commit/5a2753464bd6e34e3bc7a57fcaac24ea5153fbb6 has separated them.

**Comment by ricea** [comment]
I realised there's now an additional reason why they have to be different promises--we mark writer.closed as handled because it's a "state promise". close() and other method promises we don't mark as handled so that errors are noticed.
