### ISSUE TITLE
new ReadableStream({type: 'bytes'}, new CountQueuingStrategy({highWaterMark: 5})) is weird

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#729]
If you see CountQueuingStrategy when constructing a ReadableStream, you might expect it to be setting the queue size in chunks. But if `type` is `"bytes"`, it sets the queue size in bytes instead.

I was discussing this with @domenic and we concluded that new ReadableStream() should probably throw if the strategy passed to a byte stream has a size function.

**Comment by TejasQ** [comment]
Definitely could use this!
