### ISSUE TITLE
pipeTo() text appears to say all queued writable chunks must be written on readable error

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#738]
https://streams.spec.whatwg.org/commit-snapshots/037ec544adc7a7677ada2ba140849fb5549b09fd#rs-pipeTo-shutdown-with-action

> If any chunks have been read but not yet written, write them to dest\.
> Wait until every chunk that has been read has been written

It appears to me that this requires all queued chunks to be written when the ReadableStream becomes errored. This is not what the reference implementation actually implements, and I am not sure it is desirable.

https://github.com/w3c/web-platform-tests/pull/5636 contains a test which illustrates the behaviour that I think the standard text is requiring.

**Comment by domenic** [comment]
Hmm. This seems correct to me. In particular if the destination is not errored, and we have data we got from the readable stream before it died, we should be doing our best to get it into the destination, instead of throwing it away. I reviewed the test and it seems correct.

What would you expect, and what makes you think this might not be desirable?

**Comment by ricea** [comment]
I can see two opposing viewpoints here:
1. The source is broken, we have failed, we should stop as soon as it is safe to do so.
2. The source is broken, we should save as much data as we can.

I can only think of one precedent for this at the moment. In Windows socket code, if the connection is reset, any data that has not yet been read by the application is discarded. On Unix, the application can still read all remaining data. The Unix behaviour is generally considered more useful among people who write cross-platform socket code.

However there is a difference in that even on Unix the application can choose to discard that data. With pipeTo applications are stuck with whichever behaviour we choose.

I am leaning towards 2. as it minimises the risk of data loss.
