### ISSUE TITLE
"2.4. Pipe Chains and Backpressure"

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#740]
https://streams.spec.whatwg.org/commit-snapshots/3193db4f3fa34c52d726055ab99a623f66c4a623#pipe-chains

> 2\.4\. Pipe Chains and Backpressure

Maybe this section should explain more clearly how backpressure manifests itself in the API?

Based on https://github.com/w3ctag/design-reviews/issues/163#issuecomment-297907517 by @dbaron.

**Comment by domenic** [comment]
In general I feel like the model section needs to be redone to talk about the API more. It was originally written when we thought we'd duck-type everything.
