### ISSUE TITLE
"At this point in time the division of work betw..."

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#741]
https://streams.spec.whatwg.org/commit-snapshots/3193db4f3fa34c52d726055ab99a623f66c4a623#ws-abstract-ops-used-by-controllers

> At this point in time the division of work between the stream and its controller may seems somewhat arbitrary, but centralizing much of the logic in the controller is a useful structure for the future\.

This sentence is maybe overly ambiguous? I feel we've actually been quite careful in designing this to enable byte streams, but that doesn't come across at all.

Based on https://github.com/w3ctag/design-reviews/issues/163#issuecomment-297909069 by @dbaron.

**Comment by tyoshino** [comment]
Shall we just note concretely that this is for extending WS for a byte stream variant?
