### ISSUE TITLE
Define generic operation for GetDesiredSize?

### ISSUE THREAD

**Issue by rombel** [whatwg/streams#745]
In current version of the spec, ReadableStreamDefaultControllerGetDesiredSize and ReadableByteStreamControllerGetDesiredSize describe exactly the same process (this is because queueTotalSize is now used for both controllers). Wouldn't it be possible to define a single ReadableStreamControllerGenericGetDesiredSize, similarly to what is done for some reader operations?

**Comment by tyoshino** [comment]
Yeah, sounds fine.

https://streams.spec.whatwg.org/#readable-byte-stream-controller-get-desired-size
https://streams.spec.whatwg.org/#readable-stream-default-controller-get-desired-size

**Comment by domenic** [comment]
Now that we're linking the internal slots, this seems less good.
