### ISSUE TITLE
RFC: Review pipes.js (a Highland.js inspired utility library for web streams)

### ISSUE THREAD

**Issue by creatorrr** [whatwg/streams#748]
Hey folks!

Thank you for the amazing work on the standard. I have been following the progress for a while now and even using the reference implementation in side projects. 

In the process, I started writing [pipes.js](http://pipes.js.org), a Highland.js inspired utility library for web streams.

It'd be great if I could get comments and suggestions on the same. There're more modules in the works than currently displayed. I'm happy to elaborate on any design decisions. 

Cc- @neovov @kentonv @domenic @tyoshino

**Comment by ricea** [comment]
This is great. Utilities like this are important to drive adoption. They can also help guide future evolution of the standard.

I haven't looked at the implementation yet. I want to do that, but it may be a few weeks before I get time.

You could update the docs to note that ReadableStream and WritableStream are considered stable now. A new stable release of Chrome should come out any day now with WritableStream enabled by default.

**Comment by creatorrr** [comment]
Thanks for taking a look and the heads up on the docs update, @ricea ! Please do let me know your thoughts once you get a chance to take a deeper look. Would love to hear what you think. :)
