### ISSUE TITLE
Why does call to pipeThrough throw Uncaught TypeError: Cannot convert undefined or null to object?

### ISSUE THREAD

**Issue by guest271314** [whatwg/streams#754]
According to [Chrome Platform Status Streams API: piping Network / Connectivity](https://www.chromestatus.com/feature/6067348976959488) `.pipeTo()` is defined at Chrome 59.

The specification describes the pattern as 

> [3.2.4.4. `pipeThrough({ writable, readable }, options)`](https://streams.spec.whatwg.org/#rs-pipe-through)

At an [example](https://github.com/whatwg/streams/blob/a78e1ae670c68d4d80b2ffa10c85c25eaa82bf37/demos/streaming-element-backpressure.html) within the repository the code used is 

```
  await response.body
      .pipeThrough(new TextDecoder())
```

Tried code below at `console` at Chromium 59 while attempting to gather the concept and appropriate pattern and expected parameters for `.pipeThrough()`

```
let n = 0;
let text = "a";

let readableStream = new ReadableStream({
  pull(c) {
    if (++n < 10) c.enqueue(text)
    else c.close();
  }
});

readableStream
.pipeThrough(new TextEncoder())
.pipeTo(new WritableStream({
  write(chunk) {
    console.log("Chunk received", chunk);
  },
  close() {
    console.log("All data successfully read!");
  },
  abort(e) {
    console.error("Something went wrong!", e);
  }
}))
```
which logged 

```
Uncaught TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
```

Downloaded repository and tried the same code at `console` at above linked example `document`, which logged expected result.

Questions:

1) Why does Chromium 59 throw a `TypeError` though `.pipeThrough()` is defined at `ReadableStream` object?

2) What is the proper parameter pattern expected by `.pipeThrough()`? For example, does `ReadableStream().pipeThrough(new WritableStream(), new ReadableStream())` reflect the expected parameters passed to the function?

3) Is `/streams-master/demos/transforms/transform-stream-polyfill.js` which is loaded at the example currently necessary to use `.pipeThrough()` at Chromium browser?

**Comment by lifaon74** [comment]
Seems legit behavior. `pipeThrough` expect an object with `writable` and `readable` properties, but `TextDecoder` doesn't have any of them, so it can't work. I guess the example proposes a future improvement of TextDecoder to support streams.
Chrome is not totally up-to-date with the specs (because it is not finalized yet), you should use the [implementation](https://github.com/whatwg/streams/tree/master/reference-implementation/lib).

**Comment by ricea** [comment]
The use of TextDecoder in `pipeThrough()` is just a proposed change to the standard. It hasn't been formally reviewed and no browser implements it natively. There is a prollyfill (a polyfill for the proposed change) at https://github.com/GoogleChrome/text-encode-transform-prollyfill which is what the demo uses.

I'm thinking of including a comment in the example code to clarify that this is only proposed usage. What do you think?

> Why does Chromium 59 throw a TypeError though .pipeThrough() is defined at ReadableStream object?

It's actually complaining about `writable` not being a WritableStream object. The exception description could be better.

> What is the proper parameter pattern expected by .pipeThrough()? For example, does ReadableStream().pipeThrough(new WritableStream(), new ReadableStream()) reflect the expected parameters passed to the function?

It expects an object with `readable` and `writable` properties. So

```
new ReadableStream().pipeThrough(
  {writable: new WritableStream(), 
   readable: new ReadableStream()});
```

would be correct syntax.

> Is /streams-master/demos/transforms/transform-stream-polyfill.js which is loaded at the example currently necessary to use .pipeThrough() at Chromium browser?

Yes. There's some more standardisation work to be done before TransformStream will be ready: https://streams.spec.whatwg.org/#ts. If you'd like to help with the standardisation work you could take a look at some of our outstanding issues: https://github.com/whatwg/streams/issues?q=is%3Aissue+is%3Aopen+label%3A%22transform+streams%22

Issues with Chrome's implementation of the standard should be filed on Chrome's bug tracker at https://crbug.com. To briefly summarise the status: ReadableStream has some deviations from the current version of the standard. The largest one is that `type: 'bytes'` passed to the constructor doesn't work. The `pipeTo()` and `pipeThrough()` implementation is up to date, however. There are no known deviations of Chrome's WritableStream from the standard.

**Comment by ricea** [comment]
I fixed the bug in Chrome that caused this error: https://bugs.chromium.org/p/chromium/issues/detail?id=747772 and also changed pipeThrough to throw a more helpful exception: https://bugs.chromium.org/p/chromium/issues/detail?id=751241.

**Comment by guest271314** [comment]
@ricea How to get to the `readable` portion of the `.pipeThrough()` method? http://plnkr.co/edit/RRdcVfRlh8LecLmQqpJU?p=preview
