### ISSUE TITLE
Reading last chunk from StreamReader

### ISSUE THREAD

**Issue by DanielBaulig** [whatwg/streams#760]
If a StreamReader knows that any given chunk is the last chunk in the stream, is it acceptable for the StreamReader to resolve the read Promise with `{ value: lastChunk, done: true }`? The specified default reader implementation does not seem to do that and I was wondering if there's any specific reason for that?

https://streams.spec.whatwg.org/#default-reader-read

**Comment by domenic** [comment]
No; as for why, it's mostly to match the JavaScript iteration protocol.

**Comment by DanielBaulig** [comment]
Thanks!
