### ISSUE TITLE
TransformStream does not propagate the argument passed to cancel

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#768]
I just want to check that this is the expected behaviour.

```javascript
const ts = new TransformStream();
const closedPromise = ts.writable.getWriter().closed;
ts.readable.cancel(new Error('hay'));
closedPromise.catch(e => console.log(e.message));  // logs 'Readable side canceled'
```

**Comment by domenic** [comment]
I think the OP's behavior is better than that in #771. I guess it is the difference between saying "canceling the readable side aborts the writable side" vs. "canceling the readable side transmits the cancelation back to cause the writable side to become errored in that way". The latter makes a bit more sense to me.

**Comment by ricea** [comment]
pipeTo() propagates [[storedError]] from the readable to the writable, so I think it is consistent that TransformStream do the same.
