### ISSUE TITLE
Make the abstract shorter

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#769]
Looking at https://spec.whatwg.org/, we're a clear outlier. It should probably just be

> The Streams Standard provides APIs for creating, composing, and consuming streams of data.

or maybe

> The Streams Standard provides APIs for creating, composing, and consuming streams of data that map efficiently to low-level I/O primitives, and allow easy composition with built-in backpressure and queuing.

Need to update it here and there.

The rest can go in the introduction section.

**Comment by guest271314** [comment]
The first option appears to be adequate.
