### ISSUE TITLE
What should the behaviour of controller.close() be?

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#774]
I think the following test should pass:

```javascript
promise_test(t => {
  const ts = recordingIdentityTransformStream();
  const rs = new ReadableStream({
    start(controller) {
      controller.enqueue(0);
      controller.enqueue(1);
      controller.enqueue(2);
      controller.close();
    }
  });
  const pipeToPromise = rs.pipeTo(ts.writable);
  return delay(0).then(() => {
    assert_array_equals(ts.events, ['transform', 0], 'transform() should have seen one chunk');
    ts.controller.close();
    return promise_rejects(t, new TypeError(), pipeToPromise, 'enqueuing the second chunk should fail');
  }).then(() => {
    assert_array_equals(ts.events, ['transform', 0, 'transform', 1], 'transform() should have seen two chunks');
  });
}, 'closing readable should permit remaining chunks to be processed');
```

Currently `pipeToPromise` never becomes settled because the second chunk is never written.

I think this should work. Having a method which blocks the pipe permanently if you call it when there is backpressure doesn't seem very useful to me.

**Comment by domenic** [comment]
If you'll indulge me, I'm kind of unclear on the semantics of a transform controller's close().

I guess the situation is when you want to discard any further incoming data. You're signaling that everything you've seen so far is enough, and now you're successfully done. E.g. you could imagine a findFirstPrime transformer: [1, 4, 6, 9, 7, 10, 2] (length = 7) -> [false, false, false, false, true] (length = 5).

In that scenario do we say that attempting to transform the 10 is a failure? Probably, just like attempting to write to any other closed writable stream is a failure. OK, that makes sense. But the readable side never gets marked as errored, right?

In this situation you have [0, 1, 2] -> [0]. Do we count the pipe as failed, or succeeded? Your test indicates failed, which I guess is pretty baked in to the semantics of pipeTo: if the writable side errors, everything blows up. But it seems like disallowing early-quitting in this way is a bit bad.

**Comment by ricea** [comment]
> If you'll indulge me, I'm kind of unclear on the semantics of a transform controller's close().

Me too.

What I'm imagining is that you already have code to discard chunks you aren't interested in. For example:

```javascript
new TransformStream({
  start() {
    this.sawPrime = false;
  },
  transform(chunk, controller) {
    if (this.sawPrime) {
      return;
    }
    controller.enqueue(chunk);
    if (isPrime(chunk)) {
      controller.close();
      this.sawPrime = true;
    }
  }
});
```

In this case `controller.close()` is mostly just an optimisation which allows downstream consumers to complete sooner. However, it makes an important semantic difference when the data source is infinite.

An alternative is that `controller.close()` also tells the TransformStream not to call `transform()` or `flush()` any more. I resisted this idea because it seems too "magical", but on second thought it follows naturally from backpressure being relieved.

**Comment by domenic** [comment]
So under that proposal, does data keeps getting pulled from `rs`, but thrown away? Or do we close `ts.writable`, thus causing `rs` to be canceled and the `pipeTo()` promise to be rejected?

I guess the latter is probably better.

The `pipeTo()` promise being rejected seems a little unfortunate, but anything else would not be very consistent with `pipeTo()`'s normal behavior, I think.

**Comment by ricea** [comment]
I think `controller.close()` would be a strange name for "close the downstream side of the pipe, but error the upstream side".

I think "close the downstream, discard the upstream" is a more useful operation. Although I've realised that the current behaviour actually gives authors the most flexibility. For example, if they have a transformer with a side-effect of generating a hash of all the input data[1], it wouldn't work if we stopped calling `transform()`.

I'd like to get rid of `controller.close()` altogether, but I think it is necessary functionality for potentially infinite inputs.

[1] I don't think transforms with side-effects are a good idea in general. It would be better to tee to a separate WritableStream that does the calculation. But there's definitely demand for transforms with side-effects, and people are going to write them.

**Comment by ricea** [comment]
I've realised you can't reliably perform the "close the downstream, error the upstream behaviour" with the current API. `controller.close(); controller.error();` is equivalent to `controller.error()` if the readable queue is non-empty. The queued data will be discarded. I suppose you could poll `controller.desiredSize` until it is equal to highWaterMark and then call `controller.error()`. This seems bad.

I've also become less convinced by my earlier argument that you should be able to keep receiving new chunks after calling `controller.close()`. I now think that `close()` meaning "I am done with transforming" makes more sense.

I also don't think "close and discard" is sensible any more. If the source is infinite then continuing to read it at full speed seems like a bad idea.

So I've come around to "close and abort" semantics. I don't know if we should change the name to `closeAndAbort()` for clarity, or stick with `close()` to avoid being ugly. `closeReadableAndAbortWritable()` would be the ultimate in clarity, but I don't think anyone would want to type that.

**Comment by domenic** [comment]
I think I like abortAndClose() (or errorAndClose()?), since conceptually I think of aborting the incoming writes before I close off the out going reads. Just close() gives a false sense of simplicitly. This is a somewhat unusual operation, which most people will not call.

**Comment by ricea** [comment]
I prefer the word "abort" here, because "error" implies something has gone wrong, but actually we're just done transforming. Upstream sources get rejections, but this is similar to what happens in a Unix pipe when something in the middle decides it is done.

I have a slight preference for closeAndAbort() because it accentuates the positive aspect that we've finished with our work. Although the operations are effectively simultaneous, I feel like the close() takes priority so that the abort() doesn't end up erroring both sides.

**Comment by domenic** [comment]
My thinking for error over abort was that abort was something the producer does to the writable side, whereas erroring is something the stream's internals do to signal to the outside world.

Maybe we need a new word entirely, like shutdown()?

**Comment by ricea** [comment]
Your logic on error vs. abort makes sense.

shutdown() means something else in socket APIs. I'd like to avoid it for that reason. I'm wondering about just `controller.done()`. A problem is that it is such an attractive-sounding operation that people might get the impression that it is the correct way to finish off any transformation.

**Comment by domenic** [comment]
http://www.thesaurus.com/browse/shut%20down

cease? halt? stop? desist? terminate?

I agree done() is a bit too attractive.

**Comment by ricea** [comment]
I like terminate(). It's both descriptive and threatening. People won't be quite sure what it does, but that's not necessarily a bad thing. stop() is a great name, but again it has the issue that people might get into the mindset that it is something they should always be calling.

Another option I was considering is exit(), by analogy with how a process in a Unix pipe would perform this operation, but I think it is just too confusing on the web.
