### ISSUE TITLE
Normative requirements for constructor names?

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#775]
Is `WritableStream.name` required to return "WritableStream"?

Is `new WritableStream().getWriter().constructor.name` required to return "WritableStreamDefaultWriter"?

**Comment by domenic** [comment]
Yes: https://tc39.github.io/ecma262/#sec-ecmascript-standard-built-in-objects

> Every built-in function object, including constructors, that is not identified as an anonymous function has a name property whose value is a String. Unless otherwise specified, this value is the name that is given to the function in this specification. For functions that are specified as properties of objects, the name value is the property name string used to access the function. Functions that are specified as get or set accessor functions of built-in properties have "get " or "set " prepended to the property name string. The value of the name property is explicitly specified for each built-in functions whose property key is a Symbol value.

plus https://streams.spec.whatwg.org/#conventions , which admittedly doesn't say exactly which ES clauses it's meant to cover.

**Comment by ricea** [comment]
Thanks. I will add test(s).

**Comment by ricea** [comment]
PR: https://github.com/w3c/web-platform-tests/pull/7035
