### ISSUE TITLE
Branch snapshot missing for algorithm-slots branch

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#858]
#857 links to https://streams.spec.whatwg.org/branch-snapshots/algorithm-slots/ which I think is the correct URL, but it returns a 404.

**Comment by domenic** [comment]
This appears to be a general problem with the new deploy script. /cc @annevk @foolip. E.g. https://github.com/whatwg/dom/pull/535 also illustrates this problem.

I think the reasoning for removing branch snapshots from the deploy script was that we would use pr-preview instead? /cc @tobie. I'm not sure how to configure pr-preview to not use branch-snapshots. Or maybe this is just a bug in the new deploy script?

**Comment by annevk** [comment]
I don't think we planned on removing branch snapshots at all. The only thing I remember is that we all acknowledged they're not guaranteed to be stable as branch names can get reused.

**Comment by domenic** [comment]
Hmm, you're right, I misremembered. [The code is still there](https://github.com/whatwg/whatwg.org/blob/f7a1bfb8ad9534838a6861b3f9ef7d65a7da3a79/resources.whatwg.org/build/deploy.sh#L85). I'll try to dig in further...

**Comment by foolip** [comment]
Looks like https://travis-ci.org/whatwg/streams/builds/303587310 failed, isn't that the explanation?

**Comment by domenic** [comment]
Ah, right, that makes sense. Then the only issue is that pr-preview links even when builds fail, but I'm not sure that's worth worrying about.

**Comment by tobie** [comment]
> I'm not sure how to configure pr-preview to not use branch-snapshots.

So branch-snapshot usage is special-cased for WHAT WG specs. It's hard-coded, so there's no config options on a per repo basis.

> Ah, right, that makes sense. Then the only issue is that pr-preview links even when builds fail, but I'm not sure that's worth worrying about.

I'll be working on adding support to PR-Preview for the HTML spec shortly. I'll see if this issue can be improve while I'm at it.

**Comment by tobie** [comment]
For info, it's special-cased in the views: https://github.com/tobie/pr-preview/blob/763ed515358f971abd9abbd7f743a4dc56e1bcf9/lib/views/body.js#L56-L62. Which makes it a bit more complicated to check if it has built correctly. There are also race-conditions involved, so fixing this might be pretty difficult.

A better strategy might be to have pr-preview upload the files it creates to a WHAT WG controlled S3 bucket setup as snapshots.whatwg.org (or similar).

**Comment by domenic** [comment]
I'm leaning toward "everything's working fine and streams just needs to fix its build" currently :)

**Comment by annevk** [comment]
See https://github.com/whatwg/meta/issues/52 about getting rid of `branch-snapshots/` in favor of letting PR Preview manage that always.

**Comment by ricea** [comment]
Closing as it appears WAI.
