### ISSUE TITLE
Export interface definitions

### ISSUE THREAD

**Issue by TimothyGu** [whatwg/streams#861]
This may have been filed in an issue here, but I couldn't find it, so sorry for any inconvenience. While the few helper methods Fetch Standard has are probably fine, having a [definition for `ReadableStream`](https://fetch.spec.whatwg.org/#concept-readablestream) in there is certainly odd.

**Comment by domenic** [comment]
Per https://tabatkins.github.io/bikeshed/#dfn-export they're already exported. Ideally Fetch should delegate here, but I think @annevk wants https://github.com/heycam/webidl/issues/445 solved first?

This is also related to https://github.com/whatwg/streams/issues/372

**Comment by annevk** [comment]
Yeah, Fetch needs the IDL representation of a ReadableStream object.

**Comment by TimothyGu** [comment]
Okay. Seems like this topic is covered in other issues already. Let's close this for now.
