### ISSUE TITLE
rethrowAssertionErrorRejection is broken

### ISSUE THREAD

**Issue by MattiasBuelens** [whatwg/streams#865]
84c584c replaced the default Node `assert` with the `better-assert` module, in order to resolve #807. However, this refactoring accidentally broke the `rethrowAssertionErrorRejection` helper, since [it uses `assert.AssertionError`](https://github.com/whatwg/streams/blob/a480a4fd23c1e3f0cea94cbbdf224f352ae60ab2/reference-implementation/lib/utils.js#L8).

While `assert` does indeed export an `AssertionError` class, `better-assert` does not. Therefore, `assert.AssertionError` is `undefined`, and `e.constructor === assert.AssertionError` always evaluates to `false`. As such, the helper never re-throws an assertion error.

One possibility would be to use `require('assert').AssertionError`, but this assumes `better-assert` will never introduce a different error class. If necessary, we could detect the error class with something like:
```js
const AssertionError = (() => {
  try {
    assert(false);
  } catch (e) {
    return e.constructor;
  }
})();
```
But maybe let's not go *that* far. 😛 

Thoughts? I can make a quick PR to use `require('assert').AssertionError` again.

**Comment by ricea** [comment]
I think the `require('assert').AssertionError` approach makes sense. It's simple and shouldn't break anything. Maybe we should use an `instanceof` check instead of strict equality in case `better-assert` decides to subclass AssertionError in future?

**Comment by domenic** [comment]
@MattiasBuelens are you still interested in working on a PR for this?

**Comment by MattiasBuelens** [comment]
@domenic Oh right, I forgot about this one. Sure, I'll send a PR (hopefully) later today.
