### ISSUE TITLE
Investigate (F)RP literature

### ISSUE THREAD

**Issue by steveklabnik** [whatwg/streams#88]
Breifly discussed this with @domenic last night, but I see many parallels to this proposal and functional reactive programming. There may be lessons to be learned from that literature or JavaScript implementations of it (bacon.js, Rx).

I'm interested in doing some of this, as I've written an FRP implementation in Ruby. I need to dig into the details of the spec first.

**Comment by domenic** [comment]
As this spec becomes more constrained by the need to efficiently wrap byte sources and sinks while still presenting a general interface, it's clearer that it's best for streams to harmonize with FRP libraries or paradigms in ECMAScript, but not necessarily be based on or implement them. Kris Kowal's [GTOR](https://github.com/kriskowal/gtor/) goes into some more details on how this might work, and I am optimistic especially that as ES gains e.g. [async iterators](https://github.com/zenparsing/async-iteration/) the integration will be fluid and simple---while not sacrificing our focus on being able to efficiently wrap low-level byte sources and sinks. Closing, but thanks for the prompting and discussion, all!
