### ISSUE TITLE
Interface for push based ReadableStream?

### ISSUE THREAD

**Issue by mrkurt** [whatwg/streams#889]
Hi! I'm working on a proxy that needs to give user code a stream interface, but only actually read the underlying data on demand. As far as I can tell, this matches the description [push based data sources](https://github.com/whatwg/streams/blob/master/Requirements.md#you-must-be-able-to-efficiently-adapt-existing-push-based-data-sources-into-a-uniform-streaming-interface).

Is there a standard interface for starting/pausing/resuming a push based `ReadableStream`, or should it be done ad hoc?

**Comment by domenic** [comment]
ReadableStream's public API is always pull. It can wrap an underlying push source though, as seen in e.g. https://streams.spec.whatwg.org/#example-rs-push-no-backpressure.

> but only actually read the underlying data on demand.

That sounds much more like a underlying pull source. See e.g. https://streams.spec.whatwg.org/#example-rs-pull.

**Comment by mrkurt** [comment]
Ah! Ok that makes things a little clearer. 

It might be a pull! Pull happens immediately when I create a readable stream, however, and what I really want is for it to do nothing at instantiation time, then do a lot as soon as it's read from. Is this a gross hack or does it fit the spirit of the spec?

```
let data = [1,2,3,4,5]
let pullCalled = false
let s = new ReadableStream({
  start(controller){ console.log("started") },
  pull(controller){
    if(!pullCalled){
      console.log("first pull noop")
      pullCalled = true
    }
    else if(pullCalled && data.length > 0){
      let i = data.shift()
      controller.enqueue(i)
      console.log(i)
    }
  }
})
```

**Comment by domenic** [comment]
pull() is called on initialization in order to fill the internal queue up to the default high water mark of 1, so that there is always data available to be read when the consumer asks. If you'd prefer to not have a high water mark of 1, you can set it as such when creating your readable stream, e.g. by passing `new CountQueuingStrategy({ highWaterMark: 0 })` as the second argument.

**Comment by mrkurt** [comment]
Nice, that will do what I need. Thank you!

**Comment by domenic** [comment]
Awesome! I'll close this issue then :).
