### ISSUE TITLE
Should writableStream.abort() reject on already-errored streams?

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#900]
As noted in #847, this can lead to lots of redundant `.catch(() => {})`s.

I think it's especially strange that this rejects given that we just resolve with undefined if the stream is already _closed_. If anything that's the case where you failed to abort. If you're already _errored_, then you've basically aborted the stream already.

So I'm inclined to change this. Any thoughts?

**Comment by ricea** [comment]
I agree we should change it. We already let `writer.abort()` not call underlying sink `abort()` if the stream is closed, so we're not providing a guarantee there.

The benefit of the current behaviour is that it lets you know if you accidentally called `abort()` twice, but that doesn't actually seem like such a serious bug: surplus calls to `abort()` are harmless anyway. Compared to that, the cost of having to stick in useless catch statements seems a lot more serious.

If there's some benefit to `abort()` throwing that I've forgotten it might change my mind, but at the moment the decision seems pretty clear-cut.

**Comment by domenic** [comment]
I think we've just gotten more experience with the APIs over time, especially as we write transform stream examples. So, our initial theorizing about "more errors is nice" turns out to not be actually true in practice.

I'll work on a PR for this.
