### ISSUE TITLE
ReadableStream constructor: standard text and reference implementation doesn't match

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#917]
In the standard text, underlyingSource.type is looked up before strategy.size, but the reference implementation still uses destructuring assignment in the constructor arguments and so looks up "size" first.

This difference is observable, but none of our tests are observing it.

**Comment by ricea** [comment]
I'm going to work on it, and testing the ordering of lookups in all the constructors.

**Comment by ricea** [comment]
Turns out the WritableStream constructor in the reference implementation doesn't match either.

Some of these orderings are a little odd. For example, the WritableStream constructor looks up type, size and highWaterMark, and only then checks whether type is undefined or not. If I'm going to write a test for this, I'd rather the behaviour be something I can explain. @domenic would it be okay to reorder things so that parameters are in general checked right after being looked up?

**Comment by domenic** [comment]
I think the idea was to make things easier to implement using destructuring or Web IDL. In those cases, lookups all happen first, then inspection of the extracted values.

**Comment by ricea** [comment]
It's easy enough for a JS implementation to switch from destructuring to explicitly lookups. Blink's implementation has switched back and forth at various times. So I'm not worried about that.

However, for C++ implementations, trying to unpack an options object directly from C++ can be cumbersome and buggy, as Blink's RequestInit constructor demonstrates: https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/fetch/RequestInit.cpp?q=RequestInit::RequestInit.

If you use WebIDL then you end up with this algorithm:

https://heycam.github.io/webidl/#es-dictionary

On the positive side, most validation ends up interleaved with lookup this way, which is how I want to do it. On the negative

- WebIDL wants us to [convert](https://heycam.github.io/webidl/#dfn-convert-ecmascript-to-idl-value) the arguments in order. This is problematic now that we've split out the digestion of the underlying object into SetUp\*DefaultControllerFromUnderlying\*, which always happens after processing the strategy.
- WebIDL wants us to lookup dictionary members in lexicographical order. This is doable but annoying.
- The check that highWaterMark is >=0 will happen in a later step from the conversion of highWaterMark to a number, which is really weird from the point of view of our standard text.

Having said that, I haven't written a C++ implementation and I don't know how big of a problem this is in practice. @tschneidereit, do you have any input?

I'm thinking the solution may be to add a normative note to each constructor saying something like "All these lookups, type conversions, and validations must be performed, but implementations may change the order".

**Comment by domenic** [comment]
I'd rather not allow implementation-defined ordering. If you think it's too weird to write the standard text in a way that mimics Web IDL order, then we should just do the natural-for-JS order and implementations that would prefer to use Web IDL can be content to fail the ordering tests.

**Comment by ricea** [comment]
> If we have implementations that already know that they'd go this route, then we might as well admit that we're leaving the order implementation-defined :/

I just looked at WebKit's implementation, and it's using JS with no destructuring assignment. They use IDL together with the JavaScript somehow, but they just use `any` for the options arguments rather than dictionaries. So I'm counting them in the "don't care" camp. I have a vague recollection that Edge had some difficulties because they were using WebIDL in their implementation, but I can't remember where I heard that and I don't know anyone I could ask to get an opinion.

So, I'm going to conclude that there's no significant implementer restrictions on ordering, and we can do what makes sense for the standard.

Since the TransformStream constructor has two strategy arguments and so can't use destructuring assignment for them, I'm going to say that for consistency none of the constructors should use destructuring assignment.

Here's the current order of lookups/validations for the ReadableStream constructor:

1. Lookup _type_
2. Lookup _size_
3. Lookup _highWaterMark_
4. ToString(_type_)
5. toNumber and validate _highWaterMark_
6. Validate _size_
7. Lookup _pull_
8. Validate _pull_
9. Lookup _cancel_
10. Validate _cancel_
11. Lookup _start_
12. Validate _start_

The reason the lookups for size and highWaterMark are separated from their validations is so they can be factored out of the "if" statement based on the type. So there's actually not much I want to change here, except I'd like to validate _size_ before _highWaterMark_, because that's what WritableStream and TransformStream do.

**Comment by tschneidereit** [comment]
> [T]he TransformStream constructor has two strategy arguments and so can't use destructuring assignment for them

Why not? This seems like it'd work:
```
class TransformStream {
  constructor({transformer = {}, 
              {size: writableSizeFunction, highWaterMark: writableHighWaterMark} = {},
              {size: readableSizeFunction, highWaterMark: readableHighWaterMark} = {})
  {}
}
```

> I'm going to say that for consistency none of the constructors should use destructuring assignment.

I think this is an entirely fine outcome, but if you only want to do it this way because destructuring wouldn't work, then perhaps that's not needed.

**Comment by ricea** [comment]
> Why not? This seems like it'd work:

> ```javascript
> class TransformStream {
> constructor({transformer = {}, 
>              {size: writableSizeFunction, highWaterMark: writableHighWaterMark} = {},
>              {size: readableSizeFunction, highWaterMark: readableHighWaterMark} = {})
>  {}
> }
> ```

I didn't know you could do that. But I still have a mild preference for making the lookups explicit. Interleaving them with the validations feels more natural to me.

**Comment by tschneidereit** [comment]
> I didn't know you could do that. But I still have a mild preference for making the lookups explicit. Interleaving them with the validations feels more natural to me.

Fair enough. Though that'd prevent us from ever going to a spec style that makes use of WebIDL or something similar, right?

**Comment by ricea** [comment]
> Fair enough. Though that'd prevent us from ever going to a spec style that makes use of WebIDL or something similar, right?

Never say never. It will probably be a good long while before any web developers manage to develop an implicit dependency on the order of validations. In the meantime, it's low cost to change it around if the benefit is sufficient.

**Comment by ricea** [comment]
Accommodating future addition of byte types to WritableStream and TransformStream makes this messier than I realised. I'd like to list out my priorities, for my own benefit as much as anything. From high importance to low importance:

1. Avoid duplication. In particular, this means that size needs to be looked up separately from validating it, since the validation depends on the type of the stream, but the lookup is the same in both cases.
2. Try to avoid having to change the order again when we add byte streams.
3. Perform lookups close to the point of use.
4. Perform validation soon after lookup.
5. Be consistent. The ordering should match between the different types where it doesn't contradict the above.
6. Be explicit.

I suppose the alternative would be to not change anything and just test for the current order. But personally I'd rather take the opportunity to make it make sense.

**Comment by domenic** [comment]
Looking at https://github.com/ricea/web-platform-tests/blob/f7aab0af8bf4ffc4aa24ce4bb5299b0a063ff8ef/streams/readable-byte-streams/constructor.js#L9 is a bit concerning. The logic is not very transparent. Additionally, it's interesting that we disallow some things but ignore others; e.g. we ignore autoAllocateChunkSize for non-byte streams, but disallow a size() in the strategy.

A variant that would make the most sense to me would be:

```js
  op('get', 'cancel'),
  op('validate', 'cancel'),
  op('get', 'pull'),
  op('validate', 'pull'),
  op('get', 'start'),
  op('validate', 'start'),
  op('get', 'type'),
  op('validate', 'type'),
  op('get', 'autoAllocateChunkSize'),      // *
  op('tonumber', 'autoAllocateChunkSize'), // *
  op('validate', 'autoAllocateChunkSize'), // *
  op('get', 'size'),                       // **
  op('validate', 'size'),                  // **
  op('get', 'highWaterMark'),
  op('tonumber', 'highWaterMark'),
  op('validate', 'highWaterMark'),
```

Then

- * = either omit if type !== 'bytes', or omit the tonumber and change the validate to throw, or just omit the tonumber/validate
- ** = either omit if type === 'bytes', or change the validate to throw, or just omit the validate

The principles here are:

- left to right argument processing
- alphabetical within arguments
- type conversion/validation happens immediately after getting

It's worth noting that the semantics with * = omit the tonumber/validate and ** = omit the validate are then exactly what you'd get with Web IDL.

We'd then want to extend these principles to the other cases besides readable byte stream.

I realize this would be harder to factor, given that it would require logic that is currently in SetUpReadableByteStreamControllerFromUnderlyingSource to be put back in the constructor. So maybe it's not worth it. I'm totally happy to accept #922 and associated tests, and revisit this later if someone else complains. The more important thing is just picking an order, and aligning the reference implementation/tests together, and in that regard #922 suffices. But I thought it'd be good to write out my thoughts.

**Comment by domenic** [comment]
> Including autoAllocateChunkSize where it isn't needed is much less confusing: either you forgot type: 'bytes', which case you'll find out when your access to controller.byobRequest fails, or you just included autoAllocateChunkSize where it was meaningless, in which case it behaves just like all other meaningless properties: it does nothing.

Hmm, why can't we say that you included size where it was meaningless, and in such cases, it should do nothing?
