### ISSUE TITLE
Numeric conversion is not done on autoAllocateChunkSize

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#921]
https://streams.spec.whatwg.org/commit-snapshots/6f97246dd5577b2b15a8991b5bc5f63939c8f59d/#set-up-readable-byte-stream-controller-from-underlying-source

> If \! IsInteger\(autoAllocateChunkSize\) is false

In other cases when we accept a number, we call ToNumber() on it. For example, you can do new ReadableStream({}, { highWaterMark: "7" }) and it will do what you'd expect. But we don't do this for autoAllocateChunkSize. We probably should.

@domenic Do you know of any reason not to do this?

**Comment by domenic** [comment]
This is just a bug; great find.

**Comment by ricea** [comment]
Fixed in #922.
