### ISSUE TITLE
Permit freeing underlying source / sink / transformer after close

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#932]
Once a stream is closed or errored, none of the methods on the underlying source / sink / transformer will be called any more. As a quality-of-implementation enhancement some browsers might decide to drop their references at that point so that the underlying object can be garbage collected even if the stream is still referenced.

This is currently a valid optimisation, however if someone adds weak refs to Javascript it will become observable.

I propose that we explicitly drop the references in the standard to ensure this optimisation is valid. Implementations still won't be required to drop the references because they're not required to perform GC at any particular time or on any particular object.

**Comment by domenic** [comment]
Great catch, and strong +1. Weird to think about weak references making this sort of thing observable :-/.

**Comment by ricea** [comment]
It's actually tricky to follow through all the operations to find the necessary and sufficient places to clear the algorithms slots, so I decided I'd do TransformStream, ReadableStream and WritableStream separately to make it easier.

**Comment by ricea** [comment]
As @domenic mentioned in #944, we also need to clear [[strategySizeAlgorithm]].

**Comment by ricea** [comment]
All done.
