### ISSUE TITLE
WritableStreamDefaultWriterGetDesiredSize(writer) cannot in general be used to determine size of chunks read by pipeTo

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#938]
https://streams.spec.whatwg.org/commit-snapshots/d422f997bcdd6435fcc2e7eb531ee5635dae4887/#ref-for-chunk①⑧

> If reader is a BYOB reader, WritableStreamDefaultWriterGetDesiredSize\(writer\) should be used to determine the size of the chunks read from reader\.

This doesn't work unless the strategy of _writer_ measures chunks in bytes. In general it is not possible to determine this except possibly by checking the strategy `size` function for equality with `ByteLengthQueuingStrategy.prototype.size`.

I've discussed this with @domenic before, but I don't think we have an issue filed. I think we should try to find some text that retains the intent while not expecting implementations to do things that make no sense.

**Comment by domenic** [comment]
Hmm. I'm not sure this is so nonsensical. The whole piping/backpressure infrastructure basically relies on matching notions of "size" across the pipe. Or if not relies, at least assumes.

So the intention of this, from what I can tell, is: the writer says it wants 1024 Xs. We normally don't know how to get 1024 Xs; we just read one chunk, measure the size, and see how many Xs we got, then adjust as we go along. But if you're piping a readable byte stream to something that says it wants 1024 Xs, let's assume X is "bytes", and then we can ask the readable byte stream for exactly 1024 of those.

Seems OK?

**Comment by ricea** [comment]
Even if we assume bytes, we still have to sanity check the value. For TextDecoderStream, I want to set HWM to 1 to avoid adding unneeded buffering to the pipe. But if pipeTo() read 1 byte at a time, that would be pretty catastrophic for efficiency.

On the other end of the scale, the writable might have HWM set to `Infinity` to disable flow control altogether.

I haven't got any good answer except maybe to say that "implementations should choose a reasonable value".

**Comment by domenic** [comment]
> For TextDecoderStream, I want to set HWM to 1 to avoid adding unneeded buffering to the pipe. But if pipeTo() read 1 byte at a time, that would be pretty catastrophic for efficiency.

Hmmm, fair point. This seems like a more general issue with how desiredSize gets communicated along pipe chains and transform streams?? :-/ Like if I do

```js
byteReadable
  .pipeThrough(new TextDecoderStream())
  .pipeTo(new WritableStream(..., {
     highWaterMark: 1024,
     size(string) { return string.length; }
  });
```

then ideally you should be pulling ~1024 byte chunks (under an assumption of 1 code point ~ 1 byte), not 1-byte chunks...

I'm not sure the infrastructure there would be tractable or desirable to build, but it might be worth exploring? Or maybe I'm thinking of this all wrong in some way...

**Comment by ricea** [comment]
I think part of the problem is that we've got highWaterMark serving double-duty as controlling buffering and communicating optimal chunk size.

Choosing the chunk size at the head of the pipe in a way that doesn't require global knowledge of the rest of the pipe is hard. I've been thinking along the lines of a feature for advanced users that permits an underlying sink to specifically state what size of chunks it wants. Maybe in combination with a feature for TransformStream where you can specify a function that provides a (possibly approximate) back-mapping from sizes on the readable side to sizes on the writable side.

**Comment by domenic** [comment]
Ah, that's a great analysis, I agree completely. OK, maybe we should file that for future investigation, and just focus on fixing this bug...

Can you think of anything besides just being very vague? E.g. my first draft would be

> If reader is a BYOB reader, WritableStreamDefaultWriterGetDesiredSize(writer) may be used as input to determine the size of the chunks read from reader.

perhaps coupled with some discussions about how this falls down in some cases (mismatched chunk types, desired size of 1)

Or just delete it... :-/.

**Comment by ricea** [comment]
I've got an alternative formulation that just adds the words "as a basis":

> If reader is a BYOB reader, WritableStreamDefaultWriterGetDesiredSize(writer) should be used as a basis to determine the size of the chunks read from reader.

We could maybe have a note something like:

> Note: It's frequently inefficient to read chunks that are too small or too large. Other information might be factored in to determine the optimal chunk size.

**Comment by domenic** [comment]
Yeah, that sounds good, as long as we have the note.
