### ISSUE TITLE
Question: Should Streams have the prototype for `Symbol.toStringTag` and `toString` declared?

### ISSUE THREAD

**Issue by ThisIsMissEm** [whatwg/streams#952]
In certain implementations of whatwg streams, I've come across them not implementing `toString` or `Symbol.toStringTag` on the prototype meaning that if you're trying to find out if you've been given a stream (or another data type) then you have to rely on duck typing.

In the following, I'd expect to see `"[object ReadableStream]"` returned:
```js
let r = new ReadableStream()
// ReadableStream {}
r.toString()
// "[object Object]"
> Object.prototype.toString.call(r)
// "[object Object]"
```

In Safari these all return as I'd expect, in Chrome and Firefox they return `"[object Object]"`. The spec doesn't actually specify the toString behavior.

**Comment by ThisIsMissEm** [comment]
(Relatedly I've opened an issue on the node.js FormData module for the same issue: https://github.com/form-data/form-data/issues/396 )

**Comment by ricea** [comment]
Interesting point. It looks like "[object ReadableStream]" would be correct. I don't think it would hurt to be explicit about this in the standard. I'm not sure of the best way to do it. Perhaps specifying the value of ReadableStream.prototype[Symbol.toStringTag] is sufficient?

@domenic Can you suggest the correct way to specify this, off the top of your head?

**Comment by domenic** [comment]
Currently the spec required [object Object]. We could change this if we wanted, but I'm not sure what the benefits would be. People can just use x.constructor.name for the same effect.

**Comment by ricea** [comment]
I think the benefit is consistency. Language objects Promise, Map, WeakMap, and WeakSet all return
`"[object Foo]"`, and AFAIK all IDL types that don't specifically override it also return `"[object Foo]"`. Which leaves streams as a weird odd-one-out.
