### ISSUE TITLE
WHATWG icon is broken in Chrome in combination with ServiceWorker

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#955]
The streams icon is included in the HTML via the image tag

```html
<img alt="WHATWG" crossorigin="" height="100" 
src="https://resources.whatwg.org/logo-streams.svg">
```
However, the service worker preloads it with default fetch options, resulting in an opaque response. Chrome rejects the opaque response with the message: `The FetchEvent for "https://resources.whatwg.org/logo-streams.svg" resulted in a network error response: an "opaque" response was used for a request whose type is not no-cors`.

AFAIK Chrome is doing the right thing here.

This also affects the encoding standard and probably others.

**Comment by wanderview** [comment]
Where does the service worker preload it?

**Comment by domenic** [comment]
Thanks for reporting. It's in https://github.com/whatwg/whatwg.org/blob/ce5dff2c877057b8e4d9839cf865f347a57b9189/resources.whatwg.org/standard-service-worker.js, I believe in particular https://github.com/whatwg/whatwg.org/blob/ce5dff2c877057b8e4d9839cf865f347a57b9189/resources.whatwg.org/standard-service-worker.js#L23 .

Some previous discussion at https://github.com/whatwg/whatwg.org/issues/211 which sheds light as to how we got to this state.

Will put up a fix shortly.
