### ISSUE TITLE
Missing test coverage for destructuring arguments and GetV.

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#962]
For example `getReader(null)` should throw. `getReader(7)` should work. `getReader('hi')` should work, unless you set `String.prototype.mode = 'not byob'` first.

Similar concerns apply where the standard uses GetV.

**Comment by ricea** [comment]
If we switch to Web IDL `getReader(7)` will no longer work, so maybe we should hold off adding tests for it.

**Comment by domenic** [comment]
This is no longer supported after #1035, and idlharness tests it.
