### ISSUE TITLE
forAuthorCode can be a bit per reader

### ISSUE THREAD

**Issue by jorendorff** [whatwg/streams#964]
Eight different algorithms take a forAuthorCode argument, and it is passed to a lot of places. But if I understand the spec correctly, forAuthorCode is meant to be true iff the stream's current [[reader]] is visible to author code.

So it seems possible to give each reader a [[forAuthorCode]] field instead, and set it to false in AcquireReadableStreamDefaultReader.

This seems more direct, and might even be a nice simplification; if you agree, I'd like to contribute a patch.

**Comment by ricea** [comment]
This is a brilliant insight, thank you. If you're willing to create a patch, that would be great. You may need to sign the whatwg CLA (https://participate.whatwg.org/agreement) if you have not done so already.

**Comment by domenic** [comment]
In this case @jorendorff would just join https://github.com/mozilla-standards; I think @annevk or @dbaron can add you.

**Comment by annevk** [comment]
(Done, though still up to @jorendorff to decide whether to take this on of course.)

**Comment by jorendorff** [comment]
Thanks for taking a look! I'll put together a patch next week. (This is Thanksgiving week in the US, so I doubt I'll find time for it.)

**Comment by dbaron** [comment]
I'd note that, [as described](https://wiki.mozilla.org/Standards/GitHub_IPR_Organization), @jorendorff needs to make his membership in the organization public.
