### ISSUE TITLE
Ensure the JS thread doesn't have to get hit when piping two streams to each other

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#97]
E.g., an XHR stream to a file system stream, `xhrStream.pipeTo(fsStream)`.

As-is, there might be a problem if e.g. the user does

``` js
var oldWrite = fsStream.write;
fsStream.write = function (chunk) {
  console.log("AOP logging!!", chunk);
  oldWrite.apply(this, arguments);
};
```

after the pipe is already set up. The implementation would have to detect this and start routing data to the main thread, which kind of sucks.

A possible fix would be caching the value of `dest.write` at the top of `pipeTo`.

/cc @sicking

**Comment by domenic** [comment]
Quick update on this (old) issue: this is one of the highest priorities of the current design, pioneered with the stream reader concept. The only missing piece is a similar stream writer for writable streams. Once we have that in place this issue is done. We are very much on track though and have been designing the system around this goal.

**Comment by tyoshino** [comment]
> The only missing piece is a similar stream writer for writable streams.

This is happening at https://github.com/whatwg/streams/pull/462
