### ISSUE TITLE
SetUpReadableByteStreamController initializes [[pendingPullIntos]] twice

### ISSUE THREAD

**Issue by jorendorff** [whatwg/streams#975]
Step 5 is:

> 0. Perform ! ReadableByteStreamControllerClearPendingPullIntos(controller).

which sets controller.[[pendingPullIntos]] to an empty list; and then step 12 is:

> 0. Set controller.[[pendingPullIntos]] to a new empty List.

I think step 5 is redundant.

**Comment by ricea** [comment]
Yes, I agree. I will fix it unless you want to.

**Comment by jorendorff** [comment]
I can't get to it until the new year. Either is fine with me.
